In [1]:
import sys
import platform

print("Python:", sys.version)
print("Platform:", platform.platform())
print("Executable:", sys.executable)

Python: 3.13.16 (main, Oct  1 2026, 15:40:24) [GCC 13.3.0]
Platform: Linux-6.6.122+-x86_64-with-glibc2.39
Executable: /usr/bin/python3

In [2]:
from google.colab import files

uploaded = files.upload()

Saving XAgentic_Final_Paper_Evidence_2026-10-06 (1).zip to XAgentic_Final_Paper_Evidence_2026-10-06 (1).zip

In [3]:
import os

print(os.listdir("/content"))

['.config', 'XAgentic_Final_Paper_Evidence_2026-10-06 (1).zip', 'sample_data']

In [4]:
import os
import zipfile
import shutil

ZIP = "/content/XAgentic_Final_Paper_Evidence_2026-10-06 (1).zip"
WORK = "/content/xagentic_r1_work"

if os.path.exists(WORK):
    shutil.rmtree(WORK)

os.makedirs(WORK, exist_ok=True)

with zipfile.ZipFile(ZIP, "r") as z:
    z.extractall(WORK)

print("Extracted to:", WORK)

Extracted to: /content/xagentic_r1_work

In [5]:
!find /content/xagentic_r1_work -maxdepth 3 -type f | sort

/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/all_summary.json
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/comparison.csv
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/e1_models.csv
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/e1_seeds.csv
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/e1_summary.json
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/e2_explainers.csv
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/e2_summary.json
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/e3_summary.json
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/e3_variants.csv
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/e4_factorial.csv
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/e4_seeds.csv
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/e4_summary.json
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/fig_e2_latency.pdf
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/fig_e3_oov.pdf
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/fig_e4_combined.pdf
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/fig_escalation.pdf
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/fig_shap_global.pdf
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/final_e1_e4_5seeds.log
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/results_macros_seeds.tex
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/01_E1_E4_5SEED_FINAL/results_macros.tex
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/02_E5_QWEN37_N100_SEED52/all_summary.json
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/02_E5_QWEN37_N100_SEED52/comparison.csv
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/02_E5_QWEN37_N100_SEED52/corpus.csv
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/02_E5_QWEN37_N100_SEED52/e1_models.csv
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/02_E5_QWEN37_N100_SEED52/e1_summary.json
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/02_E5_QWEN37_N100_SEED52/e3_summary.json
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/02_E5_QWEN37_N100_SEED52/e3_variants.csv
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/02_E5_QWEN37_N100_SEED52/e4_factorial.csv
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/02_E5_QWEN37_N100_SEED52/e4_summary.json
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/02_E5_QWEN37_N100_SEED52/e5_agentic.csv
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/02_E5_QWEN37_N100_SEED52/e5_decisions.csv
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/02_E5_QWEN37_N100_SEED52/e5_summary.json
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/02_E5_QWEN37_N100_SEED52/fig_e5_agentic.pdf
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/02_E5_QWEN37_N100_SEED52/llm_cache.json
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/02_E5_QWEN37_N100_SEED52/qwen37_final_n100_seed52.log
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/03_SOURCE_CODE/agents.py
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/03_SOURCE_CODE/exp1_posthoc.py
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/03_SOURCE_CODE/exp2_inhoc.py
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/03_SOURCE_CODE/exp3_semantic.py
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/03_SOURCE_CODE/exp4_combined.py
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/03_SOURCE_CODE/exp5_agentic.py
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/03_SOURCE_CODE/run_all.py
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/03_SOURCE_CODE/run_seeds.py
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/03_SOURCE_CODE/xagentic_common.py
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/03_SOURCE_CODE/xagentic_slice.py
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/04_REPRODUCIBILITY/README.md
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/04_REPRODUCIBILITY/requirements.txt
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/FINAL_EVIDENCE_MANIFEST.txt
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/SHA256SUMS.txt

In [6]:
from pathlib import Path
import os

ROOT = Path(
    "/content/xagentic_r1_work/"
    "XAgentic_Final_Paper_Evidence_2026-10-06"
)

SRC = ROOT / "03_SOURCE_CODE"
E1_RESULTS = ROOT / "01_E1_E4_5SEED_FINAL"
E5_RESULTS = ROOT / "02_E5_QWEN37_N100_SEED52"

R1 = Path("/content/revision_experiments/R1_phrase_generalization")

print("ROOT exists      :", ROOT.exists())
print("SOURCE exists    :", SRC.exists())
print("E1 results exist :", E1_RESULTS.exists())
print("E5 results exist :", E5_RESULTS.exists())

print("\nSource files:")
for p in sorted(SRC.glob("*.py")):
    print(" ", p.name)

ROOT exists      : True
SOURCE exists    : True
E1 results exist : True
E5 results exist : True

Source files:
  agents.py
  exp1_posthoc.py
  exp2_inhoc.py
  exp3_semantic.py
  exp4_combined.py
  exp5_agentic.py
  run_all.py
  run_seeds.py
  xagentic_common.py
  xagentic_slice.py

In [7]:
import hashlib

checksum_file = ROOT / "SHA256SUMS.txt"

print(checksum_file.read_text()[:5000])

ff193306c06b126abc69fd26d3c47cb58bd9a3cc3ac49652ecf025f0b90c8b22  01_E1_E4_5SEED_FINAL/all_summary.json
d15bae8e7698809242e278ab56bdfb6f8e4e4e10af2837615aae7367607dad97  01_E1_E4_5SEED_FINAL/comparison.csv
1bbca656d6168c1c4a71e7c01369d6db11c46c19529e2db368215b14e6a7a2c0  01_E1_E4_5SEED_FINAL/e1_models.csv
189249507a9b6a113f6630a99f3363ee20f46ab9164732ac48df613d73960a63  01_E1_E4_5SEED_FINAL/e1_seeds.csv
2abb8be3fa05f7abe7fc6b984e9e564ef52be4c5f3c35fadb77181ff0aaa6c11  01_E1_E4_5SEED_FINAL/e1_summary.json
2ca8e8b427a33b5474126b683a76f10402e2ce583b6a6e97db05f810f2c4a1e4  01_E1_E4_5SEED_FINAL/e2_explainers.csv
04842b28db24c9491f8661b9e48c879607e9369cc36135c5d7b0729d1b27dda2  01_E1_E4_5SEED_FINAL/e2_summary.json
1c9589469db7199273bc2beadf86bd975e4694be8ffe32148fca5e8c6da9bd4f  01_E1_E4_5SEED_FINAL/e3_summary.json
4604cdb515ac159f6b5e0047a55ff6557feb20cca3a3df9ba08a1a9e06e13962  01_E1_E4_5SEED_FINAL/e3_variants.csv
b378e45ddec469028ebafa1c168a660fa49d05d1640c19450d9dc586ca0490dd  01_E1_E4_5SEED_FINAL/e4_factorial.csv
29239a6fa979d56a991f0803381a839c6a95c74650c5f481d2ceae2d232342b6  01_E1_E4_5SEED_FINAL/e4_seeds.csv
2928f6d258216d993330439861383badb0b035118c83087e5319cd375cbcfc22  01_E1_E4_5SEED_FINAL/e4_summary.json
fb59227ccc30a77b58903ae7a78baab252e8f525245203936e22901057460be3  01_E1_E4_5SEED_FINAL/fig_e2_latency.pdf
e84f37b2adc2ccaa0c45f2d546e1ded2a603308c954b9ee7fbac7190d938db77  01_E1_E4_5SEED_FINAL/fig_e3_oov.pdf
cd706ebe1af6ce8d46ce908f078c3d37578a61d1f6fb0b60ba62d3d4eda0a932  01_E1_E4_5SEED_FINAL/fig_e4_combined.pdf
bafd619120ecaa35b836a55016f74582de19d1283d61098e5bcf6a01fdd0cedf  01_E1_E4_5SEED_FINAL/fig_escalation.pdf
0e3a1cb95f983a284d38c3e73c40984d6e72cc7a96708aa11bdc4aad1a84705f  01_E1_E4_5SEED_FINAL/fig_shap_global.pdf
7dc991b0500c77b6c66038f6bc7ef977cebfb88060906beb53d18b9a49cb9dbe  01_E1_E4_5SEED_FINAL/final_e1_e4_5seeds.log
722530dd3c7ce3111d7a606f36d757ab15737a88e15570d5f07e0a24486f67b5  01_E1_E4_5SEED_FINAL/results_macros.tex
bbe1915be9b68fd862ba4479cb448d054a42faa9058262290d5d3e7fa2e0b6e6  01_E1_E4_5SEED_FINAL/results_macros_seeds.tex
f856772c7dcda25b911790b9e88f0ed70e8e9f8d56c6b50396ba47177470b3a6  01_E1_E4_5SEED_FINAL/seeds/all_summary_seed42.json
2eefefefd465e900fe16bedbb3cf75ecf82854904d035fae88d5f0f21d6109a9  01_E1_E4_5SEED_FINAL/seeds/all_summary_seed43.json
6c34b554b28d137107dc5b97bb2703de5ee11b95b426c8b23d6ee2fea0b9da8c  01_E1_E4_5SEED_FINAL/seeds/all_summary_seed44.json
6f9b13852c5f7c6f0d8860549e15ebfd10e595116164b8cd7d403f615b7285a4  01_E1_E4_5SEED_FINAL/seeds/all_summary_seed45.json
ff193306c06b126abc69fd26d3c47cb58bd9a3cc3ac49652ecf025f0b90c8b22  01_E1_E4_5SEED_FINAL/seeds/all_summary_seed46.json
f8ab2a1237dc69e7083a713b94f1178c4acc52367481be292b6434f940761057  01_E1_E4_5SEED_FINAL/seeds/e1_models_seed42.csv
de1e13881f5e594e16f13acf62cb87839c96f5150996973d5a399668c2c5964a  01_E1_E4_5SEED_FINAL/seeds/e1_models_seed43.csv
eaec957fb0224d78d807a51c9776653dda63d34a2db394467876675e3eed5f44  01_E1_E4_5SEED_FINAL/seeds/e1_models_seed44.csv
4a1d743df14ded4f79cca7a888a3c714e803cc38d0adf9e7dc256ab6d8e7d325  01_E1_E4_5SEED_FINAL/seeds/e1_models_seed45.csv
1bbca656d6168c1c4a71e7c01369d6db11c46c19529e2db368215b14e6a7a2c0  01_E1_E4_5SEED_FINAL/seeds/e1_models_seed46.csv
676153597e6d12760b86bd7a258ee20d173497aa5c2db1a2e65fda17bc2f8ce6  01_E1_E4_5SEED_FINAL/seeds/e4_factorial_seed42.csv
9e0a08ad63070b7059aefed72f6bbd55d78db29ad4147d4eb02ceda3f8a8db90  01_E1_E4_5SEED_FINAL/seeds/e4_factorial_seed43.csv
c78413311e81e5580e26076dd476b8b68c9ce96a15e00a9709c40b8e168bc825  01_E1_E4_5SEED_FINAL/seeds/e4_factorial_seed44.csv
89ea1f10979bef373ee87800496af6538d97a35cdf523daf05ddf88968cce698  01_E1_E4_5SEED_FINAL/seeds/e4_factorial_seed45.csv
b378e45ddec469028ebafa1c168a660fa49d05d1640c19450d9dc586ca0490dd  01_E1_E4_5SEED_FINAL/seeds/e4_factorial_seed46.csv
7b67a6cf165fe99eda5e82c7b51f20774746bc23339cae343bc2ea29c85cb1e4  02_E5_QWEN37_N100_SEED52/all_summary.json
446a95ba65080725bceea13542f65c7cdd7edc5bab99ec45cc576d48451c6d53  02_E5_QWEN37_N100_SEED52/comparison.csv
5358e25a06c863fcb25b4d906608783d612c0b1411373f140573408555b04b08  02_E5_QWEN37_N100_SEED52/corpus.csv
5e16b7e291b6b7761f897b45f99a1820bf42beaed89b2853b81dbc52d95f4a51  02_E5_QWEN37_N100_SEED52/e1_models.csv
426a4944ed2450e27995be02f103215afd4948778c27f4a52626bc63bd7c019e  02_E5_QWEN37_N100_SEED52/e1_summary.json
3acca0bdc64e2163082e97ecd43f62f8020e87771d78ae82b2e2b6933409a6b9  02_E5_QWEN37_N100_SEED52/e3_summary.json
6085411ccf453438707250a76bfe77d7fb250c264583cfd01f909f8e345ac1ee  02_E5_QWEN37_N100_SEED52/e3_variants.csv
34d7bede9f9cd2410d41a8aca16ec219b29e2ea07390d443821724d457b0111e  02_E5_QWEN37_N100_SEED52/e4_factorial.csv
4787984a318a4e0fe5729195a8e75e925d544a44e5025d5cddb5d8a6050c1592  02_E5_QWEN37_N100_SEED52/e4_summary.json
14493fe3bd5c61b9e85752f637346ec7c046ab672e2af6a825970aaa5841619c  02_E5_QWEN37_N100_SEED52/e5_agentic.csv
2ae03f26b2c58c3f2e319dcdaa3eb0b91a70d5441c85a41aff4f981270ec0de7  02_E5_QWEN37_N100_SEED52/e5_decisions.csv
b3

In [8]:
files_to_inspect = [
    "xagentic_common.py",
    "xagentic_slice.py",
    "exp1_posthoc.py",
    "run_seeds.py",
    "run_all.py",
]

for filename in files_to_inspect:
    p = SRC / filename

    print("\n")
    print("=" * 110)
    print(filename)
    print("=" * 110)

    text = p.read_text(errors="replace")
    lines = text.splitlines()

    for i, line in enumerate(lines, start=1):
        if any(k.lower() in line.lower() for k in [
            "corpus",
            "dataset",
            "phrase",
            "intent",
            "train_test_split",
            "seed",
            "random_state",
            "tfidf",
            "vectorizer",
            "model",
            "classifier",
            "embb",
            "urllc",
            "mmtc",
        ]):
            start = max(0, i - 4)
            end = min(len(lines), i + 8)

            print(f"\n--- around line {i} ---")
            for j in range(start, end):
                print(f"{j+1:4d}: {lines[j]}")

==============================================================================================================
xagentic_common.py
==============================================================================================================

--- around line 5 ---
   2: Shared components for the Explainable Agentic AI slice-selection experiments.
   3:
   4: This module holds everything the three experiments have in common so that the
   5: comparison across them is strictly controlled: identical corpus, identical
   6: seed, identical train/test split, identical slice catalogue and safety contract.
   7:
   8:   E1  Post-hoc explanation          (exp1_posthoc.py)
   9:   E2  In-hoc vs post-hoc            (exp2_inhoc.py)
  10:   E3  Semantic Intent Agent         (exp3_semantic.py)
  11:
  12: Stages
  13:   S1  Synthetic intent + KPI corpus grounded in 3GPP TS 22.261 / TS 23.501

--- around line 6 ---
   3:
   4: This module holds everything the three experiments have in common so that the
   5: comparison across them is strictly controlled: identical corpus, identical
   6: seed, identical train/test split, identical slice catalogue and safety contract.
   7:
   8:   E1  Post-hoc explanation          (exp1_posthoc.py)
   9:   E2  In-hoc vs post-hoc            (exp2_inhoc.py)
  10:   E3  Semantic Intent Agent         (exp3_semantic.py)
  11:
  12: Stages
  13:   S1  Synthetic intent + KPI corpus grounded in 3GPP TS 22.261 / TS 23.501
  14:   S2  Intent Agent      : NL intent -> structured intent vector (slot filling)

--- around line 10 ---
   7:
   8:   E1  Post-hoc explanation          (exp1_posthoc.py)
   9:   E2  In-hoc vs post-hoc            (exp2_inhoc.py)
  10:   E3  Semantic Intent Agent         (exp3_semantic.py)
  11:
  12: Stages
  13:   S1  Synthetic intent + KPI corpus grounded in 3GPP TS 22.261 / TS 23.501
  14:   S2  Intent Agent      : NL intent -> structured intent vector (slot filling)
  15:   S3  Candidate Agent   : SST/feasibility screening against a slice catalogue
  16:   S4  Selection Agent   : supervised slice classifier
  17:   S5  Validation Agent  : safety-contract check (3GPP KPI envelopes)
  18:   S6  Explanation Agent : attribution (post-hoc or in-hoc, per experiment)

--- around line 13 ---
  10:   E3  Semantic Intent Agent         (exp3_semantic.py)
  11:
  12: Stages
  13:   S1  Synthetic intent + KPI corpus grounded in 3GPP TS 22.261 / TS 23.501
  14:   S2  Intent Agent      : NL intent -> structured intent vector (slot filling)
  15:   S3  Candidate Agent   : SST/feasibility screening against a slice catalogue
  16:   S4  Selection Agent   : supervised slice classifier
  17:   S5  Validation Agent  : safety-contract check (3GPP KPI envelopes)
  18:   S6  Explanation Agent : attribution (post-hoc or in-hoc, per experiment)
  19: """
  20:
  21: from __future__ import annotations

--- around line 14 ---
  11:
  12: Stages
  13:   S1  Synthetic intent + KPI corpus grounded in 3GPP TS 22.261 / TS 23.501
  14:   S2  Intent Agent      : NL intent -> structured intent vector (slot filling)
  15:   S3  Candidate Agent   : SST/feasibility screening against a slice catalogue
  16:   S4  Selection Agent   : supervised slice classifier
  17:   S5  Validation Agent  : safety-contract check (3GPP KPI envelopes)
  18:   S6  Explanation Agent : attribution (post-hoc or in-hoc, per experiment)
  19: """
  20:
  21: from __future__ import annotations
  22:

--- around line 16 ---
  13:   S1  Synthetic intent + KPI corpus grounded in 3GPP TS 22.261 / TS 23.501
  14:   S2  Intent Agent      : NL intent -> structured intent vector (slot filling)
  15:   S3  Candidate Agent   : SST/feasibility screening against a slice catalogue
  16:   S4  Selection Agent   : supervised slice classifier
  17:   S5  Validation Agent  : safety-contract check (3GPP KPI envelopes)
  18:   S6  Explanation Agent : attribution (post-hoc or in-hoc, per experiment)
  19: """
  20:
  21: from __future__ import annotations
  22:
  23: import json
  24: import os

--- around line 33 ---
  30: import numpy as np
  31: import pandas as pd
  32:
  33: SEED = int(os.environ.get("XAGENTIC_SEED", "42"))
  34: random.seed(SEED)
  35: np.random.seed(SEED)
  36:
  37: ROOT = os.path.dirname(os.path.abspath(__file__))
  38: OUT = os.path.join(ROOT, "results")
  39: os.makedirs(OUT, exist_ok=True)
  40:
  41: SLICES = ["eMBB", "URLLC", "mMTC"]

--- around line 34 ---
  31: import pandas as pd
  32:
  33: SEED = int(os.environ.get("XAGENTIC_SEED", "42"))
  34: random.seed(SEED)
  35: np.random.seed(SEED)
  36:
  37: ROOT = os.path.dirname(os.path.abspath(__file__))
  38: OUT = os.path.join(ROOT, "results")
  39: os.makedirs(OUT, exist_ok=True)
  40:
  41: SLICES = ["eMBB", "URLLC", "mMTC"]
  42: SLICE_ID = {s: i for i, s in enumerate(SLICES)}

--- around line 35 ---
  32:
  33: SEED = int(os.environ.get("XAGENTIC_SEED", "42"))
  34: random.seed(SEED)
  35: np.random.seed(SEED)
  36:
  37: ROOT = os.path.dirname(os.path.abspath(__file__))
  38: OUT = os.path.join(ROOT, "results")
  39: os.makedirs(OUT, exist_ok=True)
  40:
  41: SLICES = ["eMBB", "URLLC", "mMTC"]
  42: SLICE_ID = {s: i for i, s in enumerate(SLICES)}
  43:

--- around line 41 ---
  38: OUT = os.path.join(ROOT, "results")
  39: os.makedirs(OUT, exist_ok=True)
  40:
  41: SLICES = ["eMBB", "URLLC", "mMTC"]
  42: SLICE_ID = {s: i for i, s in enumerate(SLICES)}
  43:
  44: N_CORPUS = 3000
  45: TEST_SIZE = 0.30
  46:
  47: # ---------------------------------------------------------------------------
  48: # S1. Slice catalogue + synthetic intent/KPI corpus
  49: # ---------------------------------------------------------------------------

--- around line 44 ---
  41: SLICES = ["eMBB", "URLLC", "mMTC"]
  42: SLICE_ID = {s: i for i, s in enumerate(SLICES)}
  43:
  44: N_CORPUS = 3000
  45: TEST_SIZE = 0.30
  46:
  47: # ---------------------------------------------------------------------------
  48: # S1. Slice catalogue + synthetic intent/KPI corpus
  49: # ---------------------------------------------------------------------------
  50:
  51: # 3GPP-informed KPI envelopes per standardised slice/service type (SST).
  52: CATALOGUE = {

--- around line 48 ---
  45: TEST_SIZE = 0.30
  46:
  47: # ---------------------------------------------------------------------------
  48: # S1. Slice catalogue + synthetic intent/KPI corpus
  49: # ---------------------------------------------------------------------------
  50:
  51: # 3GPP-informed KPI envelopes per standardised slice/service type (SST).
  52: CATALOGUE = {
  53:     "eMBB":  dict(lat=(10.0, 150.0), thr=(25.0, 1000.0), rel=(99.0, 99.9),
  54:                   den=(1e2, 5e4), mob=(0.0, 250.0), sst=1),
  55:     "URLLC": dict(lat=(0.5, 10.0), thr=(0.1, 100.0), rel=(99.99, 99.9999),
  56:                   den=(1e2, 1e4), mob=(0.0, 500.0), sst=2),

--- around line 53 ---
  50:
  51: # 3GPP-informed KPI envelopes per standardised slice/service type (SST).
  52: CATALOGUE = {
  53:     "eMBB":  dict(lat=(10.0, 150.0), thr=(25.0, 1000.0), rel=(99.0, 99.9),
  54:                   den=(1e2, 5e4), mob=(0.0, 250.0), sst=1),
  55:     "URLLC": dict(lat=(0.5, 10.0), thr=(0.1, 100.0), rel=(99.99, 99.9999),
  56:                   den=(1e2, 1e4), mob=(0.0, 500.0), sst=2),
  57:     "mMTC":  dict(lat=(50.0, 10000.0), thr=(0.001, 2.0), rel=(95.0, 99.9),
  58:                   den=(1e4, 1e6), mob=(0.0, 30.0), sst=3),
  59: }
  60:
  61: # Use cases the Intent Agent's design-time lexicon has seen.

--- around line 55 ---
  52: CATALOGUE = {
  53:     "eMBB":  dict(lat=(10.0, 150.0), thr=(25.0, 1000.0), rel=(99.0, 99.9),
  54:                   den=(1e2, 5e4), mob=(0.0, 250.0), sst=1),
  55:     "URLLC": dict(lat=(0.5, 10.0), thr=(0.1, 100.0), rel=(99.99, 99.9999),
  56:                   den=(1e2, 1e4), mob=(0.0, 500.0), sst=2),
  57:     "mMTC":  dict(lat=(50.0, 10000.0), thr=(0.001, 2.0), rel=(95.0, 99.9),
  58:                   den=(1e4, 1e6), mob=(0.0, 30.0), sst=3),
  59: }
  60:
  61: # Use cases the Intent Agent's design-time lexicon has seen.
  62: USE_CASES_KNOWN = {
  63:     "eMBB": ["4K video streaming", "AR/VR gaming", "live broadcast",

--- around line 57 ---
  54:                   den=(1e2, 5e4), mob=(0.0, 250.0), sst=1),
  55:     "URLLC": dict(lat=(0.5, 10.0), thr=(0.1, 100.0), rel=(99.99, 99.9999),
  56:                   den=(1e2, 1e4), mob=(0.0, 500.0), sst=2),
  57:     "mMTC":  dict(lat=(50.0, 10000.0), thr=(0.001, 2.0), rel=(95.0, 99.9),
  58:                   den=(1e4, 1e6), mob=(0.0, 30.0), sst=3),
  59: }
  60:
  61: # Use cases the Intent Agent's design-time lexicon has seen.
  62: USE_CASES_KNOWN = {
  63:     "eMBB": ["4K video streaming", "AR/VR gaming", "live broadcast",
  64:              "fixed wireless access", "stadium hotspot"],
  65:     "URLLC": ["factory robot control", "remote surgery", "smart-grid protection",

--- around line 61 ---
  58:                   den=(1e4, 1e6), mob=(0.0, 30.0), sst=3),
  59: }
  60:
  61: # Use cases the Intent Agent's design-time lexicon has seen.
  62: USE_CASES_KNOWN = {
  63:     "eMBB": ["4K video streaming", "AR/VR gaming", "live broadcast",
  64:              "fixed wireless access", "stadium hotspot"],
  65:     "URLLC": ["factory robot control", "remote surgery", "smart-grid protection",
  66:               "drone fleet control", "haptic teleoperation"],
  67:     "mMTC": ["smart water meters", "agricultural sensors", "asset trackers",
  68:              "environmental monitoring", "pipeline telemetry"],
  69: }

--- around line 63 ---
  60:
  61: # Use cases the Intent Agent's design-time lexicon has seen.
  62: USE_CASES_KNOWN = {
  63:     "eMBB": ["4K video streaming", "AR/VR gaming", "live broadcast",
  64:              "fixed wireless access", "stadium hotspot"],
  65:     "URLLC": ["factory robot control", "remote surgery", "smart-grid protection",
  66:               "drone fleet control", "haptic teleoperation"],
  67:     "mMTC": ["smart water meters", "agricultural sensors", "asset trackers",
  68:              "environmental monitoring", "pipeline telemetry"],
  69: }
  70:
  71: # Lexically *unseen* use cases: realistic open-vocabulary drift. They carry no

--- around line 65 ---
  62: USE_CASES_KNOWN = {
  63:     "eMBB": ["4K video streaming", "AR/VR gaming", "live broadcast",
  64:              "fixed wireless access", "stadium hotspot"],
  65:     "URLLC": ["factory robot control", "remote surgery", "smart-grid protection",
  66:               "drone fleet control", "haptic teleoperation"],
  67:     "mMTC": ["smart water meters", "agricultural sensors", "asset trackers",
  68:              "environmental monitoring", "pipeline telemetry"],
  69: }
  70:
  71: # Lexically *unseen* use cases: realistic open-vocabulary drift. They carry no
  72: # exact keyword signal, so a lexicon-based agent must fall back to KPI slots.
  73: USE_CASES_UNSEEN = {

--- around line 67 ---
  64:              "fixed wireless access", "stadium hotspot"],
  65:     "URLLC": ["factory robot control", "remote surgery", "smart-grid protection",
  66:               "drone fleet control", "haptic teleoperation"],
  67:     "mMTC": ["smart water meters", "agricultural sensors", "asset trackers",
  68:              "environmental monitoring", "pipeline telemetry"],
  69: }
  70:
  71: # Lexically *unseen* use cases: realistic open-vocabulary drift. They carry no
  72: # exact keyword signal, so a lexicon-based agent must fall back to KPI slots.
  73: USE_CASES_UNSEEN = {
  74:     "eMBB": ["high-definition conferencing", "digital signage uplink",
  75:              "newsroom contribution feed", "in-flight entertainment uplink"],

--- around line 74 ---
  71: # Lexically *unseen* use cases: realistic open-vocabulary drift. They carry no
  72: # exact keyword signal, so a lexicon-based agent must fall back to KPI slots.
  73: USE_CASES_UNSEEN = {
  74:     "eMBB": ["high-definition conferencing", "digital signage uplink",
  75:              "newsroom contribution feed", "in-flight entertainment uplink"],
  76:     "URLLC": ["port crane synchronisation", "substation differential tripping",
  77:               "rail interlocking signalling", "surgical imaging feedback"],
  78:     "mMTC": ["utility submetering fleet", "soil-moisture reporting nodes",
  79:              "cold-chain condition reporting", "street luminaire telemetry"],
  80: }
  81:
  82: # Vertical-agnostic phrasings that give the agent no lexical prior at all.

--- around line 76 ---
  73: USE_CASES_UNSEEN = {
  74:     "eMBB": ["high-definition conferencing", "digital signage uplink",
  75:              "newsroom contribution feed", "in-flight entertainment uplink"],
  76:     "URLLC": ["port crane synchronisation", "substation differential tripping",
  77:               "rail interlocking signalling", "surgical imaging feedback"],
  78:     "mMTC": ["utility submetering fleet", "soil-moisture reporting nodes",
  79:              "cold-chain condition reporting", "street luminaire telemetry"],
  80: }
  81:
  82: # Vertical-agnostic phrasings that give the agent no lexical prior at all.
  83: GENERIC_USE_CASES = [
  84:     "campus connectivity", "enterprise application", "smart city service",

--- around line 78 ---
  75:              "newsroom contribution feed", "in-flight entertainment uplink"],
  76:     "URLLC": ["port crane synchronisation", "substation differential tripping",
  77:               "rail interlocking signalling", "surgical imaging feedback"],
  78:     "mMTC": ["utility submetering fleet", "soil-moisture reporting nodes",
  79:              "cold-chain condition reporting", "street luminaire telemetry"],
  80: }
  81:
  82: # Vertical-agnostic phrasings that give the agent no lexical prior at all.
  83: GENERIC_USE_CASES = [
  84:     "campus connectivity", "enterprise application", "smart city service",
  85:     "public safety communications", "retail branch connectivity",
  86:     "municipal network service", "event coverage service", "research testbed service",

--- around line 121 ---
 118:     return f"{x:.3f}"
 119:
 120:
 121: def synth_corpus(n=N_CORPUS, p_amb=0.30, seed=SEED):
 122:     """Generate NL intents with latent ground-truth slice labels.
 123:
 124:     Two difficulty dimensions are controlled independently:
 125:       * KPI ambiguity   -- a fraction `p_amb` of requests have KPI targets
 126:         blended towards a neighbouring slice envelope;
 127:       * vocabulary drift -- only ~40% of intents use a use-case phrase the
 128:         design-time lexicon covers; the rest are unseen or generic.
 129:

--- around line 122 ---
 119:
 120:
 121: def synth_corpus(n=N_CORPUS, p_amb=0.30, seed=SEED):
 122:     """Generate NL intents with latent ground-truth slice labels.
 123:
 124:     Two difficulty dimensions are controlled independently:
 125:       * KPI ambiguity   -- a fraction `p_amb` of requests have KPI targets
 126:         blended towards a neighbouring slice envelope;
 127:       * vocabulary drift -- only ~40% of intents use a use-case phrase the
 128:         design-time lexicon covers; the rest are unseen or generic.
 129:
 130:     The ground-truth label is the *pre-blending* latent slice type.

--- around line 127 ---
 124:     Two difficulty dimensions are controlled independently:
 125:       * KPI ambiguity   -- a fraction `p_amb` of requests have KPI targets
 126:         blended towards a neighbouring slice envelope;
 127:       * vocabulary drift -- only ~40% of intents use a use-case phrase the
 128:         design-time lexicon covers; the rest are unseen or generic.
 129:
 130:     The ground-truth label is the *pre-blending* latent slice type.
 131:     """
 132:     rng = np.random.default_rng(seed)
 133:     rows = []
 134:     for i in range(n):
 135:         label = SLICES[i % 3]

--- around line 132 ---
 129:
 130:     The ground-truth label is the *pre-blending* latent slice type.
 131:     """
 132:     rng = np.random.default_rng(seed)
 133:     rows = []
 134:     for i in range(n):
 135:         label = SLICES[i % 3]
 136:         c = CATALOGUE[label]
 137:         lat = _loguniform(*c["lat"], rng)
 138:         thr = _loguniform(*c["thr"], rng)
 139:         rel = float(rng.uniform(*c["rel"]))
 140:         den = _loguniform(*c["den"], rng)

--- around line 186 ---
 183:
 184:
 185: # ---------------------------------------------------------------------------
 186: # S2. Intent Agent -- deterministic slot-filling NLU
 187: # ---------------------------------------------------------------------------
 188:
 189: NUM = r"([0-9][0-9,]*\.?[0-9]*)"
 190:
 191: PATTERNS = {
 192:     "latency_ms": [
 193:         rf"(?:latency|delay)[^.;]*?(?:under|below|of|budget:?|bound)?\s*{NUM}\s*ms",
 194:         rf"{NUM}\s*ms\s*(?:one-way\s*)?(?:latency|delay|budget)",

--- around line 216 ---
 213: # Design-time domain lexicon: exact substring match only. This is deliberately
 214: # brittle -- quantifying that brittleness is the point of Experiment 3.
 215: LEXICON = {
 216:     "URLLC": ["robot control", "surgery", "grid protection", "drone fleet", "haptic",
 217:               "teleoperation"],
 218:     "mMTC": ["water meter", "agricultural sensor", "asset tracker",
 219:              "environmental monitoring", "pipeline telemetry"],
 220:     "eMBB": ["4k video", "ar/vr", "live broadcast", "fixed wireless access",
 221:              "stadium hotspot"],
 222: }
 223:
 224:

--- around line 218 ---
 215: LEXICON = {
 216:     "URLLC": ["robot control", "surgery", "grid protection", "drone fleet", "haptic",
 217:               "teleoperation"],
 218:     "mMTC": ["water meter", "agricultural sensor", "asset tracker",
 219:              "environmental monitoring", "pipeline telemetry"],
 220:     "eMBB": ["4k video", "ar/vr", "live broadcast", "fixed wireless access",
 221:              "stadium hotspot"],
 222: }
 223:
 224:
 225: @dataclass
 226: class Intent:

--- around line 220 ---
 217:               "teleoperation"],
 218:     "mMTC": ["water meter", "agricultural sensor", "asset tracker",
 219:              "environmental monitoring", "pipeline telemetry"],
 220:     "eMBB": ["4k video", "ar/vr", "live broadcast", "fixed wireless access",
 221:              "stadium hotspot"],
 222: }
 223:
 224:
 225: @dataclass
 226: class Intent:
 227:     latency_ms: float = np.nan
 228:     throughput_mbps: float = np.nan

--- around line 226 ---
 223:
 224:
 225: @dataclass
 226: class Intent:
 227:     latency_ms: float = np.nan
 228:     throughput_mbps: float = np.nan
 229:     reliability_pct: float = np.nan
 230:     density_per_km2: float = np.nan
 231:     mobility_kmh: float = np.nan
 232:     lex_embb: float = 0.0
 233:     lex_urllc: float = 0.0
 234:     lex_mmtc: float = 0.0

--- around line 232 ---
 229:     reliability_pct: float = np.nan
 230:     density_per_km2: float = np.nan
 231:     mobility_kmh: float = np.nan
 232:     lex_embb: float = 0.0
 233:     lex_urllc: float = 0.0
 234:     lex_mmtc: float = 0.0
 235:
 236:
 237: def parse_slots(text: str) -> Intent:
 238:     """Slot-filling only (no lexical prior). Shared by every Intent Agent variant."""
 239:     it = Intent()
 240:     for slot, pats in PATTERNS.items():

--- around line 233 ---
 230:     density_per_km2: float = np.nan
 231:     mobility_kmh: float = np.nan
 232:     lex_embb: float = 0.0
 233:     lex_urllc: float = 0.0
 234:     lex_mmtc: float = 0.0
 235:
 236:
 237: def parse_slots(text: str) -> Intent:
 238:     """Slot-filling only (no lexical prior). Shared by every Intent Agent variant."""
 239:     it = Intent()
 240:     for slot, pats in PATTERNS.items():
 241:         for p in pats:

--- around line 234 ---
 231:     mobility_kmh: float = np.nan
 232:     lex_embb: float = 0.0
 233:     lex_urllc: float = 0.0
 234:     lex_mmtc: float = 0.0
 235:
 236:
 237: def parse_slots(text: str) -> Intent:

In [9]:
import pandas as pd

CORPUS = E5_RESULTS / "corpus.csv"

df = pd.read_csv(CORPUS)

print("Shape:", df.shape)

print("\nColumns:")
for c in df.columns:
    print(" -", c)

print("\nFirst 10 rows:")
display(df.head(10))

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isna().sum())

print("\nUnique values:")
for c in df.columns:
    n = df[c].nunique(dropna=False)
    print(f"{c:30s} {n}")

Shape: (1200, 12)

Columns:
 - id
 - text
 - use_case
 - uc_kind
 - template
 - slice
 - ambiguous
 - lat_true
 - thr_true
 - rel_true
 - den_true
 - mob_true

First 10 rows:

,id,text,use_case,uc_kind,template,slice,ambiguous,lat_true,thr_true,rel_true,den_true,mob_true
0,0,Deploy a slice for 4K video streaming with lat...,4K video streaming,known,0,eMBB,0,52.989940,207.914598,99.467589,104.050742,NaN
1,1,I need surgical imaging feedback support: end-...,surgical imaging feedback,unseen,1,URLLC,1,15.964225,2.317143,98.036694,10936.791205,58.578475
2,2,Provision connectivity for utility submetering...,utility submetering fleet,unseen,2,mMTC,1,289.132834,NaN,96.969313,34142.171111,23.197114
3,3,Can you set up research testbed service? We re...,research testbed service,generic,3,eMBB,1,8.742612,33.809501,99.728676,NaN,NaN
4,4,Set up rail interlocking signalling. It should...,rail interlocking signalling,unseen,5,URLLC,0,NaN,3.653148,NaN,383.692634,NaN
5,5,Set up smart city service. It should sustain 1...,smart city service,generic,5,mMTC,0,NaN,1.065388,NaN,13077.211525,NaN
6,6,Deploy a slice for live broadcast with latency...,live broadcast,known,0,eMBB,1,40.539048,188.393835,99.607400,1772.991401,NaN
7,7,I need substation differential tripping suppor...,substation differential tripping,unseen,1,URLLC,1,48.446071,0.050321,97.209191,98201.589545,369.121191
8,8,Create a network slice supporting pipeline tel...,pipeline telemetry,known,4,mMTC,1,NaN,0.489137,99.312803,1604.726171,15.342483
9,9,Set up AR/VR gaming. It should sustain 54 Mbps...,AR/VR gaming,known,5,eMBB,0,NaN,54.262630,NaN,12180.333328,NaN

Data types:
id             int64
text          object
use_case      object
uc_kind       object
template       int64
slice         object
ambiguous      int64
lat_true     float64
thr_true     float64
rel_true     float64
den_true     float64
mob_true     float64
dtype: object

Missing values:
id             0
text           0
use_case       0
uc_kind        0
template       0
slice          0
ambiguous      0
lat_true     354
thr_true     325
rel_true     151
den_true     342
mob_true     646
dtype: int64

Unique values:
id                             1200
text                           1200
use_case                       35
uc_kind                        3
template                       7
slice                          3
ambiguous                      2
lat_true                       847
thr_true                       876
rel_true                       1050
den_true                       859
mob_true                       555

In [10]:
for c in df.columns:
    if df[c].dtype == "object":
        print("\n", "=" * 90)
        print(c)
        print("=" * 90)
        print(df[c].value_counts(dropna=False).head(30))

 ==========================================================================================
text
==========================================================================================
text
Can you set up surgical imaging feedback? We require no more than 88 ms one-way latency, a minimum of 1.0 Mbps and 98.4343% service availability.                                                      1
Set up campus connectivity. It should sustain 42 Mbps for roughly 713 devices per km2.                                                                                                                 1
Can you set up soil-moisture reporting nodes? We require no more than 9,349 ms one-way latency, a minimum of 0.235 Mbps and 97.5956% service availability.                                             1
Create a network slice supporting public safety communications with 5.4 Mbps guaranteed bitrate, 99.9964 percent reliability, 2,148 terminals per km2 and 186 km/h mobility.                           1
Set up AR/VR gaming. It should sustain 92 Mbps for roughly 393 devices per km2.                                                                                                                        1
I need street luminaire telemetry support: end-to-end delay must stay below 273 ms, sustained rate 1.1 Mbps, availability 96.8148%, device density around 118,066 per km2, mobility up to 8.9 km/h.    1
Please onboard remote surgery with a 2.2 ms delay bound and 99.9933% availability.                                                                                                                     1
Provision connectivity for campus connectivity. Target budget: 12 ms latency, 99.0288% reliability, 9,890 devices/km2, users moving at 202 km/h.                                                       1
Deploy a slice for pipeline telemetry with latency under 143 ms, at least 0.004 Mbps throughput and 97.4475% reliability for about 11,238 devices per square km.                                       1
Deploy a slice for substation differential tripping with latency under 3.7 ms, at least 1.6 Mbps throughput and 99.9956% reliability for about 872 devices per square km.                              1
Provision connectivity for research testbed service. Target budget: 64 ms latency, 99.236% reliability, 494 devices/km2, users moving at 196 km/h.                                                     1
Please onboard smart water meters with a 1,352 ms delay bound and 95.2178% availability.                                                                                                               1
Please onboard haptic teleoperation with a 3.2 ms delay bound and 99.9944% availability.                                                                                                               1
Can you set up fixed wireless access? We require no more than 11 ms one-way latency, a minimum of 372 Mbps and 99.2232% service availability.                                                          1
Set up campus connectivity. It should sustain 0.145 Mbps for roughly 216,557 devices per km2.                                                                                                          1
I need drone fleet control support: end-to-end delay must stay below 6.9 ms, sustained rate 0.649 Mbps, availability 99.9933%, device density around 549 per km2, mobility up to 328 km/h.             1
Create a network slice supporting research testbed service with 22 Mbps guaranteed bitrate, 99.9998 percent reliability, 107 terminals per km2 and 12 km/h mobility.                                   1
Create a network slice supporting stadium hotspot with 106 Mbps guaranteed bitrate, 99.8878 percent reliability, 16,463 terminals per km2 and 85 km/h mobility.                                        1
Provision connectivity for campus connectivity. Target budget: 107 ms latency, 96.2924% reliability, 48,745 devices/km2, users moving at 14 km/h.                                                      1
Set up remote surgery. It should sustain 21 Mbps for roughly 4,190 devices per km2.                                                                                                                    1
Create a network slice supporting research testbed service with 0.040 Mbps guaranteed bitrate, 96.434 percent reliability, 98,237 terminals per km2 and 142 km/h mobility.                             1
Deploy a slice for municipal network service with latency under 75 ms, at least 0.004 Mbps throughput and 96.0463% reliability for about 169,977 devices per square km.                                1
I need campus connectivity support: end-to-end delay must stay below 3.9 ms, sustained rate 54 Mbps, availability 99.9995%, device density around 8,578 per km2, mobility up to 246 km/h.              1
Can you set up high-definition conferencing? We require no more than 48 ms one-way latency, a minimum of 646 Mbps and 99.1343% service availability.                                                   1
Can you set up soil-moisture reporting nodes? We require no more than 4,843 ms one-way latency, a minimum of 0.046 Mbps and 98.5869% service availability.                                             1
Set up drone fleet control. It should sustain 21 Mbps for roughly 153 devices per km2.                                                                                                                 1
Please onboard enterprise application with a 621 ms delay bound and 99.6445% availability.                                                                                                             1
I need asset trackers support: end-to-end delay must stay below 4,067 ms, sustained rate 0.001 Mbps, availability 97.8268%, device density around 44,302 per km2, mobility up to 13 km/h.              1
Deploy a slice for port crane synchronisation with latency under 6.2 ms, at least 0.545 Mbps throughput and 99.9976% reliability for about 500 devices per square km.                                  1
Provision connectivity for public safety communications. Target budget: 21 ms latency, 99.4749% reliability, 6,311 devices/km2, users moving at 115 km/h.                                              1
Name: count, dtype: int64

 ==========================================================================================
use_case
==========================================================================================
use_case
municipal network service           58
enterprise application              49
research testbed service            48
campus connectivity                 47
smart city service                  45
public safety communications        43
remote surgery                      43
substation differential tripping    40
high-definition conferencing        38
smart-grid protection               38
event coverage service              38
pipeline telemetry                  37
haptic teleoperation                36
utility submetering fleet           36
retail branch connectivity          35
cold-chain condition reporting      35
live broadcast                      34
4K video streaming                  33
smart water meters                  32
port crane synchronisation          32
environmental monitoring            31
fixed wireless access               29
street luminaire telemetry          29
AR/VR gaming                        29
newsroom contribution feed          29
surgical imaging feedback           28
digital signage uplink              28
rail interlocking signalling        27
agricultural sensors                27
drone fleet control                 26
Name: count, dtype: int64

 ==========================================================================================
uc_kind
==========================================================================================
uc_kind
known      463
unseen     374
generic    363
Name: count, dtype: int64

 ==========================================================================================
slice
==========================================================================================
slice
eMBB     400
URLLC    400
mMTC     400
Name: count, dtype: int64

In [11]:
assert train_phrase_families.isdisjoint(test_phrase_families)

NameError: name 'train_phrase_families' is not defined

In [12]:
from pathlib import Path
import shutil
import json
import hashlib
import datetime

ROOT = Path(
    "/content/xagentic_r1_work/"
    "XAgentic_Final_Paper_Evidence_2026-10-06"
)

FROZEN_SRC = ROOT / "03_SOURCE_CODE"

R1 = Path("/content/revision_experiments/R1_phrase_generalization")

# Fresh R1 only -- frozen evidence remains untouched
if R1.exists():
    shutil.rmtree(R1)

dirs = [
    "notebooks",
    "src",
    "data/original",
    "data/phrase_family_heldout",
    "data/generic_kpi",
    "data/kpi_only",
    "splits",
    "results/seed_42",
    "results/seed_43",
    "results/seed_44",
    "results/seed_45",
    "results/seed_46",
    "results/aggregate",
    "figures",
    "audit",
    "manifests",
    "frozen_reference",
]

for d in dirs:
    (R1 / d).mkdir(parents=True, exist_ok=True)

print("R1 workspace created:")
print(R1)

R1 workspace created:
/content/revision_experiments/R1_phrase_generalization

In [13]:
source_hashes = {}

for p in sorted(FROZEN_SRC.glob("*.py")):
    sha = hashlib.sha256(p.read_bytes()).hexdigest()
    source_hashes[p.name] = sha

manifest = {
    "experiment": "R1_phrase_generalization",
    "purpose": (
        "Reviewer-driven robustness evaluation for lexical leakage, "
        "phrase-family generalization, generic+KPI and KPI-only conditions."
    ),
    "frozen_evidence": "XAgentic_Final_Paper_Evidence_2026-10-06",
    "original_source_modified": False,
    "seeds": [42, 43, 44, 45, 46],
    "conditions": [
        "L1_original",
        "L2_phrase_family_heldout",
        "L3_generic_kpi",
        "L4_kpi_only"
    ],
    "source_sha256": source_hashes,
    "created_utc": datetime.datetime.now(
        datetime.timezone.utc
    ).isoformat()
}

out = R1 / "frozen_reference/source_manifest.json"
out.write_text(json.dumps(manifest, indent=2))

print(out.read_text())

{
  "experiment": "R1_phrase_generalization",
  "purpose": "Reviewer-driven robustness evaluation for lexical leakage, phrase-family generalization, generic+KPI and KPI-only conditions.",
  "frozen_evidence": "XAgentic_Final_Paper_Evidence_2026-10-06",
  "original_source_modified": false,
  "seeds": [
    42,
    43,
    44,
    45,
    46
  ],
  "conditions": [
    "L1_original",
    "L2_phrase_family_heldout",
    "L3_generic_kpi",
    "L4_kpi_only"
  ],
  "source_sha256": {
    "agents.py": "073a9281316ab7be44cbc65e73cf73efdef631400265eb11cee722795039928b",
    "exp1_posthoc.py": "fc5acf7194e877a5656976043ea13c931a3198b65c0a574affad888a10422c4a",
    "exp2_inhoc.py": "34b0bec18e401be6417827a1476e674fa625e10f18f12c806383d27b2a776827",
    "exp3_semantic.py": "7a3366df283101259254c871df9035ed5333a06b80211d4a6d4f47d5bf95f294",
    "exp4_combined.py": "33ce35f3e24530ee6a1c5903a541e429efc70ccc8ab5118fcee1c581bb848597",
    "exp5_agentic.py": "58e9546d264353ad42399ceb219b472454b368227682e7c78c8c5f2d56a00953",
    "run_all.py": "53347bcbed9a1c51e21b0af3d97377238fbdf222c08e8907c580049295b92074",
    "run_seeds.py": "a615e45022b85ee0909bf98ba8e12cda7523e1f2c4d93b65aaa356c92503605a",
    "xagentic_common.py": "1484f474ba7f40b451583115da9fc7c4fdebc79f9c6876d9a0d7447f649cfbb6",
    "xagentic_slice.py": "7bf2f1190a2928f273578425f194fc3272385d4baaa9044bff771d0fd748ae05"
  },
  "created_utc": "2026-10-07T03:51:02.684929+00:00"
}

In [14]:
import pandas as pd

CORPUS = (
    ROOT /
    "02_E5_QWEN37_N100_SEED52" /
    "corpus.csv"
)

df = pd.read_csv(CORPUS)

phrase_counts = (
    df.groupby(["slice", "uc_kind", "use_case"])
      .size()
      .reset_index(name="n")
      .sort_values(["slice", "uc_kind", "use_case"])
)

display(phrase_counts)

print("\nNumber of phrase/use-case groups:", len(phrase_counts))

print("\nBy slice:")
print(
    phrase_counts.groupby("slice")["use_case"]
                 .nunique()
)

print("\nBy kind:")
print(
    phrase_counts.groupby("uc_kind")["use_case"]
                 .nunique()
)

    slice  uc_kind                          use_case   n
0   URLLC  generic               campus connectivity  12
1   URLLC  generic            enterprise application  12
2   URLLC  generic            event coverage service  13
3   URLLC  generic         municipal network service  27
4   URLLC  generic      public safety communications   7
5   URLLC  generic          research testbed service  17
6   URLLC  generic        retail branch connectivity  10
7   URLLC  generic                smart city service  11
8   URLLC    known               drone fleet control  26
9   URLLC    known             factory robot control  21
10  URLLC    known              haptic teleoperation  36
11  URLLC    known                    remote surgery  43
12  URLLC    known             smart-grid protection  38
13  URLLC   unseen        port crane synchronisation  32
14  URLLC   unseen      rail interlocking signalling  27
15  URLLC   unseen  substation differential tripping  40
16  URLLC   unseen         surgical imaging feedback  28
17   eMBB  generic               campus connectivity  20
18   eMBB  generic            enterprise application  18
19   eMBB  generic            event coverage service  13
20   eMBB  generic         municipal network service  15
21   eMBB  generic      public safety communications  21
22   eMBB  generic          research testbed service  18
23   eMBB  generic        retail branch connectivity  11
24   eMBB  generic                smart city service  16
25   eMBB    known                4K video streaming  33
26   eMBB    known                      AR/VR gaming  29
27   eMBB    known             fixed wireless access  29
28   eMBB    known                    live broadcast  34
29   eMBB    known                   stadium hotspot  22
30   eMBB   unseen            digital signage uplink  28
31   eMBB   unseen      high-definition conferencing  38
32   eMBB   unseen    in-flight entertainment uplink  26
33   eMBB   unseen        newsroom contribution feed  29
34   mMTC  generic               campus connectivity  15
35   mMTC  generic            enterprise application  19
36   mMTC  generic            event coverage service  12
37   mMTC  generic         municipal network service  16
38   mMTC  generic      public safety communications  15
39   mMTC  generic          research testbed service  13
40   mMTC  generic        retail branch connectivity  14
41   mMTC  generic                smart city service  18
42   mMTC    known              agricultural sensors  27
43   mMTC    known                    asset trackers  25
44   mMTC    known          environmental monitoring  31
45   mMTC    known                pipeline telemetry  37
46   mMTC    known                smart water meters  32
47   mMTC   unseen    cold-chain condition reporting  35
48   mMTC   unseen     soil-moisture reporting nodes  26
49   mMTC   unseen        street luminaire telemetry  29
50   mMTC   unseen         utility submetering fleet  36

Number of phrase/use-case groups: 51

By slice:
slice
URLLC    17
eMBB     17
mMTC     17
Name: use_case, dtype: int64

By kind:
uc_kind
generic     8
known      15
unseen     12
Name: use_case, dtype: int64

In [15]:
phrase_counts.to_csv(
    R1 / "audit/original_phrase_inventory.csv",
    index=False
)

print("Saved original_phrase_inventory.csv")

Saved original_phrase_inventory.csv

In [16]:
import numpy as np
import pandas as pd
from pathlib import Path

SEEDS = [42, 43, 44, 45, 46]

CLASS_SPECIFIC = df[df["uc_kind"].isin(["known", "unseen"])].copy()
GENERIC = df[df["uc_kind"] == "generic"].copy()

def build_family_split(df, seed, test_fraction=0.30):
    rng = np.random.default_rng(seed)

    train_families = []
    test_families = []

    # Split phrase/use-case families independently within
    # each slice and vocabulary category.
    family_table = (
        df[df["uc_kind"].isin(["known", "unseen"])]
        [["slice", "uc_kind", "use_case"]]
        .drop_duplicates()
    )

    for (slice_name, kind), grp in family_table.groupby(
        ["slice", "uc_kind"]
    ):
        families = sorted(grp["use_case"].tolist())
        families = np.array(families, dtype=object)

        rng.shuffle(families)

        n_test = max(1, int(round(len(families) * test_fraction)))

        test = families[:n_test]
        train = families[n_test:]

        for fam in train:
            train_families.append({
                "slice": slice_name,
                "uc_kind": kind,
                "use_case": fam
            })

        for fam in test:
            test_families.append({
                "slice": slice_name,
                "uc_kind": kind,
                "use_case": fam
            })

    train_families = pd.DataFrame(train_families)
    test_families = pd.DataFrame(test_families)

    return train_families, test_families

In [17]:
all_split_rows = []

for seed in SEEDS:

    train_fam, test_fam = build_family_split(df, seed)

    train_set = set(
        zip(
            train_fam["slice"],
            train_fam["uc_kind"],
            train_fam["use_case"]
        )
    )

    test_set = set(
        zip(
            test_fam["slice"],
            test_fam["uc_kind"],
            test_fam["use_case"]
        )
    )

    overlap = train_set & test_set

    assert len(overlap) == 0, (
        f"LEAKAGE DETECTED seed={seed}: {overlap}"
    )

    train_fam["partition"] = "train"
    test_fam["partition"] = "test"

    manifest_seed = pd.concat(
        [train_fam, test_fam],
        ignore_index=True
    )

    manifest_seed["seed"] = seed

    manifest_seed.to_csv(
        R1 / f"splits/phrase_family_split_seed{seed}.csv",
        index=False
    )

    all_split_rows.append(manifest_seed)

    print(
        f"Seed {seed}: "
        f"train families={len(train_fam)}, "
        f"test families={len(test_fam)}, "
        f"overlap={len(overlap)}"
    )

all_splits = pd.concat(all_split_rows, ignore_index=True)

display(all_splits.head(30))

Seed 42: train families=18, test families=9, overlap=0
Seed 43: train families=18, test families=9, overlap=0
Seed 44: train families=18, test families=9, overlap=0
Seed 45: train families=18, test families=9, overlap=0
Seed 46: train families=18, test families=9, overlap=0

    slice uc_kind                          use_case partition  seed
0   URLLC   known                    remote surgery     train    42
1   URLLC   known             factory robot control     train    42
2   URLLC   known               drone fleet control     train    42
3   URLLC  unseen      rail interlocking signalling     train    42
4   URLLC  unseen  substation differential tripping     train    42
5   URLLC  unseen        port crane synchronisation     train    42
6    eMBB   known                4K video streaming     train    42
7    eMBB   known                      AR/VR gaming     train    42
8    eMBB   known                    live broadcast     train    42
9    eMBB  unseen        newsroom contribution feed     train    42
10   eMBB  unseen            digital signage uplink     train    42
11   eMBB  unseen      high-definition conferencing     train    42
12   mMTC   known                smart water meters     train    42
13   mMTC   known          environmental monitoring     train    42
14   mMTC   known                pipeline telemetry     train    42
15   mMTC  unseen    cold-chain condition reporting     train    42
16   mMTC  unseen        street luminaire telemetry     train    42
17   mMTC  unseen     soil-moisture reporting nodes     train    42
18  URLLC   known             smart-grid protection      test    42
19  URLLC   known              haptic teleoperation      test    42
20  URLLC  unseen         surgical imaging feedback      test    42
21   eMBB   known             fixed wireless access      test    42
22   eMBB   known                   stadium hotspot      test    42
23   eMBB  unseen    in-flight entertainment uplink      test    42
24   mMTC   known              agricultural sensors      test    42
25   mMTC   known                    asset trackers      test    42
26   mMTC  unseen         utility submetering fleet      test    42
27  URLLC   known              haptic teleoperation     train    43
28  URLLC   known               drone fleet control     train    43
29  URLLC   known                    remote surgery     train    43

In [18]:
audit_rows = []

for seed in SEEDS:

    m = pd.read_csv(
        R1 / f"splits/phrase_family_split_seed{seed}.csv"
    )

    tr = m[m["partition"] == "train"]
    te = m[m["partition"] == "test"]

    train_families = set(tr["use_case"])
    test_families = set(te["use_case"])

    overlap = train_families & test_families

    for slice_name in ["eMBB", "URLLC", "mMTC"]:
        for kind in ["known", "unseen"]:

            train_n = len(
                tr[
                    (tr["slice"] == slice_name) &
                    (tr["uc_kind"] == kind)
                ]
            )

            test_n = len(
                te[
                    (te["slice"] == slice_name) &
                    (te["uc_kind"] == kind)
                ]
            )

            audit_rows.append({
                "seed": seed,
                "slice": slice_name,
                "uc_kind": kind,
                "train_families": train_n,
                "test_families": test_n,
                "global_family_overlap": len(overlap)
            })

audit = pd.DataFrame(audit_rows)

display(audit)

audit.to_csv(
    R1 / "audit/phrase_family_leakage_audit.csv",
    index=False
)

assert audit["global_family_overlap"].max() == 0

print("\nR1 L2 PHRASE-FAMILY LEAKAGE AUDIT: PASS")

    seed  slice uc_kind  train_families  test_families  global_family_overlap
0     42   eMBB   known               3              2                      0
1     42   eMBB  unseen               3              1                      0
2     42  URLLC   known               3              2                      0
3     42  URLLC  unseen               3              1                      0
4     42   mMTC   known               3              2                      0
5     42   mMTC  unseen               3              1                      0
6     43   eMBB   known               3              2                      0
7     43   eMBB  unseen               3              1                      0
8     43  URLLC   known               3              2                      0
9     43  URLLC  unseen               3              1                      0
10    43   mMTC   known               3              2                      0
11    43   mMTC  unseen               3              1                      0
12    44   eMBB   known               3              2                      0
13    44   eMBB  unseen               3              1                      0
14    44  URLLC   known               3              2                      0
15    44  URLLC  unseen               3              1                      0
16    44   mMTC   known               3              2                      0
17    44   mMTC  unseen               3              1                      0
18    45   eMBB   known               3              2                      0
19    45   eMBB  unseen               3              1                      0
20    45  URLLC   known               3              2                      0
21    45  URLLC  unseen               3              1                      0
22    45   mMTC   known               3              2                      0
23    45   mMTC  unseen               3              1                      0
24    46   eMBB   known               3              2                      0
25    46   eMBB  unseen               3              1                      0
26    46  URLLC   known               3              2                      0
27    46  URLLC  unseen               3              1                      0
28    46   mMTC   known               3              2                      0
29    46   mMTC  unseen               3              1                      0

R1 L2 PHRASE-FAMILY LEAKAGE AUDIT: PASS

In [19]:
import pandas as pd
import numpy as np
import re
from pathlib import Path

# ============================================================
# R1 DATASET CONSTRUCTION
# ============================================================

R1 = Path("/content/revision_experiments/R1_phrase_generalization")

df = pd.read_csv(
    ROOT / "02_E5_QWEN37_N100_SEED52" / "corpus.csv"
).copy()

KPI_COLS = [
    "lat_true",
    "thr_true",
    "rel_true",
    "den_true",
    "mob_true",
]

# ------------------------------------------------------------
# Helper: replace the use-case phrase with neutral wording.
#
# Important:
# We preserve the ORIGINAL sentence/template and KPI wording.
# Only the use-case lexical cue is removed.
# ------------------------------------------------------------

NEUTRAL_PHRASE = "network service"

def make_generic_kpi_text(row):
    text = str(row["text"])
    uc = str(row["use_case"])

    # Exact replacement because synth_corpus inserted use_case literally.
    new_text, n = re.subn(
        re.escape(uc),
        NEUTRAL_PHRASE,
        text,
        count=1,
        flags=re.IGNORECASE,
    )

    if n != 1:
        raise ValueError(
            f"Could not replace use_case for id={row['id']}: "
            f"{uc!r} in {text!r}"
        )

    return new_text


# ------------------------------------------------------------
# KPI-only text.
#
# Use only KPIs that were actually present in the original
# template/text. Do NOT reveal hidden latent KPI values.
#
# We therefore derive KPI-only wording from the observable
# natural-language declaration rather than dumping all *_true
# columns into the text.
# ------------------------------------------------------------

def extract_observable_kpi_fragments(text):

    fragments = []

    patterns = [
        # latency
        (
            "latency",
            r"(?i)(?:latency|delay)[^.;,]*?"
            r"([0-9][0-9,]*\.?[0-9]*)\s*ms"
        ),

        # reversed latency expression, e.g. "2.2 ms delay"
        (
            "latency_rev",
            r"(?i)([0-9][0-9,]*\.?[0-9]*)\s*ms"
            r"[^.;,]*?(?:latency|delay)"
        ),

        # throughput / rate
        (
            "throughput",
            r"(?i)([0-9][0-9,]*\.?[0-9]*)\s*Mbps"
        ),

        # reliability / availability
        (
            "reliability",
            r"(?i)([0-9][0-9,]*\.?[0-9]*)\s*"
            r"(?:%|percent)[^.;,]*?"
            r"(?:reliability|availability)"
        ),

        # reversed reliability wording
        (
            "reliability_rev",
            r"(?i)(?:reliability|availability)[^.;,]*?"
            r"([0-9][0-9,]*\.?[0-9]*)\s*(?:%|percent)"
        ),

        # density
        (
            "density",
            r"(?i)([0-9][0-9,]*\.?[0-9]*)\s*"
            r"(?:devices|terminals)[^.;,]*?(?:km2|km²|square km)"
        ),

        # mobility
        (
            "mobility",
            r"(?i)([0-9][0-9,]*\.?[0-9]*)\s*km/h"
        ),
    ]

    found = {}

    for name, pattern in patterns:
        m = re.search(pattern, text)

        if m:
            base_name = (
                "latency" if name.startswith("latency")
                else "reliability" if name.startswith("reliability")
                else name
            )

            if base_name not in found:
                found[base_name] = m.group(1)

    if "latency" in found:
        fragments.append(
            f"latency requirement {found['latency']} ms"
        )

    if "throughput" in found:
        fragments.append(
            f"throughput requirement {found['throughput']} Mbps"
        )

    if "reliability" in found:
        fragments.append(
            f"reliability requirement {found['reliability']} percent"
        )

    if "density" in found:
        fragments.append(
            f"device density requirement {found['density']} devices per km2"
        )

    if "mobility" in found:
        fragments.append(
            f"mobility requirement {found['mobility']} km/h"
        )

    return fragments


def make_kpi_only_text(row):

    fragments = extract_observable_kpi_fragments(str(row["text"]))

    if not fragments:
        raise ValueError(
            f"No observable KPI extracted for id={row['id']}: "
            f"{row['text']}"
        )

    return "; ".join(fragments) + "."


# ============================================================
# Construct common L1/L3/L4 master data
# ============================================================

master = df.copy()

master["text_L1_original"] = master["text"]

master["text_L3_generic_kpi"] = master.apply(
    make_generic_kpi_text,
    axis=1
)

master["text_L4_kpi_only"] = master.apply(
    make_kpi_only_text,
    axis=1
)

master.to_csv(
    R1 / "data/r1_master_conditions.csv",
    index=False
)

print("R1 master conditions created:", master.shape)

display(
    master[
        [
            "id",
            "slice",
            "uc_kind",
            "ambiguous",
            "text_L1_original",
            "text_L3_generic_kpi",
            "text_L4_kpi_only",
        ]
    ].head(10)
)

R1 master conditions created: (1200, 15)

,id,slice,uc_kind,ambiguous,text_L1_original,text_L3_generic_kpi,text_L4_kpi_only
0,0,eMBB,known,0,Deploy a slice for 4K video streaming with lat...,Deploy a slice for network service with latenc...,latency requirement 53 ms; throughput requirem...
1,1,URLLC,unseen,1,I need surgical imaging feedback support: end-...,I need network service support: end-to-end del...,latency requirement 16 ms; throughput requirem...
2,2,mMTC,unseen,1,Provision connectivity for utility submetering...,Provision connectivity for network service. Ta...,latency requirement 289 ms; reliability requir...
3,3,eMBB,generic,1,Can you set up research testbed service? We re...,Can you set up network service? We require no ...,latency requirement 8.7 ms; throughput require...
4,4,URLLC,unseen,0,Set up rail interlocking signalling. It should...,Set up network service. It should sustain 3.7 ...,throughput requirement 3.7 Mbps; device densit...
5,5,mMTC,generic,0,Set up smart city service. It should sustain 1...,Set up network service. It should sustain 1.1 ...,throughput requirement 1.1 Mbps; device densit...
6,6,eMBB,known,1,Deploy a slice for live broadcast with latency...,Deploy a slice for network service with latenc...,latency requirement 41 ms; throughput requirem...
7,7,URLLC,unseen,1,I need substation differential tripping suppor...,I need network service support: end-to-end del...,latency requirement 48 ms; throughput requirem...
8,8,mMTC,known,1,Create a network slice supporting pipeline tel...,Create a network slice supporting network serv...,throughput requirement 0.489 Mbps; reliability...
9,9,eMBB,known,0,Set up AR/VR gaming. It should sustain 54 Mbps...,Set up network service. It should sustain 54 M...,throughput requirement 54 Mbps; device density...

In [20]:
# ============================================================
# R1 DATASET SANITY AUDIT
# ============================================================

audit = []

for _, row in master.iterrows():

    original = str(row["text_L1_original"])
    generic  = str(row["text_L3_generic_kpi"])
    kpi_only = str(row["text_L4_kpi_only"])

    uc = str(row["use_case"])

    audit.append({
        "id": row["id"],
        "slice": row["slice"],
        "uc_kind": row["uc_kind"],
        "ambiguous": row["ambiguous"],

        # L3 must remove original phrase
        "l3_original_phrase_removed":
            uc.lower() not in generic.lower(),

        # L3 must contain neutral phrase
        "l3_has_neutral_phrase":
            NEUTRAL_PHRASE.lower() in generic.lower(),

        # L4 must contain no original phrase
        "l4_original_phrase_removed":
            uc.lower() not in kpi_only.lower(),

        # L4 must contain at least one KPI
        "l4_has_kpi":
            any(
                x in kpi_only.lower()
                for x in [
                    "latency requirement",
                    "throughput requirement",
                    "reliability requirement",
                    "device density requirement",
                    "mobility requirement",
                ]
            ),

        "l1_length": len(original),
        "l3_length": len(generic),
        "l4_length": len(kpi_only),
    })

audit = pd.DataFrame(audit)

display(audit.head())

print("\n=== FAILURES ===")

for col in [
    "l3_original_phrase_removed",
    "l3_has_neutral_phrase",
    "l4_original_phrase_removed",
    "l4_has_kpi",
]:
    failures = (~audit[col]).sum()
    print(f"{col:32s}: {failures}")

audit.to_csv(
    R1 / "audit/r1_condition_sanity.csv",
    index=False
)

assert audit["l3_original_phrase_removed"].all()
assert audit["l3_has_neutral_phrase"].all()
assert audit["l4_original_phrase_removed"].all()
assert audit["l4_has_kpi"].all()

print("\nR1 CONDITION SANITY AUDIT: PASS")

,id,slice,uc_kind,ambiguous,l3_original_phrase_removed,l3_has_neutral_phrase,l4_original_phrase_removed,l4_has_kpi,l1_length,l3_length,l4_length
0,0,eMBB,known,0,True,True,True,True,154,151,148
1,1,URLLC,unseen,1,True,True,True,True,191,181,130
2,2,mMTC,unseen,1,True,True,True,True,151,141,149
3,3,eMBB,generic,1,True,True,True,True,144,135,100
4,4,URLLC,unseen,0,True,True,True,True,96,83,80

=== FAILURES ===
l3_original_phrase_removed      : 0
l3_has_neutral_phrase           : 0
l4_original_phrase_removed      : 0
l4_has_kpi                      : 0

R1 CONDITION SANITY AUDIT: PASS

In [21]:
# Number of observable KPIs retained in L4

KPI_TERMS = {
    "latency": "latency requirement",
    "throughput": "throughput requirement",
    "reliability": "reliability requirement",
    "density": "device density requirement",
    "mobility": "mobility requirement",
}

rows = []

for _, row in master.iterrows():

    txt = row["text_L4_kpi_only"].lower()

    present = {
        k: int(v in txt)
        for k, v in KPI_TERMS.items()
    }

    rows.append({
        "id": row["id"],
        "template": row["template"],
        "slice": row["slice"],
        "uc_kind": row["uc_kind"],
        "ambiguous": row["ambiguous"],
        **present,
        "n_observable_kpis": sum(present.values())
    })

coverage = pd.DataFrame(rows)

print("Observable KPI count distribution:")
print(
    coverage["n_observable_kpis"]
    .value_counts()
    .sort_index()
)

print("\nBy template:")
display(
    coverage.groupby("template")[
        [
            "latency",
            "throughput",
            "reliability",
            "density",
            "mobility",
            "n_observable_kpis",
        ]
    ].mean().round(3)
)

coverage.to_csv(
    R1 / "audit/l4_observable_kpi_coverage.csv",
    index=False
)

Observable KPI count distribution:
n_observable_kpis
2    309
3    184
4    707
Name: count, dtype: int64

By template:

,latency,throughput,reliability,density,mobility,n_observable_kpis
template,,,,,,
0,1.0,1.0,1.0,1.0,0.0,4.0
1,1.0,1.0,1.0,0.0,1.0,4.0
2,1.0,0.0,1.0,1.0,1.0,4.0
3,1.0,1.0,1.0,0.0,0.0,3.0
4,0.0,1.0,1.0,1.0,1.0,4.0
5,0.0,1.0,0.0,1.0,0.0,2.0
6,1.0,0.0,1.0,0.0,0.0,2.0

In [22]:
# Number of observable KPIs retained in L4

KPI_TERMS = {
    "latency": "latency requirement",
    "throughput": "throughput requirement",
    "reliability": "reliability requirement",
    "density": "device density requirement",
    "mobility": "mobility requirement",
}

rows = []

for _, row in master.iterrows():

    txt = row["text_L4_kpi_only"].lower()

    present = {
        k: int(v in txt)
        for k, v in KPI_TERMS.items()
    }

    rows.append({
        "id": row["id"],
        "template": row["template"],
        "slice": row["slice"],
        "uc_kind": row["uc_kind"],
        "ambiguous": row["ambiguous"],
        **present,
        "n_observable_kpis": sum(present.values())
    })

coverage = pd.DataFrame(rows)

print("Observable KPI count distribution:")
print(
    coverage["n_observable_kpis"]
    .value_counts()
    .sort_index()
)

print("\nBy template:")
display(
    coverage.groupby("template")[
        [
            "latency",
            "throughput",
            "reliability",
            "density",
            "mobility",
            "n_observable_kpis",
        ]
    ].mean().round(3)
)

coverage.to_csv(
    R1 / "audit/l4_observable_kpi_coverage.csv",
    index=False
)

Observable KPI count distribution:
n_observable_kpis
2    309
3    184
4    707
Name: count, dtype: int64

By template:

,latency,throughput,reliability,density,mobility,n_observable_kpis
template,,,,,,
0,1.0,1.0,1.0,1.0,0.0,4.0
1,1.0,1.0,1.0,0.0,1.0,4.0
2,1.0,0.0,1.0,1.0,1.0,4.0
3,1.0,1.0,1.0,0.0,0.0,3.0
4,0.0,1.0,1.0,1.0,1.0,4.0
5,0.0,1.0,0.0,1.0,0.0,2.0
6,1.0,0.0,1.0,0.0,0.0,2.0

In [23]:
from sklearn.model_selection import train_test_split
import pandas as pd
import json

SEEDS = [42, 43, 44, 45, 46]

split_summary = []

for seed in SEEDS:

    # ========================================================
    # L1/L3/L4 common row split
    # ========================================================

    train_idx, test_idx = train_test_split(
        master.index,
        test_size=0.20,
        random_state=seed,
        stratify=master["slice"]
    )

    common_split = pd.DataFrame({
        "id": master.loc[
            list(train_idx) + list(test_idx), "id"
        ].values,

        "partition":
            ["train"] * len(train_idx) +
            ["test"] * len(test_idx)
    })

    common_split.to_csv(
        R1 / f"splits/common_row_split_seed{seed}.csv",
        index=False
    )

    # ========================================================
    # L2 phrase-family split
    # ========================================================

    fam = pd.read_csv(
        R1 / f"splits/phrase_family_split_seed{seed}.csv"
    )

    train_families = set(
        fam.loc[
            fam["partition"] == "train",
            "use_case"
        ]
    )

    test_families = set(
        fam.loc[
            fam["partition"] == "test",
            "use_case"
        ]
    )

    # L2 deliberately excludes generic cases.
    l2_pool = master[
        master["uc_kind"].isin(["known", "unseen"])
    ].copy()

    l2_train = l2_pool[
        l2_pool["use_case"].isin(train_families)
    ].copy()

    l2_test = l2_pool[
        l2_pool["use_case"].isin(test_families)
    ].copy()

    # Critical leakage assertion
    actual_train_families = set(l2_train["use_case"])
    actual_test_families = set(l2_test["use_case"])

    overlap = actual_train_families & actual_test_families

    assert not overlap, (
        f"L2 leakage seed={seed}: {overlap}"
    )

    l2_split = pd.concat([
        l2_train[["id"]].assign(partition="train"),
        l2_test[["id"]].assign(partition="test")
    ])

    l2_split.to_csv(
        R1 / f"splits/L2_row_split_seed{seed}.csv",
        index=False
    )

    # ========================================================
    # Summary
    # ========================================================

    for condition, tr, te in [

        (
            "L1_original",
            master.loc[train_idx],
            master.loc[test_idx]
        ),

        (
            "L3_generic_kpi",
            master.loc[train_idx],
            master.loc[test_idx]
        ),

        (
            "L4_kpi_only",
            master.loc[train_idx],
            master.loc[test_idx]
        ),

        (
            "L2_phrase_family_heldout",
            l2_train,
            l2_test
        ),
    ]:

        split_summary.append({
            "seed": seed,
            "condition": condition,
            "train_n": len(tr),
            "test_n": len(te),

            "train_eMBB":
                int((tr["slice"] == "eMBB").sum()),
            "train_URLLC":
                int((tr["slice"] == "URLLC").sum()),
            "train_mMTC":
                int((tr["slice"] == "mMTC").sum()),

            "test_eMBB":
                int((te["slice"] == "eMBB").sum()),
            "test_URLLC":
                int((te["slice"] == "URLLC").sum()),
            "test_mMTC":
                int((te["slice"] == "mMTC").sum()),

            "test_ambiguous_0":
                int((te["ambiguous"] == 0).sum()),
            "test_ambiguous_1":
                int((te["ambiguous"] == 1).sum()),
        })


split_summary = pd.DataFrame(split_summary)

split_summary.to_csv(
    R1 / "audit/r1_split_summary.csv",
    index=False
)

display(split_summary)

print("\nR1 FINAL SPLITS: CREATED")

,seed,condition,train_n,test_n,train_eMBB,train_URLLC,train_mMTC,test_eMBB,test_URLLC,test_mMTC,test_ambiguous_0,test_ambiguous_1
0,42,L1_original,960,240,320,320,320,80,80,80,172,68
1,42,L3_generic_kpi,960,240,320,320,320,80,80,80,172,68
2,42,L4_kpi_only,960,240,320,320,320,80,80,80,172,68
3,42,L2_phrase_family_heldout,570,267,191,189,190,77,102,88,188,79
4,43,L1_original,960,240,320,320,320,80,80,80,170,70
5,43,L3_generic_kpi,960,240,320,320,320,80,80,80,170,70
6,43,L4_kpi_only,960,240,320,320,320,80,80,80,170,70
7,43,L2_phrase_family_heldout,568,269,180,192,196,88,99,82,188,81
8,44,L1_original,960,240,320,320,320,80,80,80,164,76
9,44,L3_generic_kpi,960,240,320,320,320,80,80,80,164,76
10,44,L4_kpi_only,960,240,320,320,320,80,80,80,164,76
11,44,L2_phrase_family_heldout,529,308,163,180,186,105,111,92,229,79
12,45,L1_original,960,240,320,320,320,80,80,80,161,79
13,45,L3_generic_kpi,960,240,320,320,320,80,80,80,161,79
14,45,L4_kpi_only,960,240,320,320,320,80,80,80,161,79
15,45,L2_phrase_family_heldout,573,264,188,201,184,80,90,94,183,81
16,46,L1_original,960,240,320,320,320,80,80,80,172,68
17,46,L3_generic_kpi,960,240,320,320,320,80,80,80,172,68
18,46,L4_kpi_only,960,240,320,320,320,80,80,80,172,68
19,46,L2_phrase_family_heldout,569,268,181,204,184,87,87,94,177,91

R1 FINAL SPLITS: CREATED

In [24]:
print("=" * 80)
print("R1 SPLIT INTEGRITY AUDIT")
print("=" * 80)

for seed in SEEDS:

    print(f"\nSEED {seed}")

    # --------------------------------------------------------
    # Common L1/L3/L4 split
    # --------------------------------------------------------

    common = pd.read_csv(
        R1 / f"splits/common_row_split_seed{seed}.csv"
    )

    train_ids = set(
        common.loc[
            common["partition"] == "train", "id"
        ]
    )

    test_ids = set(
        common.loc[
            common["partition"] == "test", "id"
        ]
    )

    assert train_ids.isdisjoint(test_ids)

    assert len(train_ids) + len(test_ids) == len(master)

    print(
        f"  L1/L3/L4: "
        f"train={len(train_ids)}, "
        f"test={len(test_ids)}, "
        f"ID overlap=0"
    )

    # --------------------------------------------------------
    # L2
    # --------------------------------------------------------

    l2 = pd.read_csv(
        R1 / f"splits/L2_row_split_seed{seed}.csv"
    )

    l2_train_ids = set(
        l2.loc[
            l2["partition"] == "train", "id"
        ]
    )

    l2_test_ids = set(
        l2.loc[
            l2["partition"] == "test", "id"
        ]
    )

    assert l2_train_ids.isdisjoint(l2_test_ids)

    tr = master[
        master["id"].isin(l2_train_ids)
    ]

    te = master[
        master["id"].isin(l2_test_ids)
    ]

    tr_families = set(tr["use_case"])
    te_families = set(te["use_case"])

    family_overlap = tr_families & te_families

    assert not family_overlap

    assert not (tr["uc_kind"] == "generic").any()
    assert not (te["uc_kind"] == "generic").any()

    print(
        f"  L2: "
        f"train={len(tr)}, "
        f"test={len(te)}, "
        f"phrase-family overlap={len(family_overlap)}"
    )

print("\nR1 SPLIT INTEGRITY AUDIT: PASS")

================================================================================
R1 SPLIT INTEGRITY AUDIT
================================================================================

SEED 42
  L1/L3/L4: train=960, test=240, ID overlap=0
  L2: train=570, test=267, phrase-family overlap=0

SEED 43
  L1/L3/L4: train=960, test=240, ID overlap=0
  L2: train=568, test=269, phrase-family overlap=0

SEED 44
  L1/L3/L4: train=960, test=240, ID overlap=0
  L2: train=529, test=308, phrase-family overlap=0

SEED 45
  L1/L3/L4: train=960, test=240, ID overlap=0
  L2: train=573, test=264, phrase-family overlap=0

SEED 46
  L1/L3/L4: train=960, test=240, ID overlap=0
  L2: train=569, test=268, phrase-family overlap=0

R1 SPLIT INTEGRITY AUDIT: PASS

In [25]:
import sys
import importlib

sys.path.insert(0, str(FROZEN_SRC))

import xagentic_common
importlib.reload(xagentic_common)

print("Loaded frozen xagentic_common:")
print(xagentic_common.__file__)

Loaded frozen xagentic_common:
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/03_SOURCE_CODE/xagentic_common.py

In [26]:
import inspect

for name, obj in inspect.getmembers(xagentic_common):

    if inspect.isfunction(obj):

        if any(
            term in name.lower()
            for term in [
                "intent",
                "feature",
                "parse",
                "vector",
                "slot"
            ]
        ):
            print(name, inspect.signature(obj))

build_features (df: 'pd.DataFrame', lex_fn=None)
parse_intent (text: 'str') -> 'Intent'
parse_slots (text: 'str') -> 'Intent'
score_slots (df: 'pd.DataFrame')

In [27]:
import inspect
import xagentic_common as xc

print("=" * 100)
print("build_features SOURCE")
print("=" * 100)
print(inspect.getsource(xc.build_features))

print("\n" + "=" * 100)
print("parse_intent SOURCE")
print("=" * 100)
print(inspect.getsource(xc.parse_intent))

====================================================================================================
build_features SOURCE
====================================================================================================
def build_features(df: pd.DataFrame, lex_fn=None):
    """Assemble the 14-dim feature matrix.

    `lex_fn(text) -> (embb, urllc, mmtc)` supplies the lexical prior. Passing a
    different `lex_fn` is exactly how Experiment 3 swaps the Intent Agent while
    holding every other pipeline stage fixed.
    """
    if lex_fn is None:
        lex_fn = lexicon_scores

    recs = []
    for _, r in df.iterrows():
        it = parse_slots(r["text"])
        it.lex_embb, it.lex_urllc, it.lex_mmtc = lex_fn(r["text"])
        recs.append(asdict(it))

    X = pd.DataFrame(recs)
    for slot in SLOT_MAP:
        X["miss_" + slot.split("_")[0]] = (~np.isfinite(X[slot].astype(float))).astype(int)
    X["log_latency"] = np.log10(X["latency_ms"].astype(float).clip(lower=1e-3))
    X["log_throughput"] = np.log10(X["throughput_mbps"].astype(float).clip(lower=1e-4))
    X["log_density"] = np.log10(X["density_per_km2"].astype(float).clip(lower=1.0))
    X = X[FEATURES].astype(float)
    # NOTE: missing slots are deliberately left as NaN here. Imputation is a
    # *fitted* step and is performed inside split() using training-split medians
    # only, so no test-split statistic can leak into the feature matrix.
    return X


====================================================================================================
parse_intent SOURCE
====================================================================================================
def parse_intent(text: str) -> Intent:
    """Full E1 Intent Agent: slot filling + binary lexicon prior."""
    it = parse_slots(text)
    it.lex_embb, it.lex_urllc, it.lex_mmtc = lexicon_scores(text)
    return it

In [28]:
sample = master.head(5).copy()

for condition, text_col in [
    ("L1", "text_L1_original"),
    ("L3", "text_L3_generic_kpi"),
    ("L4", "text_L4_kpi_only"),
]:
    temp = sample.copy()
    temp["text"] = temp[text_col]

    X, y, meta = xc.build_features(temp)

    print("\n", "=" * 80)
    print(condition)
    print("=" * 80)

    print("X type :", type(X))
    print("X shape:", getattr(X, "shape", None))
    print("y type :", type(y))
    print("y shape:", getattr(y, "shape", None))
    print("meta type:", type(meta))

    if hasattr(X, "columns"):
        print("Feature columns:")
        print(list(X.columns))

ValueError: too many values to unpack (expected 3)

In [29]:
sample = master.head(5).copy()

for condition, text_col in [
    ("L1", "text_L1_original"),
    ("L3", "text_L3_generic_kpi"),
    ("L4", "text_L4_kpi_only"),
]:
    temp = sample.copy()
    temp["text"] = temp[text_col]

    X = xc.build_features(temp)

    print("\n" + "=" * 80)
    print(condition)
    print("=" * 80)

    print("X type :", type(X))
    print("X shape:", X.shape)

    print("\nFeature columns:")
    print(list(X.columns))

    print("\nFirst 5 rows:")
    display(X)

================================================================================
L1
================================================================================
X type : <class 'pandas.core.frame.DataFrame'>
X shape: (5, 14)

Feature columns:
['latency_ms', 'throughput_mbps', 'reliability_pct', 'density_per_km2', 'mobility_kmh', 'log_latency', 'log_throughput', 'log_density', 'miss_latency', 'miss_throughput', 'miss_density', 'lex_embb', 'lex_urllc', 'lex_mmtc']

First 5 rows:

,latency_ms,throughput_mbps,reliability_pct,density_per_km2,mobility_kmh,log_latency,log_throughput,log_density,miss_latency,miss_throughput,miss_density,lex_embb,lex_urllc,lex_mmtc
0,53.0,208.0,99.4676,104.0,NaN,1.724276,2.318063,2.017033,0.0,0.0,0.0,1.0,0.0,0.0
1,16.0,2.3,98.0367,NaN,59.0,1.204120,0.361728,NaN,0.0,0.0,1.0,0.0,0.0,0.0
2,289.0,NaN,96.9693,34142.0,23.0,2.460898,NaN,4.533289,0.0,1.0,0.0,0.0,0.0,0.0
3,8.7,34.0,99.7287,NaN,NaN,0.939519,1.531479,NaN,0.0,0.0,1.0,0.0,0.0,0.0
4,NaN,3.7,NaN,384.0,NaN,NaN,0.568202,2.584331,1.0,0.0,0.0,0.0,0.0,0.0

================================================================================
L3
================================================================================
X type : <class 'pandas.core.frame.DataFrame'>
X shape: (5, 14)

Feature columns:
['latency_ms', 'throughput_mbps', 'reliability_pct', 'density_per_km2', 'mobility_kmh', 'log_latency', 'log_throughput', 'log_density', 'miss_latency', 'miss_throughput', 'miss_density', 'lex_embb', 'lex_urllc', 'lex_mmtc']

First 5 rows:

,latency_ms,throughput_mbps,reliability_pct,density_per_km2,mobility_kmh,log_latency,log_throughput,log_density,miss_latency,miss_throughput,miss_density,lex_embb,lex_urllc,lex_mmtc
0,53.0,208.0,99.4676,104.0,NaN,1.724276,2.318063,2.017033,0.0,0.0,0.0,0.0,0.0,0.0
1,16.0,2.3,98.0367,NaN,59.0,1.204120,0.361728,NaN,0.0,0.0,1.0,0.0,0.0,0.0
2,289.0,NaN,96.9693,34142.0,23.0,2.460898,NaN,4.533289,0.0,1.0,0.0,0.0,0.0,0.0
3,8.7,34.0,99.7287,NaN,NaN,0.939519,1.531479,NaN,0.0,0.0,1.0,0.0,0.0,0.0
4,NaN,3.7,NaN,384.0,NaN,NaN,0.568202,2.584331,1.0,0.0,0.0,0.0,0.0,0.0

================================================================================
L4
================================================================================
X type : <class 'pandas.core.frame.DataFrame'>
X shape: (5, 14)

Feature columns:
['latency_ms', 'throughput_mbps', 'reliability_pct', 'density_per_km2', 'mobility_kmh', 'log_latency', 'log_throughput', 'log_density', 'miss_latency', 'miss_throughput', 'miss_density', 'lex_embb', 'lex_urllc', 'lex_mmtc']

First 5 rows:

,latency_ms,throughput_mbps,reliability_pct,density_per_km2,mobility_kmh,log_latency,log_throughput,log_density,miss_latency,miss_throughput,miss_density,lex_embb,lex_urllc,lex_mmtc
0,53.0,208.0,99.4676,104.0,NaN,1.724276,2.318063,2.017033,0.0,0.0,0.0,0.0,0.0,0.0
1,16.0,2.3,98.0367,NaN,59.0,1.204120,0.361728,NaN,0.0,0.0,1.0,0.0,0.0,0.0
2,289.0,NaN,96.9693,34142.0,23.0,2.460898,NaN,4.533289,0.0,1.0,0.0,0.0,0.0,0.0
3,8.7,34.0,99.7287,NaN,NaN,0.939519,1.531479,NaN,0.0,0.0,1.0,0.0,0.0,0.0
4,NaN,3.7,NaN,384.0,NaN,NaN,0.568202,2.584331,1.0,0.0,0.0,0.0,0.0,0.0

In [30]:
feature_sets = {}

for condition, text_col in [
    ("L1", "text_L1_original"),
    ("L3", "text_L3_generic_kpi"),
    ("L4", "text_L4_kpi_only"),
]:
    temp = master.copy()
    temp["text"] = temp[text_col]

    X = xc.build_features(temp)

    feature_sets[condition] = X

    print("\n" + "=" * 80)
    print(condition)
    print("=" * 80)

    print("Shape:", X.shape)

    for col in [
        "lex_embb",
        "lex_urllc",
        "lex_mmtc"
    ]:
        print(
            f"{col:15s} "
            f"nonzero={int((X[col] != 0).sum()):4d} "
            f"sum={X[col].sum():.0f}"
        )

================================================================================
L1
================================================================================
Shape: (1200, 14)
lex_embb        nonzero= 147 sum=147
lex_urllc       nonzero= 164 sum=164
lex_mmtc        nonzero= 152 sum=152

================================================================================
L3
================================================================================
Shape: (1200, 14)
lex_embb        nonzero=   0 sum=0
lex_urllc       nonzero=   0 sum=0
lex_mmtc        nonzero=   0 sum=0

================================================================================
L4
================================================================================
Shape: (1200, 14)
lex_embb        nonzero=   0 sum=0
lex_urllc       nonzero=   0 sum=0
lex_mmtc        nonzero=   0 sum=0

In [31]:
from dataclasses import asdict, is_dataclass

def intent_to_dict(obj):
    if is_dataclass(obj):
        return asdict(obj)

    if hasattr(obj, "__dict__"):
        return vars(obj)

    raise TypeError(
        f"Cannot convert parsed Intent type: {type(obj)}"
    )


records = []

for _, row in master.iterrows():

    parsed = {}

    for condition, col in [
        ("L1", "text_L1_original"),
        ("L3", "text_L3_generic_kpi"),
        ("L4", "text_L4_kpi_only"),
    ]:
        obj = xc.parse_intent(str(row[col]))
        parsed[condition] = intent_to_dict(obj)

    records.append({
        "id": row["id"],
        "slice": row["slice"],
        "template": row["template"],
        "uc_kind": row["uc_kind"],
        "ambiguous": row["ambiguous"],
        "L1": parsed["L1"],
        "L3": parsed["L3"],
        "L4": parsed["L4"],
    })


print("Parsed records:", len(records))

print("\nExample L1:")
print(records[0]["L1"])

print("\nExample L3:")
print(records[0]["L3"])

print("\nExample L4:")
print(records[0]["L4"])

Parsed records: 1200

Example L1:
{'latency_ms': 53.0, 'throughput_mbps': 208.0, 'reliability_pct': 99.4676, 'density_per_km2': 104.0, 'mobility_kmh': nan, 'lex_embb': 1.0, 'lex_urllc': 0.0, 'lex_mmtc': 0.0}

Example L3:
{'latency_ms': 53.0, 'throughput_mbps': 208.0, 'reliability_pct': 99.4676, 'density_per_km2': 104.0, 'mobility_kmh': nan, 'lex_embb': 0.0, 'lex_urllc': 0.0, 'lex_mmtc': 0.0}

Example L4:
{'latency_ms': 53.0, 'throughput_mbps': 208.0, 'reliability_pct': 99.4676, 'density_per_km2': 104.0, 'mobility_kmh': nan, 'lex_embb': 0.0, 'lex_urllc': 0.0, 'lex_mmtc': 0.0}

In [32]:
import numpy as np
import pandas as pd

X1 = feature_sets["L1"].reset_index(drop=True)
X3 = feature_sets["L3"].reset_index(drop=True)
X4 = feature_sets["L4"].reset_index(drop=True)

NON_LEXICAL = [
    "latency_ms",
    "throughput_mbps",
    "reliability_pct",
    "density_per_km2",
    "mobility_kmh",
    "log_latency",
    "log_throughput",
    "log_density",
    "miss_latency",
    "miss_throughput",
    "miss_density",
]

LEXICAL = [
    "lex_embb",
    "lex_urllc",
    "lex_mmtc",
]

rows = []

for col in NON_LEXICAL:

    same_13 = np.allclose(
        X1[col].to_numpy(),
        X3[col].to_numpy(),
        equal_nan=True
    )

    same_14 = np.allclose(
        X1[col].to_numpy(),
        X4[col].to_numpy(),
        equal_nan=True
    )

    rows.append({
        "feature": col,
        "L1_equals_L3": same_13,
        "L1_equals_L4": same_14
    })

equiv = pd.DataFrame(rows)

display(equiv)

assert equiv["L1_equals_L3"].all()
assert equiv["L1_equals_L4"].all()

for col in LEXICAL:
    assert (X3[col] == 0).all()
    assert (X4[col] == 0).all()

print("\nR1 FEATURE-PRESERVATION AUDIT: PASS")
print("All non-lexical features are identical across L1/L3/L4.")
print("All lexical-prior features are zero in L3/L4.")

equiv.to_csv(
    R1 / "audit/r1_feature_preservation.csv",
    index=False
)

            feature  L1_equals_L3  L1_equals_L4
0        latency_ms          True          True
1   throughput_mbps          True          True
2   reliability_pct          True          True
3   density_per_km2          True          True
4      mobility_kmh          True          True
5       log_latency          True          True
6    log_throughput          True          True
7       log_density          True          True
8      miss_latency          True          True
9   miss_throughput          True          True
10     miss_density          True          True

R1 FEATURE-PRESERVATION AUDIT: PASS
All non-lexical features are identical across L1/L3/L4.
All lexical-prior features are zero in L3/L4.

In [33]:
import inspect
import exp1_posthoc as e1
import xagentic_common as xc

print("=" * 100)
print("FUNCTIONS IN exp1_posthoc")
print("=" * 100)

for name, obj in inspect.getmembers(e1):
    if inspect.isfunction(obj):
        print(name, inspect.signature(obj))

print("\n" + "=" * 100)
print("RELEVANT FUNCTIONS IN xagentic_common")
print("=" * 100)

for name, obj in inspect.getmembers(xc):
    if inspect.isfunction(obj):
        if any(k in name.lower() for k in [
            "split",
            "model",
            "train",
            "imput",
            "scale",
            "classifier",
            "evaluate"
        ]):
            print(name, inspect.signature(obj))

====================================================================================================
FUNCTIONS IN exp1_posthoc
====================================================================================================
ablation_fidelity (predict_fn, Xte, attributions, median, k_list=(1, 2, 3), seed=42)
accuracy_score (y_true, y_pred, *, normalize=True, sample_weight=None)
build_features (df: 'pd.DataFrame', lex_fn=None)
build_models ()
clone (estimator, *, safe=True)
confusion_matrix (y_true, y_pred, *, labels=None, sample_weight=None, normalize=None)
contract_valid (pred_label, row)
cross_val_predict (estimator, X, y=None, *, groups=None, cv=None, n_jobs=None, verbose=0, params=None, pre_dispatch='2*n_jobs', method='predict')
cross_val_score (estimator, X, y=None, *, groups=None, scoring=None, cv=None, n_jobs=None, verbose=0, params=None, pre_dispatch='2*n_jobs', error_score=nan)
escalation_signal_ablation (proba, ypred, yte, Xte, attr, tau)
escalation_table (proba, ypred, yte, Xte, taus=(0.5, 0.6, 0.7, 0.8, 0.9))
f1_score (y_true, y_pred, *, labels=None, pos_label=1, average='binary', sample_weight=None, zero_division='warn')
precision_recall_fscore_support (y_true, y_pred, *, beta=1.0, labels=None, pos_label=1, average=None, warn_for=('precision', 'recall', 'f-score'), sample_weight=None, zero_division='warn')
rule_based (row)
rule_based_lex (row)
run (df=None, verbose=True)
save_csv (df, name)
save_json (obj, name)
score_slots (df: 'pd.DataFrame')
select_tau (tbl, min_autonomous_acc=0.98)
split (X, y, df)
subgroup_report (ypred, yte, dte)
synth_corpus (n=3000, p_amb=0.3, seed=42)

====================================================================================================
RELEVANT FUNCTIONS IN xagentic_common
====================================================================================================
split (X, y, df)

In [34]:
print("=" * 100)
print("exp1_posthoc.py")
print("=" * 100)

src = inspect.getsource(e1)

for i, line in enumerate(src.splitlines(), 1):
    if any(k in line.lower() for k in [
        "cross_val",
        "stratified",
        "gradient",
        "randomforest",
        "random_forest",
        "logistic",
        "classifier",
        "model",
        "imputer",
        "simpleimputer",
        "standardscaler",
        "macro",
        "f1",
        "random_state",
    ]):
        print(f"{i:4d}: {line}")

====================================================================================================
exp1_posthoc.py
====================================================================================================
  13:     e1_models.csv, e1_per_class.csv, e1_confusion.csv, e1_escalation.csv,
  26: from sklearn.model_selection import (
  27:     StratifiedKFold, cross_val_score, cross_val_predict,
  29: from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
  30: from sklearn.tree import DecisionTreeClassifier
  31: from sklearn.linear_model import LogisticRegression
  32: from sklearn.neural_network import MLPClassifier
  34: from sklearn.preprocessing import StandardScaler
  36:     accuracy_score, f1_score, precision_recall_fscore_support, confusion_matrix,
  48: def build_models():
  50:         "Logistic Regression": Pipeline([
  51:             ("sc", StandardScaler()),
  52:             ("m", LogisticRegression(max_iter=2000, random_state=SEED))]),
  53:         "Decision Tree": DecisionTreeClassifier(max_depth=8, random_state=SEED),
  55:             ("sc", StandardScaler()),
  56:             ("m", MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=1200,
  57:                                 random_state=SEED))]),
  58:         "Gradient Boosting": GradientBoostingClassifier(random_state=SEED),
  59:         "Random Forest": RandomForestClassifier(n_estimators=300, random_state=SEED,
  85:     # ---- S4: Selection Agent model sweep -----------------------------------
  91:         model="Rule-based playbook", acc=accuracy_score(yte, rb),
  92:         f1=f1_score(yte, rb, average="macro"), cv_mean=np.nan, cv_std=np.nan,
  97:     # M9: lexicon-augmented playbook -- same 14-dim input as the learned models,
 103:         model="Rule-based + lexicon", acc=accuracy_score(yte, rbl),
 104:         f1=f1_score(yte, rbl, average="macro"), cv_mean=np.nan, cv_std=np.nan,
 109:     skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
 111:     for name, m in build_models().items():
 113:         cv = cross_val_score(m, Xtr, ytr, cv=skf, scoring="f1_macro", n_jobs=1)
 120:             model=name, acc=accuracy_score(yte, p),
 121:             f1=f1_score(yte, p, average="macro"),
 128:     save_csv(res, "e1_models.csv")
 131:     # Model selection uses ONLY the cross-validated score computed on the
 134:         "cv_mean", ascending=False).iloc[0]["model"]
 137:     infer_lat_ms = float(res.loc[res["model"] == best_name, "lat_ms"].iloc[0])
 138:     print(f"[S4] best = {best_name} (selected on 5-fold CV macro F1, train split)")
 141:     # cross_val_predict gives every training intent a prediction from a model
 143:     oof_proba = cross_val_predict(clone(best), Xtr, ytr, cv=skf,
 152:     pr, rc, f1c, sup = precision_recall_fscore_support(yte, ypred, labels=[0, 1, 2])
 153:     save_csv(dict(slice=SLICES, precision=pr, recall=rc, f1=f1c, support=sup),
 162:     bg = shap.sample(Xtr, 100, random_state=SEED)
 220:         experiment="E1", label="Post-hoc (SHAP)", model=best_name,
 221:         model_selection="5-fold CV macro F1 on train split",
 226:         macro_f1=float(f1_score(yte, ypred, average="macro")),
 234:         baseline_rule_f1=float(f1_score(yte, rb, average="macro")),
 236:         baseline_rulelex_f1=float(f1_score(yte, rbl, average="macro")),
 256:     print(f"[E1] accuracy {rep['acc_overall']:.4f} | macro F1 {rep['macro_f1']:.4f} "

In [35]:
print("=" * 100)
print("split() SOURCE")
print("=" * 100)

if hasattr(xc, "split"):
    print(inspect.getsource(xc.split))
else:
    print("No split() function found.")

====================================================================================================
split() SOURCE
====================================================================================================
def split(X, y, df):
    """Stratified 70/30 split, then median-impute using TRAIN statistics only.

    build_features() returns raw NaNs for unstated slots; the median is fitted
    here on the training split and applied to both splits, so the held-out data
    contributes nothing to the imputation statistics.
    """
    from sklearn.model_selection import train_test_split
    Xtr, Xte, ytr, yte, dtr, dte = train_test_split(
        X, y, df, test_size=TEST_SIZE, random_state=SEED, stratify=y)
    med = Xtr.median(numeric_only=True)
    return Xtr.fillna(med), Xte.fillna(med), ytr, yte, dtr, dte

In [36]:
# ============================================================
# R1 L2 FINAL PRE-TRAINING AUDIT
# ============================================================

import pandas as pd

l2_audit_rows = []

for seed in SEEDS:

    split_file = R1 / f"splits/L2_row_split_seed{seed}.csv"
    sp = pd.read_csv(split_file)

    train_ids = set(
        sp.loc[sp["partition"] == "train", "id"]
    )

    test_ids = set(
        sp.loc[sp["partition"] == "test", "id"]
    )

    train_df = master[
        master["id"].isin(train_ids)
    ].copy()

    test_df = master[
        master["id"].isin(test_ids)
    ].copy()

    # --------------------------------------------------------
    # Hard assertions
    # --------------------------------------------------------

    assert train_ids.isdisjoint(test_ids)

    train_families = set(train_df["use_case"])
    test_families = set(test_df["use_case"])

    overlap = train_families & test_families

    assert len(overlap) == 0

    # L2 is specifically class-specific phrase generalization
    assert set(train_df["uc_kind"].unique()) <= {
        "known", "unseen"
    }

    assert set(test_df["uc_kind"].unique()) <= {
        "known", "unseen"
    }

    # Build frozen E1 features from ORIGINAL TEXT
    l2_train_input = train_df.copy()
    l2_test_input = test_df.copy()

    l2_train_input["text"] = \
        l2_train_input["text_L1_original"]

    l2_test_input["text"] = \
        l2_test_input["text_L1_original"]

    X_train = xc.build_features(l2_train_input)
    X_test = xc.build_features(l2_test_input)

    assert X_train.shape[1] == 14
    assert X_test.shape[1] == 14

    # --------------------------------------------------------
    # Record statistics
    # --------------------------------------------------------

    l2_audit_rows.append({

        "seed": seed,

        "train_n": len(train_df),
        "test_n": len(test_df),

        "train_families":
            train_df["use_case"].nunique(),

        "test_families":
            test_df["use_case"].nunique(),

        "family_overlap":
            len(overlap),

        "train_eMBB":
            int((train_df["slice"] == "eMBB").sum()),

        "train_URLLC":
            int((train_df["slice"] == "URLLC").sum()),

        "train_mMTC":
            int((train_df["slice"] == "mMTC").sum()),

        "test_eMBB":
            int((test_df["slice"] == "eMBB").sum()),

        "test_URLLC":
            int((test_df["slice"] == "URLLC").sum()),

        "test_mMTC":
            int((test_df["slice"] == "mMTC").sum()),

        "test_nonambiguous":
            int((test_df["ambiguous"] == 0).sum()),

        "test_ambiguous":
            int((test_df["ambiguous"] == 1).sum()),

        "train_lexical_hits":
            int(
                X_train[
                    ["lex_embb",
                     "lex_urllc",
                     "lex_mmtc"]
                ].sum().sum()
            ),

        "test_lexical_hits":
            int(
                X_test[
                    ["lex_embb",
                     "lex_urllc",
                     "lex_mmtc"]
                ].sum().sum()
            ),
    })


l2_audit = pd.DataFrame(l2_audit_rows)

display(l2_audit)

l2_audit.to_csv(
    R1 / "audit/L2_final_pretraining_audit.csv",
    index=False
)

assert (l2_audit["family_overlap"] == 0).all()

print()
print("=" * 80)
print("R1 L2 FINAL PRE-TRAINING AUDIT: PASS")
print("=" * 80)

,seed,train_n,test_n,train_families,test_families,family_overlap,train_eMBB,train_URLLC,train_mMTC,test_eMBB,test_URLLC,test_mMTC,test_nonambiguous,test_ambiguous,train_lexical_hits,test_lexical_hits
0,42,570,267,18,9,0,191,189,190,77,102,88,188,79,286,177
1,43,568,269,18,9,0,180,192,196,88,99,82,188,81,286,177
2,44,529,308,18,9,0,163,180,186,105,111,92,229,79,260,203
3,45,573,264,18,9,0,188,201,184,80,90,94,183,81,282,181
4,46,569,268,18,9,0,181,204,184,87,87,94,177,91,290,173

================================================================================
R1 L2 FINAL PRE-TRAINING AUDIT: PASS
================================================================================

In [37]:
from sklearn.model_selection import train_test_split
import pandas as pd

SEEDS = [42, 43, 44, 45, 46]

for seed in SEEDS:

    train_idx, test_idx = train_test_split(
        master.index,
        test_size=0.30,          # MATCH FROZEN E1
        random_state=seed,
        stratify=master["slice"]
    )

    common_split = pd.DataFrame({
        "id": master.loc[
            list(train_idx) + list(test_idx), "id"
        ].values,
        "partition":
            ["train"] * len(train_idx) +
            ["test"] * len(test_idx)
    })

    common_split.to_csv(
        R1 / f"splits/common_row_split_seed{seed}.csv",
        index=False
    )

    assert len(train_idx) == 840
    assert len(test_idx) == 360

print("L1/L3/L4 common splits rebuilt using frozen E1 70/30 protocol.")

L1/L3/L4 common splits rebuilt using frozen E1 70/30 protocol.

In [38]:
for seed in SEEDS:

    sp = pd.read_csv(
        R1 / f"splits/common_row_split_seed{seed}.csv"
    )

    tr = sp[sp["partition"] == "train"]
    te = sp[sp["partition"] == "test"]

    assert set(tr["id"]).isdisjoint(set(te["id"]))

    print(
        f"Seed {seed}: "
        f"train={len(tr)}, test={len(te)}"
    )

print("\n70/30 SPLIT AUDIT: PASS")

Seed 42: train=840, test=360
Seed 43: train=840, test=360
Seed 44: train=840, test=360
Seed 45: train=840, test=360
Seed 46: train=840, test=360

70/30 SPLIT AUDIT: PASS

In [39]:
import numpy as np
import pandas as pd

from sklearn.base import clone
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_recall_fscore_support,
    confusion_matrix,
)

import exp1_posthoc as e1
import xagentic_common as xc


SLICES = ["eMBB", "URLLC", "mMTC"]
SEEDS = [42, 43, 44, 45, 46]


def encode_labels(series):
    mapping = {
        "eMBB": 0,
        "URLLC": 1,
        "mMTC": 2,
    }

    y = series.map(mapping)

    if y.isna().any():
        raise ValueError("Unknown slice label encountered.")

    return y.astype(int).to_numpy()


def median_impute_train_only(Xtr, Xte):
    """
    Match frozen E1:
    median is learned from TRAIN only.
    """
    med = Xtr.median(numeric_only=True)

    return (
        Xtr.fillna(med),
        Xte.fillna(med),
        med
    )

In [40]:
def select_model_train_only(Xtr, ytr, seed):

    # Important:
    # exp1_posthoc.build_models() uses module-level SEED.
    # Set it explicitly for each R1 run.
    e1.SEED = seed

    models = e1.build_models()

    skf = StratifiedKFold(
        n_splits=5,
        shuffle=True,
        random_state=seed
    )

    rows = []

    for name, model in models.items():

        cv = cross_val_score(
            model,
            Xtr,
            ytr,
            cv=skf,
            scoring="f1_macro",
            n_jobs=1
        )

        rows.append({
            "model": name,
            "cv_mean": float(np.mean(cv)),
            "cv_std": float(np.std(cv)),
        })

    table = (
        pd.DataFrame(rows)
        .sort_values(
            ["cv_mean", "model"],
            ascending=[False, True]
        )
        .reset_index(drop=True)
    )

    best_name = table.iloc[0]["model"]

    best_model = clone(models[best_name])

    return best_name, best_model, table

In [41]:
def load_r1_condition(seed, condition):

    if condition in {
        "L1_original",
        "L3_generic_kpi",
        "L4_kpi_only",
    }:

        sp = pd.read_csv(
            R1 / f"splits/common_row_split_seed{seed}.csv"
        )

    elif condition == "L2_phrase_family_heldout":

        sp = pd.read_csv(
            R1 / f"splits/L2_row_split_seed{seed}.csv"
        )

    else:
        raise ValueError(
            f"Unknown condition: {condition}"
        )

    train_ids = set(
        sp.loc[
            sp["partition"] == "train",
            "id"
        ]
    )

    test_ids = set(
        sp.loc[
            sp["partition"] == "test",
            "id"
        ]
    )

    assert train_ids.isdisjoint(test_ids)

    train_df = (
        master[
            master["id"].isin(train_ids)
        ]
        .copy()
        .sort_values("id")
        .reset_index(drop=True)
    )

    test_df = (
        master[
            master["id"].isin(test_ids)
        ]
        .copy()
        .sort_values("id")
        .reset_index(drop=True)
    )

    text_column = {
        "L1_original":
            "text_L1_original",

        "L2_phrase_family_heldout":
            "text_L1_original",

        "L3_generic_kpi":
            "text_L3_generic_kpi",

        "L4_kpi_only":
            "text_L4_kpi_only",
    }[condition]

    train_df["text"] = train_df[text_column]
    test_df["text"] = test_df[text_column]

    # ------------------------------------------
    # Special L2 leakage assertion
    # ------------------------------------------

    if condition == "L2_phrase_family_heldout":

        train_families = set(
            train_df["use_case"]
        )

        test_families = set(
            test_df["use_case"]
        )

        overlap = (
            train_families &
            test_families
        )

        assert len(overlap) == 0, (
            f"L2 FAMILY LEAKAGE: {overlap}"
        )

    return train_df, test_df

In [42]:
def run_one_r1(seed, condition):

    train_df, test_df = load_r1_condition(
        seed,
        condition
    )

    # ------------------------------------------
    # Frozen feature builder
    # ------------------------------------------

    Xtr_raw = xc.build_features(train_df)
    Xte_raw = xc.build_features(test_df)

    assert list(Xtr_raw.columns) == list(Xte_raw.columns)
    assert Xtr_raw.shape[1] == 14

    ytr = encode_labels(train_df["slice"])
    yte = encode_labels(test_df["slice"])

    # ------------------------------------------
    # TRAIN-only imputation
    # ------------------------------------------

    Xtr, Xte, medians = (
        median_impute_train_only(
            Xtr_raw,
            Xte_raw
        )
    )

    assert not Xtr.isna().any().any()
    assert not Xte.isna().any().any()

    # ------------------------------------------
    # Training-only CV model selection
    # ------------------------------------------

    best_name, model, cv_table = (
        select_model_train_only(
            Xtr,
            ytr,
            seed
        )
    )

    # ------------------------------------------
    # Final fit
    # ------------------------------------------

    model.fit(Xtr, ytr)

    pred = model.predict(Xte)

    # ------------------------------------------
    # Main metrics
    # ------------------------------------------

    acc = accuracy_score(yte, pred)

    macro_f1 = f1_score(
        yte,
        pred,
        average="macro"
    )

    pr, rc, f1c, sup = (
        precision_recall_fscore_support(
            yte,
            pred,
            labels=[0, 1, 2],
            zero_division=0
        )
    )

    cm = confusion_matrix(
        yte,
        pred,
        labels=[0, 1, 2]
    )

    # ------------------------------------------
    # Difficulty / ambiguity strata
    # ------------------------------------------

    test_df = test_df.copy()

    test_df["y_true"] = yte
    test_df["y_pred"] = pred
    test_df["correct"] = (
        test_df["y_true"] ==
        test_df["y_pred"]
    )

    subgroup_rows = []

    for ambiguity in [0, 1]:

        mask = (
            test_df["ambiguous"] ==
            ambiguity
        ).to_numpy()

        if mask.sum() == 0:
            continue

        subgroup_rows.append({
            "ambiguous": ambiguity,
            "n": int(mask.sum()),

            "accuracy":
                float(
                    accuracy_score(
                        yte[mask],
                        pred[mask]
                    )
                ),

            "macro_f1":
                float(
                    f1_score(
                        yte[mask],
                        pred[mask],
                        average="macro",
                        zero_division=0
                    )
                ),
        })

    # ------------------------------------------
    # Summary
    # ------------------------------------------

    summary = {
        "seed": seed,
        "condition": condition,

        "train_n": len(train_df),
        "test_n": len(test_df),

        "selected_model": best_name,

        "selected_cv_mean":
            float(
                cv_table.iloc[0]["cv_mean"]
            ),

        "selected_cv_std":
            float(
                cv_table.iloc[0]["cv_std"]
            ),

        "accuracy": float(acc),
        "macro_f1": float(macro_f1),

        "test_nonambiguous_n":
            int(
                (test_df["ambiguous"] == 0)
                .sum()
            ),

        "test_ambiguous_n":
            int(
                (test_df["ambiguous"] == 1)
                .sum()
            ),
    }

    per_class = pd.DataFrame({
        "slice": SLICES,
        "precision": pr,
        "recall": rc,
        "f1": f1c,
        "support": sup,
    })

    confusion = pd.DataFrame(
        cm,
        index=SLICES,
        columns=SLICES
    )

    subgroup = pd.DataFrame(
        subgroup_rows
    )

    return {
        "summary": summary,
        "cv": cv_table,
        "per_class": per_class,
        "confusion": confusion,
        "subgroup": subgroup,
        "predictions": test_df,
        "medians": medians,
    }

In [43]:
smoke = run_one_r1(
    seed=42,
    condition="L1_original"
)

print(smoke["summary"])

print("\nCV model selection:")
display(smoke["cv"])

print("\nPer class:")
display(smoke["per_class"])

print("\nAmbiguity:")
display(smoke["subgroup"])

print("\nConfusion:")
display(smoke["confusion"])

{'seed': 42, 'condition': 'L1_original', 'train_n': 840, 'test_n': 360, 'selected_model': 'Gradient Boosting', 'selected_cv_mean': 0.9285276349197369, 'selected_cv_std': 0.01811090427824921, 'accuracy': 0.9416666666666667, 'macro_f1': 0.9416797893121998, 'test_nonambiguous_n': 262, 'test_ambiguous_n': 98}

CV model selection:

                 model   cv_mean    cv_std
0    Gradient Boosting  0.928528  0.018111
1        Decision Tree  0.914486  0.015510
2        Random Forest  0.911759  0.018645
3  Logistic Regression  0.904408  0.021986
4          MLP (64,32)  0.904290  0.017231

Per class:

   slice  precision    recall        f1  support
0   eMBB   0.919355  0.950000  0.934426      120
1  URLLC   0.940171  0.916667  0.928270      120
2   mMTC   0.966387  0.958333  0.962343      120

Ambiguity:

   ambiguous    n  accuracy  macro_f1
0          0  262  0.988550  0.988540
1          1   98  0.816327  0.810789

Confusion:

       eMBB  URLLC  mMTC
eMBB    114      4     2
URLLC     8    110     2
mMTC      2      3   115

In [44]:
from pathlib import Path
import pandas as pd
import hashlib
import json

FINAL_DATA = R1 / "data/final_3000"
FINAL_DATA.mkdir(parents=True, exist_ok=True)

SEEDS = [42, 43, 44, 45, 46]

generation_rows = []

for seed in SEEDS:

    df = xc.synth_corpus(
        n=3000,
        p_amb=0.30,
        seed=seed
    )

    path = FINAL_DATA / f"r1_corpus_seed{seed}.csv"
    df.to_csv(path, index=False)

    sha = hashlib.sha256(
        path.read_bytes()
    ).hexdigest()

    generation_rows.append({
        "seed": seed,
        "n": len(df),
        "eMBB": int((df["slice"] == "eMBB").sum()),
        "URLLC": int((df["slice"] == "URLLC").sum()),
        "mMTC": int((df["slice"] == "mMTC").sum()),
        "ambiguous_0": int((df["ambiguous"] == 0).sum()),
        "ambiguous_1": int((df["ambiguous"] == 1).sum()),
        "known": int((df["uc_kind"] == "known").sum()),
        "unseen": int((df["uc_kind"] == "unseen").sum()),
        "generic": int((df["uc_kind"] == "generic").sum()),
        "sha256": sha
    })

generation_audit = pd.DataFrame(generation_rows)

display(generation_audit)

assert (generation_audit["n"] == 3000).all()
assert (generation_audit["eMBB"] == 1000).all()
assert (generation_audit["URLLC"] == 1000).all()
assert (generation_audit["mMTC"] == 1000).all()

generation_audit.to_csv(
    R1 / "audit/r1_final_corpus_generation.csv",
    index=False
)

print("\nR1 FINAL 3000-CORPUS GENERATION: PASS")

,seed,n,eMBB,URLLC,mMTC,ambiguous_0,ambiguous_1,known,unseen,generic,sha256
0,42,3000,1000,1000,1000,2110,890,1193,864,943,d3c319980785f18264b58581d227ba10c8914ffc2a0564...
1,43,3000,1000,1000,1000,2074,926,1182,896,922,aea3188b867e31b1d699cff6708670f0b02b3bcfd1ad4e...
2,44,3000,1000,1000,1000,2071,929,1218,883,899,80f97b25b60c1f9698324dbbb9f0d0ac4366133a4127bf...
3,45,3000,1000,1000,1000,2022,978,1209,883,908,57eaf2c6ff444a9c6e21f6405efe687aede57ca965e251...
4,46,3000,1000,1000,1000,2060,940,1159,936,905,b30ce95c0c7ed73ee00f1ffa1b30d0c86fef89c9b5c10f...

R1 FINAL 3000-CORPUS GENERATION: PASS

In [45]:
import numpy as np
import pandas as pd

from sklearn.base import clone
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import accuracy_score, f1_score

SEED = 42

# ------------------------------------------------------------
# Freeze module-level seed exactly as original experiment
# ------------------------------------------------------------

xc.SEED = SEED
e1.SEED = SEED

# ------------------------------------------------------------
# Load freshly regenerated authoritative 3000-row corpus
# ------------------------------------------------------------

df42 = pd.read_csv(
    FINAL_DATA / "r1_corpus_seed42.csv"
)

print("Corpus shape:", df42.shape)
print("\nClass counts:")
print(df42["slice"].value_counts())

# ------------------------------------------------------------
# Frozen feature generation
# ------------------------------------------------------------

X = xc.build_features(df42)

label_map = {
    name: idx
    for idx, name in enumerate(xc.SLICES)
}

y = df42["slice"].map(label_map).astype(int).to_numpy()

print("\nFeature shape:", X.shape)
print("Label mapping:", label_map)

# ------------------------------------------------------------
# IMPORTANT:
# use frozen xc.split(), not our custom splitting code
# ------------------------------------------------------------

Xtr, Xte, ytr, yte, dtr, dte = xc.split(
    X,
    y,
    df42
)

print("\nFrozen split:")
print("train =", len(Xtr))
print("test  =", len(Xte))

assert len(Xtr) == 2100
assert len(Xte) == 900

# ------------------------------------------------------------
# Exact frozen E1 training-only CV model selection
# ------------------------------------------------------------

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=SEED
)

models = e1.build_models()

cv_rows = []

for name, model in models.items():

    scores = cross_val_score(
        model,
        Xtr,
        ytr,
        cv=skf,
        scoring="f1_macro",
        n_jobs=1
    )

    cv_rows.append({
        "model": name,
        "cv_mean": float(scores.mean()),
        "cv_std": float(scores.std())
    })

cv42 = (
    pd.DataFrame(cv_rows)
    .sort_values(
        "cv_mean",
        ascending=False
    )
    .reset_index(drop=True)
)

display(cv42)

best_name = cv42.iloc[0]["model"]

print("\nSelected model:", best_name)

# ------------------------------------------------------------
# Fit selected model once on complete training split
# ------------------------------------------------------------

best = clone(models[best_name])
best.fit(Xtr, ytr)

pred = best.predict(Xte)

acc = accuracy_score(yte, pred)
macro_f1 = f1_score(
    yte,
    pred,
    average="macro"
)

print("\n" + "=" * 80)
print("R1 SEED-42 AUTHORITATIVE REPRODUCTION")
print("=" * 80)

print(f"accuracy : {acc:.10f}")
print(f"macro_f1 : {macro_f1:.10f}")
print(f"model    : {best_name}")
print(f"cv_mean  : {cv42.iloc[0]['cv_mean']:.10f}")
print(f"cv_std   : {cv42.iloc[0]['cv_std']:.10f}")

Corpus shape: (3000, 12)

Class counts:
slice
eMBB     1000
URLLC    1000
mMTC     1000
Name: count, dtype: int64

Feature shape: (3000, 14)
Label mapping: {'eMBB': 0, 'URLLC': 1, 'mMTC': 2}

Frozen split:
train = 2100
test  = 900

                 model   cv_mean    cv_std
0    Gradient Boosting  0.934708  0.008039
1        Random Forest  0.924233  0.006614
2          MLP (64,32)  0.918989  0.006190
3  Logistic Regression  0.911833  0.012865
4        Decision Tree  0.910321  0.008895

Selected model: Gradient Boosting

================================================================================
R1 SEED-42 AUTHORITATIVE REPRODUCTION
================================================================================
accuracy : 0.9277777778
macro_f1 : 0.9278323905
model    : Gradient Boosting
cv_mean  : 0.9347078205
cv_std   : 0.0080393126

In [46]:
FROZEN_E1_SEEDS = (
    ROOT /
    "01_E1_E4_5SEED_FINAL" /
    "e1_seeds.csv"
)

frozen_e1 = pd.read_csv(FROZEN_E1_SEEDS)

print("Frozen E1 columns:")
print(list(frozen_e1.columns))

print("\nFrozen E1 seed table:")
display(frozen_e1)

Frozen E1 columns:
['seed', 'acc', 'macro_f1', 'oov_gap', 'acc_ambiguous', 'model', 'tau', 'fid1', 'expl_ms']

Frozen E1 seed table:

,seed,acc,macro_f1,oov_gap,acc_ambiguous,model,tau,fid1,expl_ms
0,42,93.333333,0.933523,9.829627,77.319588,Gradient Boosting,0.9,9.428571,156.178986
1,43,90.277778,0.902639,15.491855,74.561404,Gradient Boosting,0.9,6.181818,163.012416
2,44,92.222222,0.922119,12.391304,77.586207,Gradient Boosting,0.9,15.500000,161.164130
3,45,92.222222,0.922248,11.681096,76.724138,Random Forest,0.8,5.222222,8.861146
4,46,90.277778,0.902753,13.886641,73.228346,Gradient Boosting,0.9,6.444444,161.644517

In [47]:
print("=" * 90)
print("AVAILABLE FROZEN SEED-42 VALUES")
print("=" * 90)

for col in f42.columns:
    print(f"{col:30s}: {f42.iloc[0][col]}")

==========================================================================================
AVAILABLE FROZEN SEED-42 VALUES
==========================================================================================

NameError: name 'f42' is not defined

In [48]:
# ================================================================
# R1 HARD GATE — SEED 42 FROZEN E1 REPRODUCTION
# ================================================================

import numpy as np
import pandas as pd

from sklearn.base import clone
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import accuracy_score, f1_score

SEED = 42

xc.SEED = SEED
e1.SEED = SEED

# ------------------------------------------------
# 1. Load authoritative regenerated corpus
# ------------------------------------------------

df42 = pd.read_csv(
    FINAL_DATA / "r1_corpus_seed42.csv"
)

assert len(df42) == 3000
assert (df42["slice"].value_counts() == 1000).all()

# ------------------------------------------------
# 2. Frozen feature pipeline
# ------------------------------------------------

X = xc.build_features(df42)

label_map = {
    name: idx
    for idx, name in enumerate(xc.SLICES)
}

y = (
    df42["slice"]
    .map(label_map)
    .astype(int)
    .to_numpy()
)

# ------------------------------------------------
# 3. Frozen 70/30 split + train-only imputation
# ------------------------------------------------

Xtr, Xte, ytr, yte, dtr, dte = xc.split(
    X,
    y,
    df42
)

assert len(Xtr) == 2100
assert len(Xte) == 900

# ------------------------------------------------
# 4. Frozen training-only 5-fold CV
# ------------------------------------------------

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=SEED
)

models = e1.build_models()

cv_rows = []

for name, model in models.items():

    scores = cross_val_score(
        model,
        Xtr,
        ytr,
        cv=skf,
        scoring="f1_macro",
        n_jobs=1
    )

    cv_rows.append({
        "model": name,
        "cv_mean": float(scores.mean()),
        "cv_std": float(scores.std())
    })

cv42 = (
    pd.DataFrame(cv_rows)
    .sort_values(
        "cv_mean",
        ascending=False
    )
    .reset_index(drop=True)
)

# ------------------------------------------------
# 5. Select using TRAIN CV only
# ------------------------------------------------

best_name = cv42.iloc[0]["model"]

best = clone(models[best_name])

best.fit(Xtr, ytr)

pred = best.predict(Xte)

reproduced_acc = float(
    accuracy_score(yte, pred)
)

reproduced_f1 = float(
    f1_score(
        yte,
        pred,
        average="macro"
    )
)

# ------------------------------------------------
# 6. Load frozen archived evidence
# ------------------------------------------------

frozen_e1 = pd.read_csv(
    ROOT /
    "01_E1_E4_5SEED_FINAL" /
    "e1_seeds.csv"
)

f42 = (
    frozen_e1[
        frozen_e1["seed"] == 42
    ]
    .iloc[0]
)

# Archived acc is percentage, not fraction.
frozen_acc = float(f42["acc"]) / 100.0
frozen_f1 = float(f42["macro_f1"])
frozen_model = str(f42["model"])

# ------------------------------------------------
# 7. Differences
# ------------------------------------------------

acc_diff = abs(
    reproduced_acc - frozen_acc
)

f1_diff = abs(
    reproduced_f1 - frozen_f1
)

model_match = (
    best_name == frozen_model
)

# ------------------------------------------------
# 8. Display
# ------------------------------------------------

print("=" * 90)
print("TRAINING-ONLY CV MODEL SELECTION")
print("=" * 90)

display(cv42)

print("\n" + "=" * 90)
print("FROZEN E1 vs REPRODUCED E1 — SEED 42")
print("=" * 90)

comparison = pd.DataFrame([
    {
        "metric": "Accuracy",
        "frozen": frozen_acc,
        "reproduced": reproduced_acc,
        "absolute_difference": acc_diff
    },
    {
        "metric": "Macro F1",
        "frozen": frozen_f1,
        "reproduced": reproduced_f1,
        "absolute_difference": f1_diff
    }
])

display(comparison)

print(f"Frozen model     : {frozen_model}")
print(f"Reproduced model : {best_name}")
print(f"Model match      : {model_match}")

print(f"\nFrozen accuracy     : {frozen_acc:.10f}")
print(f"Reproduced accuracy : {reproduced_acc:.10f}")
print(f"Difference          : {acc_diff:.12f}")

print(f"\nFrozen macro F1     : {frozen_f1:.10f}")
print(f"Reproduced macro F1 : {reproduced_f1:.10f}")
print(f"Difference          : {f1_diff:.12f}")

# ------------------------------------------------
# 9. Reproduction decision
# ------------------------------------------------

# Archived CSV values are rounded, therefore use a small tolerance.
ACC_TOL = 1e-6
F1_TOL = 1e-5

pass_acc = acc_diff <= ACC_TOL
pass_f1 = f1_diff <= F1_TOL

print("\n" + "=" * 90)

if model_match and pass_acc and pass_f1:

    print("R1 SEED-42 FROZEN E1 REPRODUCTION: PASS")

else:

    print("R1 SEED-42 FROZEN E1 REPRODUCTION: FAIL")

    print("\nDiagnostics:")
    print(" model_match =", model_match)
    print(" accuracy_ok =", pass_acc)
    print(" macro_f1_ok =", pass_f1)

print("=" * 90)

==========================================================================================
TRAINING-ONLY CV MODEL SELECTION
==========================================================================================

                 model   cv_mean    cv_std
0    Gradient Boosting  0.934708  0.008039
1        Random Forest  0.924233  0.006614
2          MLP (64,32)  0.918989  0.006190
3  Logistic Regression  0.911833  0.012865
4        Decision Tree  0.910321  0.008895

==========================================================================================
FROZEN E1 vs REPRODUCED E1 — SEED 42
==========================================================================================

     metric    frozen  reproduced  absolute_difference
0  Accuracy  0.933333    0.927778             0.005556
1  Macro F1  0.933523    0.927832             0.005691

Frozen model     : Gradient Boosting
Reproduced model : Gradient Boosting
Model match      : True

Frozen accuracy     : 0.9333333333
Reproduced accuracy : 0.9277777778
Difference          : 0.005555555556

Frozen macro F1     : 0.9335232669
Reproduced macro F1 : 0.9278323905
Difference          : 0.005690876334

==========================================================================================
R1 SEED-42 FROZEN E1 REPRODUCTION: FAIL

Diagnostics:
 model_match = True
 accuracy_ok = False
 macro_f1_ok = False
==========================================================================================

In [49]:
import inspect
import hashlib
import numpy as np
import pandas as pd

print("=" * 100)
print("A. MODULE / GLOBAL STATE")
print("=" * 100)

print("xc.SEED =", getattr(xc, "SEED", None))
print("xc.TEST_SIZE =", getattr(xc, "TEST_SIZE", None))

print("e1.SEED =", getattr(e1, "SEED", None))
print("e1.TEST_SIZE =", getattr(e1, "TEST_SIZE", None))

print()
print("xc.split module :", xc.split.__module__)
print("e1.split module :", e1.split.__module__)

print()
print("same split object? :", xc.split is e1.split)

print("\nxc.split globals SEED:",
      xc.split.__globals__.get("SEED"))

print("xc.split globals TEST_SIZE:",
      xc.split.__globals__.get("TEST_SIZE"))

print("\ne1.split globals SEED:",
      e1.split.__globals__.get("SEED"))

print("e1.split globals TEST_SIZE:",
      e1.split.__globals__.get("TEST_SIZE"))


print("\n" + "=" * 100)
print("B. SYNTH_CORPUS GLOBAL STATE")
print("=" * 100)

print("xc.synth_corpus module:",
      xc.synth_corpus.__module__)

print("e1.synth_corpus module:",
      e1.synth_corpus.__module__)

print("same synth object? :",
      xc.synth_corpus is e1.synth_corpus)

print("\nxc synth global SEED:",
      xc.synth_corpus.__globals__.get("SEED"))

print("e1 synth global SEED:",
      e1.synth_corpus.__globals__.get("SEED"))


print("\n" + "=" * 100)
print("C. BUILD_FEATURES GLOBAL STATE")
print("=" * 100)

print("xc.build_features module:",
      xc.build_features.__module__)

print("e1.build_features module:",
      e1.build_features.__module__)

print("same feature object? :",
      xc.build_features is e1.build_features)


print("\n" + "=" * 100)
print("D. EXACT ORIGINAL E1 RUN() CALLS")
print("=" * 100)

run_src = inspect.getsource(e1.run)

for i, line in enumerate(run_src.splitlines(), 1):

    if any(key in line for key in [
        "synth_corpus",
        "build_features",
        "split(",
        "build_models",
        "SEED",
        "y =",
        "y=",
        "SLICES",
    ]):
        print(f"{i:4d}: {line}")


print("\n" + "=" * 100)
print("E. REGENERATED CORPUS CONSISTENCY")
print("=" * 100)

# Generate again directly through the exact function visible to E1.
fresh_e1 = e1.synth_corpus(
    n=3000,
    p_amb=0.30,
    seed=42
)

saved = pd.read_csv(
    FINAL_DATA / "r1_corpus_seed42.csv"
)

print("saved shape :", saved.shape)
print("fresh shape :", fresh_e1.shape)

# Compare columns first.
print("columns identical:",
      list(saved.columns) == list(fresh_e1.columns))

# CSV round-trip can alter float representation slightly,
# so report both exact and tolerant comparisons.
same_nonfloat = True

for col in saved.columns:

    if not pd.api.types.is_numeric_dtype(saved[col]):
        if not saved[col].astype(str).equals(
            fresh_e1[col].astype(str)
        ):
            same_nonfloat = False
            print("NON-NUMERIC DIFFERENCE:", col)

print("non-float columns identical:",
      same_nonfloat)

numeric_cols = [
    c for c in saved.columns
    if pd.api.types.is_numeric_dtype(saved[c])
]

for col in numeric_cols:

    a = pd.to_numeric(saved[col], errors="coerce").to_numpy()
    b = pd.to_numeric(fresh_e1[col], errors="coerce").to_numpy()

    same = np.allclose(
        a,
        b,
        equal_nan=True,
        rtol=1e-12,
        atol=1e-12
    )

    if not same:
        diff = np.nanmax(np.abs(a - b))
        print(
            f"NUMERIC DIFFERENCE: {col:20s} "
            f"max_abs_diff={diff}"
        )

print("\nCorpus semantic comparison complete.")


print("\n" + "=" * 100)
print("F. DIRECT ORIGINAL e1.run() SMOKE")
print("=" * 100)

print("""
DO NOT run e1.run() yet in this cell.
First inspect sections A-E above.

We need to establish whether our manual reconstruction
and the frozen E1 run share the same module/global state.
""")

====================================================================================================
A. MODULE / GLOBAL STATE
====================================================================================================
xc.SEED = 42
xc.TEST_SIZE = 0.3
e1.SEED = 42
e1.TEST_SIZE = None

xc.split module : xagentic_common
e1.split module : xagentic_common

same split object? : True

xc.split globals SEED: 42
xc.split globals TEST_SIZE: 0.3

e1.split globals SEED: 42
e1.split globals TEST_SIZE: 0.3

====================================================================================================
B. SYNTH_CORPUS GLOBAL STATE
====================================================================================================
xc.synth_corpus module: xagentic_common
e1.synth_corpus module: xagentic_common
same synth object? : True

xc synth global SEED: 42
e1 synth global SEED: 42

====================================================================================================
C. BUILD_FEATURES GLOBAL STATE
====================================================================================================
xc.build_features module: xagentic_common
e1.build_features module: xagentic_common
same feature object? : True

====================================================================================================
D. EXACT ORIGINAL E1 RUN() CALLS
====================================================================================================
   9:         df = synth_corpus()
  14:     X = build_features(df)
  15:     y = df["slice"].map(SLICE_ID).values
  20:     Xtr, Xte, ytr, yte, dtr, dte = split(X, y, df)
  30:         valid=float(np.mean([contract_valid(SLICES[p], r)
  42:         valid=float(np.mean([contract_valid(SLICES[p], r)
  46:     skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
  48:     for name, m in build_models().items():
  60:             valid=float(np.mean([contract_valid(SLICES[pi], r)
  90:     save_csv(dict(slice=SLICES, precision=pr, recall=rc, f1=f1c, support=sup),
  99:     bg = shap.sample(Xtr, 100, random_state=SEED)
 108:         explainer = shap.PermutationExplainer(best.predict_proba, bg, seed=SEED)
 169:         fidelity=fid,
 174:         baseline_rulelex_valid=float(np.mean([contract_valid(SLICES[p], r)
 188:         local.append(dict(slice=SLICES[c], intent=dte.iloc[idx]["text"],

====================================================================================================
E. REGENERATED CORPUS CONSISTENCY
====================================================================================================
saved shape : (3000, 12)
fresh shape : (3000, 12)
columns identical: True
non-float columns identical: True

Corpus semantic comparison complete.

====================================================================================================
F. DIRECT ORIGINAL e1.run() SMOKE
====================================================================================================

DO NOT run e1.run() yet in this cell.
First inspect sections A-E above.

We need to establish whether our manual reconstruction
and the frozen E1 run share the same module/global state.

In [50]:
# ================================================================
# STEP 18 — DIRECT ORIGINAL E1.RUN() REPRODUCTION DIAGNOSTIC
# ================================================================

from pathlib import Path
import os
import inspect
import pandas as pd
import numpy as np

DIAG = R1 / "audit/direct_e1_seed42"
DIAG.mkdir(parents=True, exist_ok=True)

print("Diagnostic directory:")
print(DIAG)

# ------------------------------------------------
# Inspect where save_csv/save_json write
# ------------------------------------------------

print("\n" + "=" * 90)
print("SAVE FUNCTION SOURCE")
print("=" * 90)

print(inspect.getsource(e1.save_csv))
print(inspect.getsource(e1.save_json))

# Check relevant output globals
print("\nRelevant e1 globals:")

for name in [
    "OUT",
    "OUT_DIR",
    "RESULTS",
    "RESULTS_DIR",
    "RESULT_DIR",
]:
    if name in e1.__dict__:
        print(name, "=", e1.__dict__[name])

print("\nRelevant xagentic_common globals:")

for name in [
    "OUT",
    "OUT_DIR",
    "RESULTS",
    "RESULTS_DIR",
    "RESULT_DIR",
]:
    if name in xc.__dict__:
        print(name, "=", xc.__dict__[name])

Diagnostic directory:
/content/revision_experiments/R1_phrase_generalization/audit/direct_e1_seed42

==========================================================================================
SAVE FUNCTION SOURCE
==========================================================================================
def save_csv(df, name):
    path = os.path.join(OUT, name)
    pd.DataFrame(df).to_csv(path, index=False)
    print(f"  -> {path}")
    return path

def save_json(obj, name):
    path = os.path.join(OUT, name)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, default=float)
    print(f"  -> {path}")
    return path


Relevant e1 globals:
OUT = /content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/03_SOURCE_CODE/results

Relevant xagentic_common globals:
OUT = /content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/03_SOURCE_CODE/results

In [51]:
# ================================================================
# STEP 19 — SAFE DIRECT ORIGINAL E1.RUN() — SEED 42
# ================================================================

from pathlib import Path
import os
import json
import pandas as pd
import numpy as np

SEED = 42

DIAG = R1 / "audit/direct_e1_seed42"
DIAG.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------
# Preserve original module state
# ------------------------------------------------

original_e1_out = e1.OUT
original_xc_out = xc.OUT

original_e1_seed = e1.SEED
original_xc_seed = xc.SEED

print("Original e1.OUT:")
print(original_e1_out)

print("\nTemporary diagnostic OUT:")
print(DIAG)

# ------------------------------------------------
# Redirect output SAFELY
# ------------------------------------------------

e1.OUT = str(DIAG)
xc.OUT = str(DIAG)

e1.SEED = SEED
xc.SEED = SEED

# Important because imported functions use globals from
# xagentic_common.
xc.split.__globals__["SEED"] = SEED
xc.synth_corpus.__globals__["SEED"] = SEED

try:

    # ------------------------------------------------
    # Generate corpus directly in memory
    # ------------------------------------------------

    fresh42 = e1.synth_corpus(
        n=3000,
        p_amb=0.30,
        seed=SEED
    )

    print("\nFresh corpus:")
    print("shape =", fresh42.shape)

    print(
        fresh42["slice"]
        .value_counts()
        .sort_index()
    )

    # ------------------------------------------------
    # Run EXACT original E1 implementation
    # ------------------------------------------------

    print("\n" + "=" * 90)
    print("CALLING ORIGINAL e1.run(df=fresh42)")
    print("=" * 90)

    direct_result = e1.run(
        df=fresh42,
        verbose=True
    )

finally:

    # ------------------------------------------------
    # Restore original output locations/state
    # ------------------------------------------------

    e1.OUT = original_e1_out
    xc.OUT = original_xc_out

    e1.SEED = original_e1_seed
    xc.SEED = original_xc_seed

    xc.split.__globals__["SEED"] = original_xc_seed
    xc.synth_corpus.__globals__["SEED"] = original_xc_seed


print("\n" + "=" * 90)
print("ORIGINAL MODULE STATE RESTORED")
print("=" * 90)

print("e1.OUT =", e1.OUT)
print("xc.OUT =", xc.OUT)

Original e1.OUT:
/content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/03_SOURCE_CODE/results

Temporary diagnostic OUT:
/content/revision_experiments/R1_phrase_generalization/audit/direct_e1_seed42

Fresh corpus:
shape = (3000, 12)
slice
URLLC    1000
eMBB     1000
mMTC     1000
Name: count, dtype: int64

==========================================================================================
CALLING ORIGINAL e1.run(df=fresh42)
==========================================================================================
========================================================================
EXPERIMENT 1 -- Post-hoc explanation (SHAP)
========================================================================
[S2] Intent Agent: slot filling + binary lexicon ...
     mean slot recall 0.957 | false-positive 0.000 | 1.300 ms/intent
[S4] training Logistic Regression ...
[S4] training Decision Tree ...
[S4] training MLP (64,32) ...
[S4] training Gradient Boosting ...
[S4] training Random Forest ...
  -> /content/revision_experiments/R1_phrase_generalization/audit/direct_e1_seed42/e1_models.csv
               model      acc       f1  cv_mean   cv_std    valid   lat_ms
 Rule-based playbook 0.698889 0.699783      NaN      NaN 0.966667 0.075149
Rule-based + lexicon 0.801111 0.803411      NaN      NaN 0.941111 0.127291
 Logistic Regression 0.896667 0.896805 0.911833 0.012865 0.897778 0.011597
       Decision Tree 0.916667 0.917136 0.910321 0.008895 0.891111 0.003114
         MLP (64,32) 0.906667 0.906737 0.918989 0.006190 0.888889 0.016387
   Gradient Boosting 0.927778 0.927832 0.934708 0.008039 0.890000 0.011870
       Random Forest 0.923333 0.923192 0.924233 0.006614 0.886667 0.110677
[S4] best = Gradient Boosting (selected on 5-fold CV macro F1, train split)
  -> /content/revision_experiments/R1_phrase_generalization/audit/direct_e1_seed42/e1_escalation_oof.csv
[S4b] tau = 0.80 selected on out-of-fold train predictions
 tau  escalated  precision   recall  autonomous_acc
 0.5   0.125714   0.125000 0.240876        0.943355
 0.6   0.152857   0.190031 0.445255        0.957279
 0.7   0.179524   0.230769 0.635036        0.970981
 0.8   0.212381   0.239910 0.781022        0.981862
 0.9   0.270000   0.215168 0.890511        0.990215
  -> /content/revision_experiments/R1_phrase_generalization/audit/direct_e1_seed42/e1_per_class.csv
[S6] computing SHAP attributions ...
     TreeExplainer unavailable (InvalidModelError); falling back to PermutationExplainer
  -> /content/revision_experiments/R1_phrase_generalization/audit/direct_e1_seed42/e1_shap_global.csv
            feature  importance
    reliability (%)    0.232265
    mobility (km/h)    0.124865
          lex:URLLC    0.114931
           lex:eMBB    0.107616
  throughput (Mbps)    0.099608
           lex:mMTC    0.087471
     log throughput    0.053007
       latency (ms)    0.042181
        log latency    0.040614
  density (dev/km2)    0.036297
throughput unstated    0.027779
        log density    0.021980
   latency unstated    0.009594
   density unstated    0.001792
[S6] fidelity: {
  "top1": 0.18666666666666668,
  "rand1": 0.023333333333333334,
  "low1": 0.0,
  "ratio1": 8.0,
  "ratiolow1": 186666666.66666666,
  "top2": 0.3466666666666667,
  "rand2": 0.04,
  "low2": 0.0022222222222222222,
  "ratio2": 8.666666666666666,
  "ratiolow2": 156.0,
  "top3": 0.4633333333333333,
  "rand3": 0.06555555555555556,
  "low3": 0.0033333333333333335,
  "ratio3": 7.0677966101694905,
  "ratiolow3": 139.0,
  "explanation_latency_ms": 237.41054413555554,
  "inference_latency_ms": 0.011870315555724018,
  "latency_ratio": 20000.356605606255,
  "backend": "PermutationExplainer"
}
  -> /content/revision_experiments/R1_phrase_generalization/audit/direct_e1_seed42/e1_escalation.csv
 tau  escalated  precision   recall  autonomous_acc
 0.5   0.124444   0.169643 0.292308        0.941624
 0.6   0.141111   0.212598 0.415385        0.950841
 0.7   0.162222   0.260274 0.584615        0.964191
 0.8   0.207778   0.272727 0.784615        0.980365
 0.9   0.278889   0.239044 0.923077        0.992296
[S5] tau=0.80  OOF(selection) esc 21.2% rec 78.1% auto 98.2%  |  TEST esc 20.8% rec 78.5% auto 98.0%
  -> /content/revision_experiments/R1_phrase_generalization/audit/direct_e1_seed42/e1_escalation_signals.csv
[S5b] escalation signal ablation at matched budget:
                             signal  budget  escalated  precision   recall  autonomous_acc
                    Confidence only    0.12       0.12   0.444444 0.738462        0.978535
     Attribution concentration only    0.12       0.12   0.250000 0.415385        0.952020
              Confidence + contract    0.12       0.12   0.138889 0.230769        0.936869
Confidence + contract + attribution    0.12       0.12   0.138889 0.230769        0.936869
  -> /content/revision_experiments/R1_phrase_generalization/audit/direct_e1_seed42/e1_local_explanations.json
  -> /content/revision_experiments/R1_phrase_generalization/audit/direct_e1_seed42/e1_summary.json
[E1] accuracy 0.9278 | macro F1 0.9278 | OOV gap 11.6 pts | explanation 237.41 ms/intent

==========================================================================================
ORIGINAL MODULE STATE RESTORED
==========================================================================================
e1.OUT = /content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/03_SOURCE_CODE/results
xc.OUT = /content/xagentic_r1_work/XAgentic_Final_Paper_Evidence_2026-10-06/03_SOURCE_CODE/results

In [52]:
print("=" * 100)
print("DIRECT E1 DIAGNOSTIC FILES")
print("=" * 100)

for p in sorted(DIAG.iterdir()):
    print(f"{p.name:40s} {p.stat().st_size:>12,d} bytes")

====================================================================================================
DIRECT E1 DIAGNOSTIC FILES
====================================================================================================
e1_confusion.csv                                   28 bytes
e1_escalation.csv                                 450 bytes
e1_escalation_oof.csv                             424 bytes
e1_escalation_signals.csv                         416 bytes
e1_local_explanations.json                      1,513 bytes
e1_models.csv                                     893 bytes
e1_per_class.csv                                  203 bytes
e1_shap_global.csv                                506 bytes
e1_summary.json                                 4,662 bytes

In [53]:
summary_file = DIAG / "e1_summary.json"

with open(summary_file, "r") as f:
    direct_summary = json.load(f)

print("\n" + "=" * 100)
print("DIRECT ORIGINAL E1 SUMMARY — SEED 42")
print("=" * 100)

for key in [
    "model",
    "model_selection",
    "acc_overall",
    "macro_f1",
    "acc_known",
    "acc_unseen",
    "acc_generic",
    "acc_ambiguous",
    "oov_gap",
]:
    if key in direct_summary:
        print(
            f"{key:25s}: "
            f"{direct_summary[key]}"
        )

====================================================================================================
DIRECT ORIGINAL E1 SUMMARY — SEED 42
====================================================================================================
model                    : Gradient Boosting
model_selection          : 5-fold CV macro F1 on train split
acc_overall              : 0.9277777777777778
macro_f1                 : 0.9278323905230472
acc_known                : 1.0
acc_unseen               : 0.8851851851851852
acc_generic              : 0.8831615120274914
acc_ambiguous            : 0.7768924302788844
oov_gap                  : 0.11582665139366166

In [54]:
# Frozen archived evidence
f42 = (
    frozen_e1[
        frozen_e1["seed"] == 42
    ]
    .iloc[0]
)

direct_acc = float(
    direct_summary["acc_overall"]
)

# Handle either fraction or percentage just in case
if direct_acc > 1:
    direct_acc /= 100.0

direct_f1 = float(
    direct_summary["macro_f1"]
)

comparison = pd.DataFrame([
    {
        "source": "Frozen archived E1",
        "accuracy": float(f42["acc"]) / 100.0,
        "macro_f1": float(f42["macro_f1"]),
        "model": str(f42["model"])
    },
    {
        "source": "Manual reconstruction",
        "accuracy": reproduced_acc,
        "macro_f1": reproduced_f1,
        "model": best_name
    },
    {
        "source": "Direct original e1.run()",
        "accuracy": direct_acc,
        "macro_f1": direct_f1,
        "model": str(
            direct_summary.get(
                "model",
                "UNKNOWN"
            )
        )
    }
])

print("=" * 100)
print("THREE-WAY REPRODUCTION COMPARISON")
print("=" * 100)

display(comparison)

====================================================================================================
THREE-WAY REPRODUCTION COMPARISON
====================================================================================================

                     source  accuracy  macro_f1              model
0        Frozen archived E1  0.933333  0.933523  Gradient Boosting
1     Manual reconstruction  0.927778  0.927832  Gradient Boosting
2  Direct original e1.run()  0.927778  0.927832  Gradient Boosting

In [55]:
# ================================================================
# STEP 21 — FREEZE R1 REPRODUCTION / PROVENANCE DECISION
# ================================================================

import json
from datetime import datetime, timezone

provenance = {
    "experiment": "R1_phrase_generalization",
    "baseline_seed": 42,

    "authoritative_r1_source":
        "03_SOURCE_CODE current frozen snapshot",

    "corpus_generator":
        "xagentic_common.synth_corpus",

    "corpus_n": 3000,
    "p_amb": 0.30,

    "split":
        "70/30 stratified; train-only median imputation",

    "archived_e1": {
        "accuracy": 0.9333333333,
        "macro_f1": 0.9335232669,
        "model": "Gradient Boosting"
    },

    "direct_current_source_reproduction": {
        "accuracy": 0.9277777777777778,
        "macro_f1": 0.9278323905230472,
        "model": "Gradient Boosting"
    },

    "manual_reproduction": {
        "accuracy": 0.9277777777777778,
        "macro_f1": 0.9278323905230472,
        "model": "Gradient Boosting"
    },

    "decision":
        (
            "Archived E1 aggregate is retained as historical evidence. "
            "R1 uses the packaged current frozen source snapshot because "
            "manual reconstruction and direct original e1.run() reproduce "
            "each other exactly. No attempt is made to tune or alter R1 "
            "to reproduce the historical archived metric."
        ),

    "status":
        "CURRENT_SOURCE_REPRODUCTION_PASS_ARCHIVE_MISMATCH_DOCUMENTED"
}

path = R1 / "audit/r1_baseline_provenance.json"

with open(path, "w", encoding="utf-8") as f:
    json.dump(
        provenance,
        f,
        indent=2
    )

print(json.dumps(provenance, indent=2))

print("\nSaved:")
print(path)

print(
    "\nR1 BASELINE PROVENANCE: FROZEN"
)

{
  "experiment": "R1_phrase_generalization",
  "baseline_seed": 42,
  "authoritative_r1_source": "03_SOURCE_CODE current frozen snapshot",
  "corpus_generator": "xagentic_common.synth_corpus",
  "corpus_n": 3000,
  "p_amb": 0.3,
  "split": "70/30 stratified; train-only median imputation",
  "archived_e1": {
    "accuracy": 0.9333333333,
    "macro_f1": 0.9335232669,
    "model": "Gradient Boosting"
  },
  "direct_current_source_reproduction": {
    "accuracy": 0.9277777777777778,
    "macro_f1": 0.9278323905230472,
    "model": "Gradient Boosting"
  },
  "manual_reproduction": {
    "accuracy": 0.9277777777777778,
    "macro_f1": 0.9278323905230472,
    "model": "Gradient Boosting"
  },
  "decision": "Archived E1 aggregate is retained as historical evidence. R1 uses the packaged current frozen source snapshot because manual reconstruction and direct original e1.run() reproduce each other exactly. No attempt is made to tune or alter R1 to reproduce the historical archived metric.",
  "status": "CURRENT_SOURCE_REPRODUCTION_PASS_ARCHIVE_MISMATCH_DOCUMENTED"
}

Saved:
/content/revision_experiments/R1_phrase_generalization/audit/r1_baseline_provenance.json

R1 BASELINE PROVENANCE: FROZEN

In [56]:
# ================================================================
# STEP 22 — FINAL R1 L1 / L3 / L4 DATASET CONSTRUCTION
# ================================================================

import re
import pandas as pd
import numpy as np
from pathlib import Path

SEEDS = [42, 43, 44, 45, 46]

FINAL_COND = R1 / "data/final_conditions"

for condition in [
    "L1_original",
    "L3_generic_kpi",
    "L4_kpi_only",
]:
    (FINAL_COND / condition).mkdir(
        parents=True,
        exist_ok=True
    )


# ------------------------------------------------
# L3:
# Replace the exact use-case phrase with a
# class-neutral phrase.
#
# KPI wording and template structure remain intact.
# ------------------------------------------------

def make_l3_text(row):

    text = str(row["text"])
    use_case = str(row["use_case"])

    if use_case not in text:
        raise ValueError(
            f"Use-case phrase not found.\n"
            f"id={row['id']}\n"
            f"use_case={use_case}\n"
            f"text={text}"
        )

    return text.replace(
        use_case,
        "network service",
        1
    )


# ------------------------------------------------
# L4:
# Keep ONLY KPI fragments explicitly observable
# in the original intent.
#
# IMPORTANT:
# We do NOT reconstruct unstated latent KPI values.
# ------------------------------------------------

KPI_PATTERNS = [
    # latency
    r"latency\s*(?:<=|≤|=|of|is|around|about)?\s*"
    r"\d+(?:\.\d+)?\s*ms",

    # throughput
    r"throughput\s*(?:>=|≥|=|of|is|around|about)?\s*"
    r"\d+(?:\.\d+)?\s*(?:Mbps|Gbps)",

    # reliability
    r"reliability\s*(?:>=|≥|=|of|is|around|about)?\s*"
    r"\d+(?:\.\d+)?\s*%",

    # density
    r"density\s*(?:>=|≥|=|of|is|around|about)?\s*"
    r"\d+(?:\.\d+)?\s*(?:devices/)?km(?:\^?2|²)",

    # mobility
    r"mobility\s*(?:<=|≤|=|of|is|around|about)?\s*"
    r"\d+(?:\.\d+)?\s*km/h",
]


def make_l4_text(text):

    text = str(text)

    fragments = []

    for pattern in KPI_PATTERNS:

        matches = re.findall(
            pattern,
            text,
            flags=re.IGNORECASE
        )

        fragments.extend(matches)

    if not fragments:
        raise ValueError(
            "No observable KPI fragments found:\n"
            + text
        )

    return "; ".join(fragments)


# ------------------------------------------------
# Generate all seeds
# ------------------------------------------------

construction_rows = []

for seed in SEEDS:

    src = (
        FINAL_DATA /
        f"r1_corpus_seed{seed}.csv"
    )

    df = pd.read_csv(src)

    assert len(df) == 3000

    # ---------------------------
    # L1
    # ---------------------------

    l1 = df.copy()

    l1["r1_condition"] = "L1_original"
    l1["r1_text"] = l1["text"]

    # ---------------------------
    # L3
    # ---------------------------

    l3 = df.copy()

    l3["r1_condition"] = "L3_generic_kpi"

    l3["r1_text"] = l3.apply(
        make_l3_text,
        axis=1
    )

    # ---------------------------
    # L4
    # ---------------------------

    l4 = df.copy()

    l4["r1_condition"] = "L4_kpi_only"

    l4["r1_text"] = l4["text"].apply(
        make_l4_text
    )

    # ---------------------------
    # Save
    # ---------------------------

    l1.to_csv(
        FINAL_COND /
        "L1_original" /
        f"seed_{seed}.csv",
        index=False
    )

    l3.to_csv(
        FINAL_COND /
        "L3_generic_kpi" /
        f"seed_{seed}.csv",
        index=False
    )

    l4.to_csv(
        FINAL_COND /
        "L4_kpi_only" /
        f"seed_{seed}.csv",
        index=False
    )

    construction_rows.append({
        "seed": seed,
        "L1_n": len(l1),
        "L3_n": len(l3),
        "L4_n": len(l4),
        "L1_unique_ids": l1["id"].nunique(),
        "L3_unique_ids": l3["id"].nunique(),
        "L4_unique_ids": l4["id"].nunique(),
    })


construction = pd.DataFrame(
    construction_rows
)

display(construction)

assert (construction["L1_n"] == 3000).all()
assert (construction["L3_n"] == 3000).all()
assert (construction["L4_n"] == 3000).all()

print()
print("=" * 90)
print("FINAL L1/L3/L4 DATASET CONSTRUCTION: PASS")
print("=" * 90)

ValueError: No observable KPI fragments found:
Set up municipal network service. It should sustain 126 Mbps for roughly 7,624 devices per km2.

In [57]:
# ================================================================
# STEP 22A — CORRECT L4 USING FROZEN PARSER
# ================================================================

import numpy as np

def make_l4_text(text):
    """
    Construct KPI-only text using ONLY KPI values observable by
    the frozen xagentic_common.parse_slots() parser.

    No latent ground-truth KPI values are used.
    """

    text = str(text)

    parsed = xc.parse_slots(text)

    fragments = []

    # IMPORTANT:
    # Use wording understood by the same frozen parser.

    if np.isfinite(float(parsed.latency_ms)):
        fragments.append(
            f"latency {float(parsed.latency_ms):g} ms"
        )

    if np.isfinite(float(parsed.throughput_mbps)):
        fragments.append(
            f"throughput {float(parsed.throughput_mbps):g} Mbps"
        )

    if np.isfinite(float(parsed.reliability_pct)):
        fragments.append(
            f"reliability {float(parsed.reliability_pct):g}%"
        )

    if np.isfinite(float(parsed.density_per_km2)):
        fragments.append(
            f"density {float(parsed.density_per_km2):g} devices/km2"
        )

    if np.isfinite(float(parsed.mobility_kmh)):
        fragments.append(
            f"mobility {float(parsed.mobility_kmh):g} km/h"
        )

    if not fragments:
        raise ValueError(
            "Frozen parser found no observable KPI values:\n"
            + text
        )

    return "; ".join(fragments)


# ------------------------------------------------
# Test specifically against the failed example
# ------------------------------------------------

failed_example = (
    "Set up municipal network service. "
    "It should sustain 126 Mbps for roughly "
    "7,624 devices per km2."
)

print("ORIGINAL:")
print(failed_example)

print("\nFROZEN PARSER:")
print(xc.parse_slots(failed_example))

print("\nL4:")
print(make_l4_text(failed_example))

print("\nL4 RE-PARSED:")
print(
    xc.parse_slots(
        make_l4_text(failed_example)
    )
)

ORIGINAL:
Set up municipal network service. It should sustain 126 Mbps for roughly 7,624 devices per km2.

FROZEN PARSER:
Intent(latency_ms=nan, throughput_mbps=126.0, reliability_pct=nan, density_per_km2=7624.0, mobility_kmh=nan, lex_embb=0.0, lex_urllc=0.0, lex_mmtc=0.0)

L4:
throughput 126 Mbps; density 7624 devices/km2

L4 RE-PARSED:
Intent(latency_ms=nan, throughput_mbps=126.0, reliability_pct=nan, density_per_km2=7624.0, mobility_kmh=nan, lex_embb=0.0, lex_urllc=0.0, lex_mmtc=0.0)

In [58]:
# ================================================================
# STEP 22B — SINGLE-EXAMPLE FEATURE EQUIVALENCE GATE
# ================================================================

test_original = pd.DataFrame({
    "text": [failed_example]
})

test_l4 = pd.DataFrame({
    "text": [make_l4_text(failed_example)]
})

X_original = xc.build_features(test_original)
X_l4 = xc.build_features(test_l4)

check = pd.DataFrame({
    "feature": X_original.columns,
    "original": X_original.iloc[0].values,
    "L4": X_l4.iloc[0].values,
})

check["equal"] = (
    np.isclose(
        check["original"].astype(float),
        check["L4"].astype(float),
        equal_nan=True
    )
)

display(check)

NON_LEX = [
    "latency_ms",
    "throughput_mbps",
    "reliability_pct",
    "density_per_km2",
    "mobility_kmh",
    "log_latency",
    "log_throughput",
    "log_density",
    "miss_latency",
    "miss_throughput",
    "miss_density",
]

nonlex_ok = np.allclose(
    X_original[NON_LEX].to_numpy(),
    X_l4[NON_LEX].to_numpy(),
    equal_nan=True
)

print()
print("Non-lexical feature preservation:", nonlex_ok)

assert nonlex_ok

print(
    "\nSTEP 22B L4 SINGLE-EXAMPLE "
    "FEATURE PRESERVATION: PASS"
)

            feature     original           L4  equal
0        latency_ms          NaN          NaN   True
1   throughput_mbps   126.000000   126.000000   True
2   reliability_pct          NaN          NaN   True
3   density_per_km2  7624.000000  7624.000000   True
4      mobility_kmh          NaN          NaN   True
5       log_latency          NaN          NaN   True
6    log_throughput     2.100371     2.100371   True
7       log_density     3.882183     3.882183   True
8      miss_latency     1.000000     1.000000   True
9   miss_throughput     0.000000     0.000000   True
10     miss_density     0.000000     0.000000   True
11         lex_embb     0.000000     0.000000   True
12        lex_urllc     0.000000     0.000000   True
13         lex_mmtc     0.000000     0.000000   True

Non-lexical feature preservation: True

STEP 22B L4 SINGLE-EXAMPLE FEATURE PRESERVATION: PASS

In [59]:
# ================================================================
# STEP 24 — FINAL L1 / L3 / L4 GENERATION + FULL HARD AUDIT
# ================================================================

from pathlib import Path
import pandas as pd
import numpy as np
import json

SEEDS = [42, 43, 44, 45, 46]

FINAL_COND = R1 / "data/final_conditions"

for condition in [
    "L1_original",
    "L3_generic_kpi",
    "L4_kpi_only",
]:
    (FINAL_COND / condition).mkdir(
        parents=True,
        exist_ok=True
    )

NON_LEX = [
    "latency_ms",
    "throughput_mbps",
    "reliability_pct",
    "density_per_km2",
    "mobility_kmh",
    "log_latency",
    "log_throughput",
    "log_density",
    "miss_latency",
    "miss_throughput",
    "miss_density",
]

LEX = [
    "lex_embb",
    "lex_urllc",
    "lex_mmtc",
]


# ------------------------------------------------
# L3 helper
# ------------------------------------------------

def make_l3_text(row):

    text = str(row["text"])
    use_case = str(row["use_case"])

    if use_case not in text:
        raise ValueError(
            f"Use-case phrase not found: "
            f"id={row['id']} | "
            f"use_case={use_case}"
        )

    return text.replace(
        use_case,
        "network service",
        1
    )


# ------------------------------------------------
# L4 helper — frozen parser based
# ------------------------------------------------

def make_l4_text(text):

    text = str(text)

    parsed = xc.parse_slots(text)

    fragments = []

    if np.isfinite(float(parsed.latency_ms)):
        fragments.append(
            f"latency {float(parsed.latency_ms):g} ms"
        )

    if np.isfinite(float(parsed.throughput_mbps)):
        fragments.append(
            f"throughput {float(parsed.throughput_mbps):g} Mbps"
        )

    if np.isfinite(float(parsed.reliability_pct)):
        fragments.append(
            f"reliability {float(parsed.reliability_pct):g}%"
        )

    if np.isfinite(float(parsed.density_per_km2)):
        fragments.append(
            f"density {float(parsed.density_per_km2):g} devices/km2"
        )

    if np.isfinite(float(parsed.mobility_kmh)):
        fragments.append(
            f"mobility {float(parsed.mobility_kmh):g} km/h"
        )

    if not fragments:
        raise ValueError(
            "No KPI observable by frozen parser:\n"
            + text
        )

    return "; ".join(fragments)


# ------------------------------------------------
# Utility: build features from r1_text
# ------------------------------------------------

def features_from_r1(df):

    tmp = df.copy()

    tmp["text"] = tmp["r1_text"]

    return xc.build_features(tmp)


# ------------------------------------------------
# Generate + audit
# ------------------------------------------------

audit_rows = []

for seed in SEEDS:

    print("\n" + "=" * 90)
    print(f"SEED {seed}")
    print("=" * 90)

    src = (
        FINAL_DATA /
        f"r1_corpus_seed{seed}.csv"
    )

    base = pd.read_csv(src)

    assert len(base) == 3000
    assert base["id"].nunique() == 3000

    # ============================================================
    # L1
    # ============================================================

    l1 = base.copy()

    l1["r1_condition"] = "L1_original"
    l1["r1_text"] = l1["text"]

    # ============================================================
    # L3
    # ============================================================

    l3 = base.copy()

    l3["r1_condition"] = "L3_generic_kpi"

    l3["r1_text"] = l3.apply(
        make_l3_text,
        axis=1
    )

    # ============================================================
    # L4
    # ============================================================

    l4 = base.copy()

    l4["r1_condition"] = "L4_kpi_only"

    l4["r1_text"] = l4["text"].apply(
        make_l4_text
    )

    # ============================================================
    # BASIC ID / LABEL PRESERVATION
    # ============================================================

    assert l1["id"].equals(l3["id"])
    assert l1["id"].equals(l4["id"])

    assert l1["slice"].equals(l3["slice"])
    assert l1["slice"].equals(l4["slice"])

    assert l1["ambiguous"].equals(
        l3["ambiguous"]
    )

    assert l1["ambiguous"].equals(
        l4["ambiguous"]
    )

    # ============================================================
    # FEATURE EXTRACTION
    # ============================================================

    X1 = features_from_r1(l1)
    X3 = features_from_r1(l3)
    X4 = features_from_r1(l4)

    # ============================================================
    # NON-LEXICAL PRESERVATION
    # ============================================================

    l1_l3_nonlex = np.allclose(
        X1[NON_LEX].to_numpy(),
        X3[NON_LEX].to_numpy(),
        equal_nan=True,
        rtol=0,
        atol=0
    )

    l1_l4_nonlex = np.allclose(
        X1[NON_LEX].to_numpy(),
        X4[NON_LEX].to_numpy(),
        equal_nan=True,
        rtol=0,
        atol=0
    )

    # ============================================================
    # LEXICAL ABLATION
    # ============================================================

    l3_lex_zero = np.allclose(
        X3[LEX].to_numpy(),
        0.0,
        rtol=0,
        atol=0
    )

    l4_lex_zero = np.allclose(
        X4[LEX].to_numpy(),
        0.0,
        rtol=0,
        atol=0
    )

    # ============================================================
    # L3 vs L4 REPRESENTATIONAL EQUIVALENCE
    # ============================================================

    l3_l4_full_equal = np.allclose(
        X3.to_numpy(),
        X4.to_numpy(),
        equal_nan=True,
        rtol=0,
        atol=0
    )

    # ============================================================
    # L3 phrase-removal audit
    # ============================================================

    phrase_failures = 0

    for _, row in l3.iterrows():

        original_phrase = str(
            row["use_case"]
        ).lower()

        transformed = str(
            row["r1_text"]
        ).lower()

        if original_phrase in transformed:
            phrase_failures += 1

    # ============================================================
    # Record
    # ============================================================

    row = {
        "seed": seed,

        "n": len(base),

        "L1_equals_L3_nonlex":
            bool(l1_l3_nonlex),

        "L1_equals_L4_nonlex":
            bool(l1_l4_nonlex),

        "L3_lex_zero":
            bool(l3_lex_zero),

        "L4_lex_zero":
            bool(l4_lex_zero),

        "L3_equals_L4_full_features":
            bool(l3_l4_full_equal),

        "L3_phrase_failures":
            int(phrase_failures),

        "L1_lexical_rows":
            int(
                (X1[LEX].sum(axis=1) > 0)
                .sum()
            ),

        "L3_lexical_rows":
            int(
                (X3[LEX].sum(axis=1) > 0)
                .sum()
            ),

        "L4_lexical_rows":
            int(
                (X4[LEX].sum(axis=1) > 0)
                .sum()
            ),
    }

    audit_rows.append(row)

    print(row)

    # ============================================================
    # HARD SEED-LEVEL GATES
    # ============================================================

    assert l1_l3_nonlex
    assert l1_l4_nonlex

    assert l3_lex_zero
    assert l4_lex_zero

    assert phrase_failures == 0

    # ============================================================
    # SAVE ONLY AFTER PASS
    # ============================================================

    l1.to_csv(
        FINAL_COND /
        "L1_original" /
        f"seed_{seed}.csv",
        index=False
    )

    l3.to_csv(
        FINAL_COND /
        "L3_generic_kpi" /
        f"seed_{seed}.csv",
        index=False
    )

    l4.to_csv(
        FINAL_COND /
        "L4_kpi_only" /
        f"seed_{seed}.csv",
        index=False
    )


# ================================================================
# FINAL AUDIT TABLE
# ================================================================

feature_audit = pd.DataFrame(
    audit_rows
)

audit_path = (
    R1 /
    "audit/final_L1_L3_L4_feature_audit.csv"
)

feature_audit.to_csv(
    audit_path,
    index=False
)

print("\n" + "=" * 100)
print("FINAL L1 / L3 / L4 FEATURE AUDIT")
print("=" * 100)

display(feature_audit)

print("\nSaved:")
print(audit_path)

print("\n" + "=" * 100)
print(
    "FINAL L1/L3/L4 CONSTRUCTION "
    "AND FEATURE AUDIT: PASS"
)
print("=" * 100)

==========================================================================================
SEED 42
==========================================================================================
{'seed': 42, 'n': 3000, 'L1_equals_L3_nonlex': True, 'L1_equals_L4_nonlex': True, 'L3_lex_zero': True, 'L4_lex_zero': True, 'L3_equals_L4_full_features': True, 'L3_phrase_failures': 0, 'L1_lexical_rows': 1193, 'L3_lexical_rows': 0, 'L4_lexical_rows': 0}

==========================================================================================
SEED 43
==========================================================================================
{'seed': 43, 'n': 3000, 'L1_equals_L3_nonlex': True, 'L1_equals_L4_nonlex': True, 'L3_lex_zero': True, 'L4_lex_zero': True, 'L3_equals_L4_full_features': True, 'L3_phrase_failures': 0, 'L1_lexical_rows': 1182, 'L3_lexical_rows': 0, 'L4_lexical_rows': 0}

==========================================================================================
SEED 44
==========================================================================================
{'seed': 44, 'n': 3000, 'L1_equals_L3_nonlex': True, 'L1_equals_L4_nonlex': True, 'L3_lex_zero': True, 'L4_lex_zero': True, 'L3_equals_L4_full_features': True, 'L3_phrase_failures': 0, 'L1_lexical_rows': 1218, 'L3_lexical_rows': 0, 'L4_lexical_rows': 0}

==========================================================================================
SEED 45
==========================================================================================
{'seed': 45, 'n': 3000, 'L1_equals_L3_nonlex': True, 'L1_equals_L4_nonlex': True, 'L3_lex_zero': True, 'L4_lex_zero': True, 'L3_equals_L4_full_features': True, 'L3_phrase_failures': 0, 'L1_lexical_rows': 1209, 'L3_lexical_rows': 0, 'L4_lexical_rows': 0}

==========================================================================================
SEED 46
==========================================================================================
{'seed': 46, 'n': 3000, 'L1_equals_L3_nonlex': True, 'L1_equals_L4_nonlex': True, 'L3_lex_zero': True, 'L4_lex_zero': True, 'L3_equals_L4_full_features': True, 'L3_phrase_failures': 0, 'L1_lexical_rows': 1159, 'L3_lexical_rows': 0, 'L4_lexical_rows': 0}

====================================================================================================
FINAL L1 / L3 / L4 FEATURE AUDIT
====================================================================================================

,seed,n,L1_equals_L3_nonlex,L1_equals_L4_nonlex,L3_lex_zero,L4_lex_zero,L3_equals_L4_full_features,L3_phrase_failures,L1_lexical_rows,L3_lexical_rows,L4_lexical_rows
0,42,3000,True,True,True,True,True,0,1193,0,0
1,43,3000,True,True,True,True,True,0,1182,0,0
2,44,3000,True,True,True,True,True,0,1218,0,0
3,45,3000,True,True,True,True,True,0,1209,0,0
4,46,3000,True,True,True,True,True,0,1159,0,0

Saved:
/content/revision_experiments/R1_phrase_generalization/audit/final_L1_L3_L4_feature_audit.csv

====================================================================================================
FINAL L1/L3/L4 CONSTRUCTION AND FEATURE AUDIT: PASS
====================================================================================================

In [60]:
# ================================================================
# STEP 25 — FINAL L2 STRICT PHRASE-FAMILY-HELD-OUT SPLITS
# ================================================================

from pathlib import Path
import pandas as pd
import numpy as np
import json
import hashlib

SEEDS = [42, 43, 44, 45, 46]

L2_DIR = FINAL_COND / "L2_phrase_family_heldout"
L2_DIR.mkdir(parents=True, exist_ok=True)

L2_SPLITS = R1 / "splits/L2_phrase_family_heldout"
L2_SPLITS.mkdir(parents=True, exist_ok=True)

L2_MANIFESTS = R1 / "manifests/L2_phrase_family_heldout"
L2_MANIFESTS.mkdir(parents=True, exist_ok=True)


def sha256_file(path):
    h = hashlib.sha256()

    with open(path, "rb") as f:
        for chunk in iter(
            lambda: f.read(1024 * 1024),
            b""
        ):
            h.update(chunk)

    return h.hexdigest()


audit_rows = []

for seed in SEEDS:

    print("\n" + "=" * 100)
    print(f"L2 — SEED {seed}")
    print("=" * 100)

    src = (
        FINAL_DATA /
        f"r1_corpus_seed{seed}.csv"
    )

    df = pd.read_csv(src)

    assert len(df) == 3000

    # ------------------------------------------------------------
    # L2 MAIN TEST:
    # use only class-specific known/unseen phrase families.
    #
    # Generic phrases are deliberately excluded because they are
    # shared across labels and therefore cannot provide a strict
    # class-specific family-held-out partition.
    # ------------------------------------------------------------

    eligible = df[
        df["uc_kind"].isin(
            ["known", "unseen"]
        )
    ].copy()

    assert len(eligible) > 0

    rng = np.random.RandomState(seed)

    train_families = []
    test_families = []

    family_manifest = []

    # ------------------------------------------------------------
    # Split separately by class AND phrase type.
    # ------------------------------------------------------------

    for slice_name in xc.SLICES:

        for kind in ["known", "unseen"]:

            families = sorted(
                eligible.loc[
                    (eligible["slice"] == slice_name) &
                    (eligible["uc_kind"] == kind),
                    "use_case"
                ].unique().tolist()
            )

            print(
                f"{slice_name:6s} | "
                f"{kind:6s} | "
                f"{len(families)} families"
            )

            # Frozen corpus design:
            # known  = 5 families
            # unseen = 4 families
            if kind == "known":
                assert len(families) == 5
                n_test = 2
            else:
                assert len(families) == 4
                n_test = 1

            shuffled = list(families)
            rng.shuffle(shuffled)

            test_here = sorted(
                shuffled[:n_test]
            )

            train_here = sorted(
                shuffled[n_test:]
            )

            assert set(train_here).isdisjoint(
                set(test_here)
            )

            train_families.extend(
                [
                    (slice_name, kind, f)
                    for f in train_here
                ]
            )

            test_families.extend(
                [
                    (slice_name, kind, f)
                    for f in test_here
                ]
            )

            for family in train_here:
                family_manifest.append({
                    "seed": seed,
                    "slice": slice_name,
                    "uc_kind": kind,
                    "use_case": family,
                    "partition": "train",
                })

            for family in test_here:
                family_manifest.append({
                    "seed": seed,
                    "slice": slice_name,
                    "uc_kind": kind,
                    "use_case": family,
                    "partition": "test",
                })

    # ------------------------------------------------------------
    # Convert family lists to lookup sets.
    # Include slice + kind + use_case so the definition is explicit.
    # ------------------------------------------------------------

    train_keys = set(train_families)
    test_keys = set(test_families)

    assert train_keys.isdisjoint(
        test_keys
    )

    assert len(train_keys) == 18
    assert len(test_keys) == 9

    # ------------------------------------------------------------
    # Assign rows
    # ------------------------------------------------------------

    def row_key(row):
        return (
            row["slice"],
            row["uc_kind"],
            row["use_case"],
        )

    eligible["_family_key"] = eligible.apply(
        row_key,
        axis=1
    )

    train = eligible[
        eligible["_family_key"].isin(
            train_keys
        )
    ].copy()

    test = eligible[
        eligible["_family_key"].isin(
            test_keys
        )
    ].copy()

    # ------------------------------------------------------------
    # HARD COVERAGE CHECK
    # Every eligible row must belong to exactly one side.
    # ------------------------------------------------------------

    assert (
        len(train) + len(test)
        == len(eligible)
    )

    assert set(train["id"]).isdisjoint(
        set(test["id"])
    )

    # ------------------------------------------------------------
    # STRONGEST LEAKAGE CHECK:
    # NO use_case phrase may occur in both train and test.
    # ------------------------------------------------------------

    train_phrase_set = set(
        train["use_case"].unique()
    )

    test_phrase_set = set(
        test["use_case"].unique()
    )

    phrase_overlap = (
        train_phrase_set &
        test_phrase_set
    )

    assert len(phrase_overlap) == 0, (
        f"Phrase leakage detected: "
        f"{phrase_overlap}"
    )

    # ------------------------------------------------------------
    # Additional class-specific overlap check
    # ------------------------------------------------------------

    train_family_set = set(
        zip(
            train["slice"],
            train["uc_kind"],
            train["use_case"]
        )
    )

    test_family_set = set(
        zip(
            test["slice"],
            test["uc_kind"],
            test["use_case"]
        )
    )

    family_overlap = (
        train_family_set &
        test_family_set
    )

    assert len(family_overlap) == 0

    # ------------------------------------------------------------
    # Add R1 metadata
    # ------------------------------------------------------------

    train["r1_condition"] = (
        "L2_phrase_family_heldout"
    )

    test["r1_condition"] = (
        "L2_phrase_family_heldout"
    )

    train["r1_partition"] = "train"
    test["r1_partition"] = "test"

    train["r1_text"] = train["text"]
    test["r1_text"] = test["text"]

    train.drop(
        columns=["_family_key"],
        inplace=True
    )

    test.drop(
        columns=["_family_key"],
        inplace=True
    )

    # ------------------------------------------------------------
    # Counts
    # ------------------------------------------------------------

    train_counts = (
        train["slice"]
        .value_counts()
        .reindex(xc.SLICES)
        .fillna(0)
        .astype(int)
    )

    test_counts = (
        test["slice"]
        .value_counts()
        .reindex(xc.SLICES)
        .fillna(0)
        .astype(int)
    )

    test_amb_counts = (
        test["ambiguous"]
        .value_counts()
        .sort_index()
    )

    # ------------------------------------------------------------
    # Lexical-hit audit
    #
    # IMPORTANT:
    # L2 is NOT supposed to have zero lexical hits.
    # We preserve the original frozen feature extractor.
    # ------------------------------------------------------------

    Xtr_raw = xc.build_features(train)
    Xte_raw = xc.build_features(test)

    lex_cols = [
        "lex_embb",
        "lex_urllc",
        "lex_mmtc",
    ]

    train_lexical_rows = int(
        (
            Xtr_raw[lex_cols]
            .sum(axis=1) > 0
        ).sum()
    )

    test_lexical_rows = int(
        (
            Xte_raw[lex_cols]
            .sum(axis=1) > 0
        ).sum()
    )

    # ------------------------------------------------------------
    # Save split
    # ------------------------------------------------------------

    train_path = (
        L2_DIR /
        f"seed_{seed}_train.csv"
    )

    test_path = (
        L2_DIR /
        f"seed_{seed}_test.csv"
    )

    train.to_csv(
        train_path,
        index=False
    )

    test.to_csv(
        test_path,
        index=False
    )

    # ------------------------------------------------------------
    # Save family manifest
    # ------------------------------------------------------------

    manifest_df = pd.DataFrame(
        family_manifest
    ).sort_values(
        [
            "slice",
            "uc_kind",
            "partition",
            "use_case",
        ]
    )

    manifest_path = (
        L2_MANIFESTS /
        f"seed_{seed}_families.csv"
    )

    manifest_df.to_csv(
        manifest_path,
        index=False
    )

    # ------------------------------------------------------------
    # Save IDs separately for reproducibility
    # ------------------------------------------------------------

    pd.DataFrame({
        "id": train["id"].tolist()
    }).to_csv(
        L2_SPLITS /
        f"seed_{seed}_train_ids.csv",
        index=False
    )

    pd.DataFrame({
        "id": test["id"].tolist()
    }).to_csv(
        L2_SPLITS /
        f"seed_{seed}_test_ids.csv",
        index=False
    )

    # ------------------------------------------------------------
    # Audit row
    # ------------------------------------------------------------

    audit_row = {
        "seed": seed,

        "eligible_n":
            int(len(eligible)),

        "train_n":
            int(len(train)),

        "test_n":
            int(len(test)),

        "train_families":
            int(len(train_keys)),

        "test_families":
            int(len(test_keys)),

        "phrase_overlap":
            int(len(phrase_overlap)),

        "family_overlap":
            int(len(family_overlap)),

        "train_eMBB":
            int(train_counts["eMBB"]),

        "train_URLLC":
            int(train_counts["URLLC"]),

        "train_mMTC":
            int(train_counts["mMTC"]),

        "test_eMBB":
            int(test_counts["eMBB"]),

        "test_URLLC":
            int(test_counts["URLLC"]),

        "test_mMTC":
            int(test_counts["mMTC"]),

        "test_nonambiguous":
            int(test_amb_counts.get(0, 0)),

        "test_ambiguous":
            int(test_amb_counts.get(1, 0)),

        "train_lexical_rows":
            train_lexical_rows,

        "test_lexical_rows":
            test_lexical_rows,

        "train_sha256":
            sha256_file(train_path),

        "test_sha256":
            sha256_file(test_path),
    }

    audit_rows.append(
        audit_row
    )

    print("\nAUDIT:")
    print(audit_row)


# ================================================================
# FINAL L2 AUDIT
# ================================================================

l2_audit = pd.DataFrame(
    audit_rows
)

l2_audit_path = (
    R1 /
    "audit/final_L2_phrase_family_audit.csv"
)

l2_audit.to_csv(
    l2_audit_path,
    index=False
)

print("\n" + "=" * 110)
print("FINAL L2 PHRASE-FAMILY-HELD-OUT AUDIT")
print("=" * 110)

display(l2_audit)

# ------------------------------------------------
# FINAL HARD GATES
# ------------------------------------------------

assert (
    l2_audit["train_families"] == 18
).all()

assert (
    l2_audit["test_families"] == 9
).all()

assert (
    l2_audit["phrase_overlap"] == 0
).all()

assert (
    l2_audit["family_overlap"] == 0
).all()

assert (
    l2_audit[
        [
            "train_eMBB",
            "train_URLLC",
            "train_mMTC",
        ]
    ] > 0
).all().all()

assert (
    l2_audit[
        [
            "test_eMBB",
            "test_URLLC",
            "test_mMTC",
        ]
    ] > 0
).all().all()

print("\nSaved:")
print(l2_audit_path)

print("\n" + "=" * 110)
print(
    "FINAL L2 PHRASE-FAMILY-HELD-OUT "
    "CONSTRUCTION: PASS"
)
print("=" * 110)

====================================================================================================
L2 — SEED 42
====================================================================================================
eMBB   | known  | 5 families
eMBB   | unseen | 4 families
URLLC  | known  | 5 families
URLLC  | unseen | 4 families
mMTC   | known  | 5 families
mMTC   | unseen | 4 families

AUDIT:
{'seed': 42, 'eligible_n': 2057, 'train_n': 1393, 'test_n': 664, 'train_families': 18, 'test_families': 9, 'phrase_overlap': 0, 'family_overlap': 0, 'train_eMBB': 441, 'train_URLLC': 477, 'train_mMTC': 475, 'test_eMBB': 231, 'test_URLLC': 227, 'test_mMTC': 206, 'test_nonambiguous': 468, 'test_ambiguous': 196, 'train_lexical_rows': 728, 'test_lexical_rows': 465, 'train_sha256': '3818c92417123f4832a5a94fba203b6bb7ea27d4197009e6c708615ac5895284', 'test_sha256': 'e35d899bf26522d377532e36d3a56426467c3ecce33f06811ead78c54e0a61c3'}

====================================================================================================
L2 — SEED 43
====================================================================================================
eMBB   | known  | 5 families
eMBB   | unseen | 4 families
URLLC  | known  | 5 families
URLLC  | unseen | 4 families
mMTC   | known  | 5 families
mMTC   | unseen | 4 families

AUDIT:
{'seed': 43, 'eligible_n': 2078, 'train_n': 1376, 'test_n': 702, 'train_families': 18, 'test_families': 9, 'phrase_overlap': 0, 'family_overlap': 0, 'train_eMBB': 467, 'train_URLLC': 444, 'train_mMTC': 465, 'test_eMBB': 238, 'test_URLLC': 225, 'test_mMTC': 239, 'test_nonambiguous': 476, 'test_ambiguous': 226, 'train_lexical_rows': 708, 'test_lexical_rows': 474, 'train_sha256': '0b4bb6e6704a0a2eb953a7f39f48ec10587fed089c79addd4a31a914a1aec63a', 'test_sha256': 'a33b14b7276ba6ee681d678e7fcbafc897d2093a76d4f6ec7565f4ccdd494054'}

====================================================================================================
L2 — SEED 44
====================================================================================================
eMBB   | known  | 5 families
eMBB   | unseen | 4 families
URLLC  | known  | 5 families
URLLC  | unseen | 4 families
mMTC   | known  | 5 families
mMTC   | unseen | 4 families

AUDIT:
{'seed': 44, 'eligible_n': 2101, 'train_n': 1368, 'test_n': 733, 'train_families': 18, 'test_families': 9, 'phrase_overlap': 0, 'family_overlap': 0, 'train_eMBB': 464, 'train_URLLC': 455, 'train_mMTC': 449, 'test_eMBB': 233, 'test_URLLC': 243, 'test_mMTC': 257, 'test_nonambiguous': 484, 'test_ambiguous': 249, 'train_lexical_rows': 726, 'test_lexical_rows': 492, 'train_sha256': '6e8680bc50d5d910797722c6cbc241c3649dfe7284b800b2990255ee2eddbc99', 'test_sha256': 'f2de72d19c59073e984f1bbf83fc4e4b37062122d0f7f9dba132df44e55767ce'}

====================================================================================================
L2 — SEED 45
====================================================================================================
eMBB   | known  | 5 families
eMBB   | unseen | 4 families
URLLC  | known  | 5 families
URLLC  | unseen | 4 families
mMTC   | known  | 5 families
mMTC   | unseen | 4 families

AUDIT:
{'seed': 45, 'eligible_n': 2092, 'train_n': 1392, 'test_n': 700, 'train_families': 18, 'test_families': 9, 'phrase_overlap': 0, 'family_overlap': 0, 'train_eMBB': 467, 'train_URLLC': 462, 'train_mMTC': 463, 'test_eMBB': 219, 'test_URLLC': 229, 'test_mMTC': 252, 'test_nonambiguous': 468, 'test_ambiguous': 232, 'train_lexical_rows': 730, 'test_lexical_rows': 479, 'train_sha256': 'eff81f92576df1917cc3317bdaa2e203f6433789b56ad42a1e5b329d9c99e77f', 'test_sha256': '5eb319550e5ca5644cf085b700919433f77d0a124f2185e383cb4f8379036c59'}

====================================================================================================
L2 — SEED 46
====================================================================================================
eMBB   | known  | 5 families
eMBB   | unseen | 4 families
URLLC  | known  | 5 families
URLLC  | unseen | 4 families
mMTC   | known  | 5 families
mMTC   | unseen | 4 families

AUDIT:
{'seed': 46, 'eligible_n': 2095, 'train_n': 1403, 'test_n': 692, 'train_families': 18, 'test_families': 9, 'phrase_overlap': 0, 'family_overlap': 0, 'train_eMBB': 451, 'train_URLLC': 473, 'train_mMTC': 479, 'test_eMBB': 247, 'test_URLLC': 219, 'test_mMTC': 226, 'test_nonambiguous': 469, 'test_ambiguous': 223, 'train_lexical_rows': 705, 'test_lexical_rows': 454, 'train_sha256': '24f3011f73743cb902881982725ae531909d999cacbd2c6d203dd741f5af6ad9', 'test_sha256': '1b145247c6ab1293cec91e15c558c10bfd3ab0265e8d29faa3b76e1593440406'}

==============================================================================================================
FINAL L2 PHRASE-FAMILY-HELD-OUT AUDIT
==============================================================================================================

,seed,eligible_n,train_n,test_n,train_families,test_families,phrase_overlap,family_overlap,train_eMBB,train_URLLC,train_mMTC,test_eMBB,test_URLLC,test_mMTC,test_nonambiguous,test_ambiguous,train_lexical_rows,test_lexical_rows,train_sha256,test_sha256
0,42,2057,1393,664,18,9,0,0,441,477,475,231,227,206,468,196,728,465,3818c92417123f4832a5a94fba203b6bb7ea27d4197009...,e35d899bf26522d377532e36d3a56426467c3ecce33f06...
1,43,2078,1376,702,18,9,0,0,467,444,465,238,225,239,476,226,708,474,0b4bb6e6704a0a2eb953a7f39f48ec10587fed089c79ad...,a33b14b7276ba6ee681d678e7fcbafc897d2093a76d4f6...
2,44,2101,1368,733,18,9,0,0,464,455,449,233,243,257,484,249,726,492,6e8680bc50d5d910797722c6cbc241c3649dfe7284b800...,f2de72d19c59073e984f1bbf83fc4e4b37062122d0f7f9...
3,45,2092,1392,700,18,9,0,0,467,462,463,219,229,252,468,232,730,479,eff81f92576df1917cc3317bdaa2e203f6433789b56ad4...,5eb319550e5ca5644cf085b700919433f77d0a124f2185...
4,46,2095,1403,692,18,9,0,0,451,473,479,247,219,226,469,223,705,454,24f3011f73743cb902881982725ae531909d999cacbd2c...,1b145247c6ab1293cec91e15c558c10bfd3ab0265e8d29...

Saved:
/content/revision_experiments/R1_phrase_generalization/audit/final_L2_phrase_family_audit.csv

==============================================================================================================
FINAL L2 PHRASE-FAMILY-HELD-OUT CONSTRUCTION: PASS
==============================================================================================================

In [61]:
# ================================================================
# STEP 26 — R1 SEED-42 FOUR-CONDITION TRAINING SMOKE TEST
# ================================================================

from pathlib import Path
import pandas as pd
import numpy as np
import json
import time

from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_recall_fscore_support,
    confusion_matrix,
)

SEED = 42

R1_RESULTS = R1 / "results" / f"seed_{SEED}"
R1_RESULTS.mkdir(parents=True, exist_ok=True)

# Make frozen model constructors deterministic for this seed.
xc.SEED = SEED
e1.SEED = SEED

xc.split.__globals__["SEED"] = SEED


# ================================================================
# HELPER — TRAIN / SELECT / EVALUATE
# ================================================================

def run_r1_condition(
    condition,
    train_df,
    test_df,
):

    print("\n" + "=" * 100)
    print(condition)
    print("=" * 100)

    # ------------------------------------------------------------
    # Build features from R1 text
    # ------------------------------------------------------------

    tr = train_df.copy()
    te = test_df.copy()

    tr["text"] = tr["r1_text"]
    te["text"] = te["r1_text"]

    Xtr_raw = xc.build_features(tr)
    Xte_raw = xc.build_features(te)

    label_map = {
        name: i
        for i, name in enumerate(xc.SLICES)
    }

    ytr = (
        train_df["slice"]
        .map(label_map)
        .to_numpy()
    )

    yte = (
        test_df["slice"]
        .map(label_map)
        .to_numpy()
    )

    # ------------------------------------------------------------
    # TRAINING-ONLY MEDIAN IMPUTATION
    # ------------------------------------------------------------

    med = Xtr_raw.median(
        numeric_only=True
    )

    Xtr = Xtr_raw.fillna(med)
    Xte = Xte_raw.fillna(med)

    # ------------------------------------------------------------
    # EXACT TRAINING-ONLY CV MODEL SELECTION
    # ------------------------------------------------------------

    skf = StratifiedKFold(
        n_splits=5,
        shuffle=True,
        random_state=SEED
    )

    cv_rows = []

    models = e1.build_models()

    for name, model in models.items():

        scores = cross_val_score(
            model,
            Xtr,
            ytr,
            cv=skf,
            scoring="f1_macro",
            n_jobs=1,
        )

        cv_rows.append({
            "model": name,
            "cv_mean": float(
                scores.mean()
            ),
            "cv_std": float(
                scores.std()
            ),
        })

    cv_df = (
        pd.DataFrame(cv_rows)
        .sort_values(
            "cv_mean",
            ascending=False
        )
        .reset_index(drop=True)
    )

    best_name = cv_df.iloc[0]["model"]

    print("\nTRAINING-ONLY CV:")
    display(cv_df)

    print(
        "\nSelected:",
        best_name
    )

    # ------------------------------------------------------------
    # FINAL FIT
    # ------------------------------------------------------------

    best_model = models[best_name]

    t0 = time.perf_counter()

    best_model.fit(
        Xtr,
        ytr
    )

    pred = best_model.predict(
        Xte
    )

    infer_seconds = (
        time.perf_counter() - t0
    )

    # ------------------------------------------------------------
    # CORE METRICS
    # ------------------------------------------------------------

    acc = accuracy_score(
        yte,
        pred
    )

    macro = f1_score(
        yte,
        pred,
        average="macro"
    )

    pr, rc, f1c, sup = (
        precision_recall_fscore_support(
            yte,
            pred,
            labels=[
                0, 1, 2
            ],
            zero_division=0
        )
    )

    cm = confusion_matrix(
        yte,
        pred,
        labels=[
            0, 1, 2
        ]
    )

    # ------------------------------------------------------------
    # AMBIGUITY STRATIFICATION
    # ------------------------------------------------------------

    ambiguity_rows = []

    amb_values = (
        test_df["ambiguous"]
        .to_numpy()
    )

    for amb in [0, 1]:

        mask = (
            amb_values == amb
        )

        if mask.sum() == 0:
            continue

        ambiguity_rows.append({
            "ambiguous": amb,
            "n": int(mask.sum()),
            "accuracy": float(
                accuracy_score(
                    yte[mask],
                    pred[mask]
                )
            ),
            "macro_f1": float(
                f1_score(
                    yte[mask],
                    pred[mask],
                    average="macro"
                )
            ),
        })

    ambiguity_df = pd.DataFrame(
        ambiguity_rows
    )

    # ------------------------------------------------------------
    # PREDICTION EVIDENCE
    # ------------------------------------------------------------

    predictions = pd.DataFrame({
        "id":
            test_df["id"].to_numpy(),

        "condition":
            condition,

        "true_id":
            yte,

        "pred_id":
            pred,

        "true_slice":
            [
                xc.SLICES[i]
                for i in yte
            ],

        "pred_slice":
            [
                xc.SLICES[i]
                for i in pred
            ],

        "ambiguous":
            test_df[
                "ambiguous"
            ].to_numpy(),

        "uc_kind":
            test_df[
                "uc_kind"
            ].to_numpy(),

        "use_case":
            test_df[
                "use_case"
            ].to_numpy(),

        "correct":
            (
                yte == pred
            ).astype(int),
    })

    # ------------------------------------------------------------
    # PER CLASS
    # ------------------------------------------------------------

    per_class = pd.DataFrame({
        "slice": xc.SLICES,
        "precision": pr,
        "recall": rc,
        "f1": f1c,
        "support": sup,
    })

    confusion = pd.DataFrame(
        cm,
        index=[
            f"true_{x}"
            for x in xc.SLICES
        ],
        columns=[
            f"pred_{x}"
            for x in xc.SLICES
        ],
    )

    # ------------------------------------------------------------
    # SAVE
    # ------------------------------------------------------------

    prefix = (
        condition
        .replace(" ", "_")
        .replace("/", "_")
    )

    cv_df.to_csv(
        R1_RESULTS /
        f"{prefix}_cv.csv",
        index=False
    )

    per_class.to_csv(
        R1_RESULTS /
        f"{prefix}_per_class.csv",
        index=False
    )

    ambiguity_df.to_csv(
        R1_RESULTS /
        f"{prefix}_ambiguity.csv",
        index=False
    )

    predictions.to_csv(
        R1_RESULTS /
        f"{prefix}_predictions.csv",
        index=False
    )

    confusion.to_csv(
        R1_RESULTS /
        f"{prefix}_confusion.csv"
    )

    summary = {
        "seed": SEED,
        "condition": condition,

        "train_n":
            int(len(train_df)),

        "test_n":
            int(len(test_df)),

        "selected_model":
            best_name,

        "selected_cv_mean":
            float(
                cv_df.iloc[0][
                    "cv_mean"
                ]
            ),

        "selected_cv_std":
            float(
                cv_df.iloc[0][
                    "cv_std"
                ]
            ),

        "accuracy":
            float(acc),

        "macro_f1":
            float(macro),

        "test_nonambiguous_n":
            int(
                (
                    test_df[
                        "ambiguous"
                    ] == 0
                ).sum()
            ),

        "test_ambiguous_n":
            int(
                (
                    test_df[
                        "ambiguous"
                    ] == 1
                ).sum()
            ),

        "fit_plus_predict_seconds":
            float(
                infer_seconds
            ),
    }

    with open(
        R1_RESULTS /
        f"{prefix}_summary.json",
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            summary,
            f,
            indent=2
        )

    print("\nSUMMARY:")
    print(json.dumps(
        summary,
        indent=2
    ))

    print("\nPER CLASS:")
    display(per_class)

    print("\nAMBIGUITY:")
    display(ambiguity_df)

    print("\nCONFUSION:")
    display(confusion)

    return summary


# ================================================================
# LOAD SEED-42 L1/L3/L4
# ================================================================

conditions = {}

for condition in [
    "L1_original",
    "L3_generic_kpi",
    "L4_kpi_only",
]:

    df = pd.read_csv(
        FINAL_COND /
        condition /
        f"seed_{SEED}.csv"
    )

    # EXACT frozen E1 70/30 split
    #
    # We use xc.split only to recover the exact row partition.
    # Feature matrices returned here are not reused.
    tmp = df.copy()
    tmp["text"] = tmp["r1_text"]

    Xtmp = xc.build_features(tmp)

    label_map = {
        name: i
        for i, name in enumerate(xc.SLICES)
    }

    ytmp = (
        df["slice"]
        .map(label_map)
        .to_numpy()
    )

    _, _, _, _, dtr, dte = xc.split(
        Xtmp,
        ytmp,
        df
    )

    conditions[condition] = (
        dtr.copy(),
        dte.copy()
    )


# ================================================================
# LOAD L2 PRECOMPUTED FAMILY SPLIT
# ================================================================

l2_train = pd.read_csv(
    L2_DIR /
    f"seed_{SEED}_train.csv"
)

l2_test = pd.read_csv(
    L2_DIR /
    f"seed_{SEED}_test.csv"
)

conditions[
    "L2_phrase_family_heldout"
] = (
    l2_train,
    l2_test
)


# ================================================================
# RUN FOUR CONDITIONS
# ================================================================

seed42_summaries = []

for condition in [
    "L1_original",
    "L2_phrase_family_heldout",
    "L3_generic_kpi",
    "L4_kpi_only",
]:

    tr, te = conditions[
        condition
    ]

    result = run_r1_condition(
        condition,
        tr,
        te
    )

    seed42_summaries.append(
        result
    )


# ================================================================
# COMPARISON
# ================================================================

seed42_comparison = pd.DataFrame(
    seed42_summaries
)

seed42_comparison.to_csv(
    R1_RESULTS /
    "seed42_condition_comparison.csv",
    index=False
)

print("\n" + "=" * 110)
print("R1 SEED-42 FOUR-CONDITION COMPARISON")
print("=" * 110)

display(
    seed42_comparison[
        [
            "condition",
            "train_n",
            "test_n",
            "selected_model",
            "selected_cv_mean",
            "accuracy",
            "macro_f1",
            "test_nonambiguous_n",
            "test_ambiguous_n",
        ]
    ]
)

print("\nSaved:")
print(
    R1_RESULTS /
    "seed42_condition_comparison.csv"
)

print("\n" + "=" * 110)
print("R1 SEED-42 FOUR-CONDITION SMOKE TEST: COMPLETE")
print("=" * 110)

====================================================================================================
L1_original
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0    Gradient Boosting  0.934708  0.008039
1        Random Forest  0.924233  0.006614
2          MLP (64,32)  0.918989  0.006190
3  Logistic Regression  0.911833  0.012865
4        Decision Tree  0.910321  0.008895

Selected: Gradient Boosting

SUMMARY:
{
  "seed": 42,
  "condition": "L1_original",
  "train_n": 2100,
  "test_n": 900,
  "selected_model": "Gradient Boosting",
  "selected_cv_mean": 0.9347078205163128,
  "selected_cv_std": 0.008039312553058743,
  "accuracy": 0.9277777777777778,
  "macro_f1": 0.9278323905230472,
  "test_nonambiguous_n": 649,
  "test_ambiguous_n": 251,
  "fit_plus_predict_seconds": 2.0625434170005974
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.905844  0.930000  0.917763      300
1  URLLC   0.954545  0.910000  0.931741      300
2   mMTC   0.924837  0.943333  0.933993      300

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  649  0.986133  0.986155
1          1  251  0.776892  0.777008

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         279           8         13
true_URLLC         17         273         10
true_mMTC          12           5        283

====================================================================================================
L2_phrase_family_heldout
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0    Gradient Boosting  0.942967  0.014499
1        Random Forest  0.931396  0.018682
2        Decision Tree  0.928027  0.017903
3          MLP (64,32)  0.927778  0.014330
4  Logistic Regression  0.916913  0.009573

Selected: Gradient Boosting

SUMMARY:
{
  "seed": 42,
  "condition": "L2_phrase_family_heldout",
  "train_n": 1393,
  "test_n": 664,
  "selected_model": "Gradient Boosting",
  "selected_cv_mean": 0.9429671309454732,
  "selected_cv_std": 0.014498735330417453,
  "accuracy": 0.963855421686747,
  "macro_f1": 0.9640580680867656,
  "test_nonambiguous_n": 468,
  "test_ambiguous_n": 196,
  "fit_plus_predict_seconds": 1.5424538090001079
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.969298  0.956710  0.962963      231
1  URLLC   0.960177  0.955947  0.958057      227
2   mMTC   0.961905  0.980583  0.971154      206

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  468  0.991453  0.991580
1          1  196  0.897959  0.898845

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         221           7          3
true_URLLC          5         217          5
true_mMTC           2           2        202

====================================================================================================
L3_generic_kpi
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0    Gradient Boosting  0.892356  0.006665
1        Random Forest  0.881305  0.007454
2        Decision Tree  0.874251  0.011055
3          MLP (64,32)  0.867068  0.006007
4  Logistic Regression  0.855659  0.015939

Selected: Gradient Boosting

SUMMARY:
{
  "seed": 42,
  "condition": "L3_generic_kpi",
  "train_n": 2100,
  "test_n": 900,
  "selected_model": "Gradient Boosting",
  "selected_cv_mean": 0.8923564517851827,
  "selected_cv_std": 0.006665427243559698,
  "accuracy": 0.8966666666666666,
  "macro_f1": 0.896663330330631,
  "test_nonambiguous_n": 649,
  "test_ambiguous_n": 251,
  "fit_plus_predict_seconds": 2.4003140499999063
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.858491  0.910000  0.883495      300
1  URLLC   0.911348  0.856667  0.883162      300
2   mMTC   0.923333  0.923333  0.923333      300

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  649  0.984592  0.984653
1          1  251  0.669323  0.668369

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         273          16         11
true_URLLC         31         257         12
true_mMTC          14           9        277

====================================================================================================
L4_kpi_only
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0    Gradient Boosting  0.892356  0.006665
1        Random Forest  0.881305  0.007454
2        Decision Tree  0.874251  0.011055
3          MLP (64,32)  0.867068  0.006007
4  Logistic Regression  0.855659  0.015939

Selected: Gradient Boosting

SUMMARY:
{
  "seed": 42,
  "condition": "L4_kpi_only",
  "train_n": 2100,
  "test_n": 900,
  "selected_model": "Gradient Boosting",
  "selected_cv_mean": 0.8923564517851827,
  "selected_cv_std": 0.006665427243559698,
  "accuracy": 0.8966666666666666,
  "macro_f1": 0.896663330330631,
  "test_nonambiguous_n": 649,
  "test_ambiguous_n": 251,
  "fit_plus_predict_seconds": 2.71138440499999
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.858491  0.910000  0.883495      300
1  URLLC   0.911348  0.856667  0.883162      300
2   mMTC   0.923333  0.923333  0.923333      300

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  649  0.984592  0.984653
1          1  251  0.669323  0.668369

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         273          16         11
true_URLLC         31         257         12
true_mMTC          14           9        277

==============================================================================================================
R1 SEED-42 FOUR-CONDITION COMPARISON
==============================================================================================================

,condition,train_n,test_n,selected_model,selected_cv_mean,accuracy,macro_f1,test_nonambiguous_n,test_ambiguous_n
0,L1_original,2100,900,Gradient Boosting,0.934708,0.927778,0.927832,649,251
1,L2_phrase_family_heldout,1393,664,Gradient Boosting,0.942967,0.963855,0.964058,468,196
2,L3_generic_kpi,2100,900,Gradient Boosting,0.892356,0.896667,0.896663,649,251
3,L4_kpi_only,2100,900,Gradient Boosting,0.892356,0.896667,0.896663,649,251

Saved:
/content/revision_experiments/R1_phrase_generalization/results/seed_42/seed42_condition_comparison.csv

==============================================================================================================
R1 SEED-42 FOUR-CONDITION SMOKE TEST: COMPLETE
==============================================================================================================

In [62]:
# ================================================================
# STEP 27 — R1 FULL RUN: SEEDS 43–46 × FOUR CONDITIONS
# ================================================================

from pathlib import Path
import pandas as pd
import numpy as np

REMAINING_SEEDS = [43, 44, 45, 46]

all_new_summaries = []


for seed in REMAINING_SEEDS:

    print("\n\n" + "#" * 110)
    print(f"R1 FULL RUN — SEED {seed}")
    print("#" * 110)

    # ------------------------------------------------------------
    # IMPORTANT:
    # Update the global seed used by our runner and frozen models.
    # ------------------------------------------------------------

    SEED = seed

    xc.SEED = seed
    e1.SEED = seed

    xc.split.__globals__["SEED"] = seed

    # ------------------------------------------------------------
    # Output directory
    # ------------------------------------------------------------

    R1_RESULTS = (
        R1 /
        "results" /
        f"seed_{seed}"
    )

    R1_RESULTS.mkdir(
        parents=True,
        exist_ok=True
    )

    conditions = {}

    # ============================================================
    # L1 / L3 / L4
    # ============================================================

    for condition in [
        "L1_original",
        "L3_generic_kpi",
        "L4_kpi_only",
    ]:

        df = pd.read_csv(
            FINAL_COND /
            condition /
            f"seed_{seed}.csv"
        )

        tmp = df.copy()
        tmp["text"] = tmp["r1_text"]

        Xtmp = xc.build_features(tmp)

        label_map = {
            name: i
            for i, name
            in enumerate(xc.SLICES)
        }

        ytmp = (
            df["slice"]
            .map(label_map)
            .to_numpy()
        )

        # Exact frozen E1-style 70/30 split
        _, _, _, _, dtr, dte = (
            xc.split(
                Xtmp,
                ytmp,
                df
            )
        )

        conditions[
            condition
        ] = (
            dtr.copy(),
            dte.copy()
        )

    # ============================================================
    # L2 PRECOMPUTED STRICT FAMILY SPLIT
    # ============================================================

    l2_train = pd.read_csv(
        L2_DIR /
        f"seed_{seed}_train.csv"
    )

    l2_test = pd.read_csv(
        L2_DIR /
        f"seed_{seed}_test.csv"
    )

    conditions[
        "L2_phrase_family_heldout"
    ] = (
        l2_train,
        l2_test
    )

    # ============================================================
    # RUN ALL FOUR CONDITIONS
    # ============================================================

    seed_summaries = []

    for condition in [
        "L1_original",
        "L2_phrase_family_heldout",
        "L3_generic_kpi",
        "L4_kpi_only",
    ]:

        tr, te = conditions[
            condition
        ]

        result = run_r1_condition(
            condition,
            tr,
            te
        )

        seed_summaries.append(
            result
        )

        all_new_summaries.append(
            result
        )

    # ============================================================
    # SEED-LEVEL COMPARISON
    # ============================================================

    seed_comparison = pd.DataFrame(
        seed_summaries
    )

    comparison_path = (
        R1_RESULTS /
        f"seed{seed}_condition_comparison.csv"
    )

    seed_comparison.to_csv(
        comparison_path,
        index=False
    )

    print("\n" + "=" * 110)
    print(
        f"R1 SEED-{seed} "
        "FOUR-CONDITION COMPARISON"
    )
    print("=" * 110)

    display(
        seed_comparison[
            [
                "condition",
                "train_n",
                "test_n",
                "selected_model",
                "selected_cv_mean",
                "accuracy",
                "macro_f1",
                "test_nonambiguous_n",
                "test_ambiguous_n",
            ]
        ]
    )

    # ------------------------------------------------------------
    # HARD SANITY GATE:
    # L3 and L4 MUST be identical
    # ------------------------------------------------------------

    s3 = seed_comparison[
        seed_comparison[
            "condition"
        ] == "L3_generic_kpi"
    ].iloc[0]

    s4 = seed_comparison[
        seed_comparison[
            "condition"
        ] == "L4_kpi_only"
    ].iloc[0]

    assert (
        s3["selected_model"]
        == s4["selected_model"]
    )

    assert np.isclose(
        s3["selected_cv_mean"],
        s4["selected_cv_mean"],
        rtol=0,
        atol=1e-12
    )

    assert np.isclose(
        s3["accuracy"],
        s4["accuracy"],
        rtol=0,
        atol=1e-12
    )

    assert np.isclose(
        s3["macro_f1"],
        s4["macro_f1"],
        rtol=0,
        atol=1e-12
    )

    print(
        f"\nSEED {seed}: "
        "L3/L4 equivalence gate PASS"
    )


# ================================================================
# FINAL DISPLAY — SEEDS 43–46
# ================================================================

remaining_results = pd.DataFrame(
    all_new_summaries
)

print("\n\n" + "=" * 120)
print("R1 REMAINING-SEED RESULTS — 43 TO 46")
print("=" * 120)

display(
    remaining_results[
        [
            "seed",
            "condition",
            "train_n",
            "test_n",
            "selected_model",
            "selected_cv_mean",
            "accuracy",
            "macro_f1",
        ]
    ]
)

print("\n" + "=" * 120)
print(
    "R1 SEEDS 43–46 TRAINING: COMPLETE"
)
print("=" * 120)

##############################################################################################################
R1 FULL RUN — SEED 43
##############################################################################################################

====================================================================================================
L1_original
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0    Gradient Boosting  0.939478  0.008626
1        Random Forest  0.937581  0.013386
2        Decision Tree  0.926728  0.011171
3          MLP (64,32)  0.919059  0.014795
4  Logistic Regression  0.904361  0.014334

Selected: Gradient Boosting

SUMMARY:
{
  "seed": 43,
  "condition": "L1_original",
  "train_n": 2100,
  "test_n": 900,
  "selected_model": "Gradient Boosting",
  "selected_cv_mean": 0.9394780320675473,
  "selected_cv_std": 0.00862597778671555,
  "accuracy": 0.93,
  "macro_f1": 0.9300814152569492,
  "test_nonambiguous_n": 620,
  "test_ambiguous_n": 280,
  "fit_plus_predict_seconds": 2.6585470899999564
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.905229  0.923333  0.914191      300
1  URLLC   0.968085  0.910000  0.938144      300
2   mMTC   0.919872  0.956667  0.937908      300

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  620   0.98871  0.988703
1          1  280   0.80000  0.800632

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         277           7         16
true_URLLC         18         273          9
true_mMTC          11           2        287

====================================================================================================
L2_phrase_family_heldout
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0    Gradient Boosting  0.938471  0.011839
1        Random Forest  0.931828  0.015465
2        Decision Tree  0.928146  0.006596
3          MLP (64,32)  0.920857  0.020475
4  Logistic Regression  0.914299  0.015214

Selected: Gradient Boosting

SUMMARY:
{
  "seed": 43,
  "condition": "L2_phrase_family_heldout",
  "train_n": 1376,
  "test_n": 702,
  "selected_model": "Gradient Boosting",
  "selected_cv_mean": 0.9384705667573046,
  "selected_cv_std": 0.011839368303013971,
  "accuracy": 0.9558404558404558,
  "macro_f1": 0.9558859924104933,
  "test_nonambiguous_n": 476,
  "test_ambiguous_n": 226,
  "fit_plus_predict_seconds": 1.5067497879999792
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.939024  0.970588  0.954545      238
1  URLLC   0.948052  0.973333  0.960526      225
2   mMTC   0.982222  0.924686  0.952586      239

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  476  0.985294  0.985133
1          1  226  0.893805  0.891619

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         231           4          3
true_URLLC          5         219          1
true_mMTC          10           8        221

====================================================================================================
L3_generic_kpi
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0    Gradient Boosting  0.892747  0.019527
1        Random Forest  0.887615  0.018626
2        Decision Tree  0.878840  0.015402
3          MLP (64,32)  0.866284  0.016921
4  Logistic Regression  0.848910  0.015518

Selected: Gradient Boosting

SUMMARY:
{
  "seed": 43,
  "condition": "L3_generic_kpi",
  "train_n": 2100,
  "test_n": 900,
  "selected_model": "Gradient Boosting",
  "selected_cv_mean": 0.8927467500480688,
  "selected_cv_std": 0.01952747481169874,
  "accuracy": 0.8822222222222222,
  "macro_f1": 0.8825797974245924,
  "test_nonambiguous_n": 620,
  "test_ambiguous_n": 280,
  "fit_plus_predict_seconds": 2.057690904000083
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.823529  0.886667  0.853933      300
1  URLLC   0.927007  0.846667  0.885017      300
2   mMTC   0.904290  0.913333  0.908789      300

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  620  0.975806  0.975812
1          1  280  0.675000  0.676042

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         266          15         19
true_URLLC         36         254         10
true_mMTC          21           5        274

====================================================================================================
L4_kpi_only
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0    Gradient Boosting  0.892747  0.019527
1        Random Forest  0.887615  0.018626
2        Decision Tree  0.878840  0.015402
3          MLP (64,32)  0.866284  0.016921
4  Logistic Regression  0.848910  0.015518

Selected: Gradient Boosting

SUMMARY:
{
  "seed": 43,
  "condition": "L4_kpi_only",
  "train_n": 2100,
  "test_n": 900,
  "selected_model": "Gradient Boosting",
  "selected_cv_mean": 0.8927467500480688,
  "selected_cv_std": 0.01952747481169874,
  "accuracy": 0.8822222222222222,
  "macro_f1": 0.8825797974245924,
  "test_nonambiguous_n": 620,
  "test_ambiguous_n": 280,
  "fit_plus_predict_seconds": 2.069924729000377
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.823529  0.886667  0.853933      300
1  URLLC   0.927007  0.846667  0.885017      300
2   mMTC   0.904290  0.913333  0.908789      300

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  620  0.975806  0.975812
1          1  280  0.675000  0.676042

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         266          15         19
true_URLLC         36         254         10
true_mMTC          21           5        274

==============================================================================================================
R1 SEED-43 FOUR-CONDITION COMPARISON
==============================================================================================================

,condition,train_n,test_n,selected_model,selected_cv_mean,accuracy,macro_f1,test_nonambiguous_n,test_ambiguous_n
0,L1_original,2100,900,Gradient Boosting,0.939478,0.930000,0.930081,620,280
1,L2_phrase_family_heldout,1376,702,Gradient Boosting,0.938471,0.955840,0.955886,476,226
2,L3_generic_kpi,2100,900,Gradient Boosting,0.892747,0.882222,0.882580,620,280
3,L4_kpi_only,2100,900,Gradient Boosting,0.892747,0.882222,0.882580,620,280

SEED 43: L3/L4 equivalence gate PASS


##############################################################################################################
R1 FULL RUN — SEED 44
##############################################################################################################

====================================================================================================
L1_original
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0    Gradient Boosting  0.929983  0.014746
1        Random Forest  0.919459  0.006413
2        Decision Tree  0.913979  0.005110
3  Logistic Regression  0.907766  0.012093
4          MLP (64,32)  0.907611  0.016641

Selected: Gradient Boosting

SUMMARY:
{
  "seed": 44,
  "condition": "L1_original",
  "train_n": 2100,
  "test_n": 900,
  "selected_model": "Gradient Boosting",
  "selected_cv_mean": 0.9299825127411816,
  "selected_cv_std": 0.01474587380926117,
  "accuracy": 0.9422222222222222,
  "macro_f1": 0.942291629377722,
  "test_nonambiguous_n": 639,
  "test_ambiguous_n": 261,
  "fit_plus_predict_seconds": 2.058824409999943
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.921053  0.933333  0.927152      300
1  URLLC   0.965753  0.940000  0.952703      300
2   mMTC   0.940789  0.953333  0.947020      300

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  639  0.989045  0.988929
1          1  261  0.827586  0.828233

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         280           6         14
true_URLLC         14         282          4
true_mMTC          10           4        286

====================================================================================================
L2_phrase_family_heldout
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0    Gradient Boosting  0.937150  0.010971
1        Random Forest  0.929094  0.007211
2  Logistic Regression  0.925705  0.013401
3        Decision Tree  0.924546  0.008892
4          MLP (64,32)  0.918254  0.011081

Selected: Gradient Boosting

SUMMARY:
{
  "seed": 44,
  "condition": "L2_phrase_family_heldout",
  "train_n": 1368,
  "test_n": 733,
  "selected_model": "Gradient Boosting",
  "selected_cv_mean": 0.937149590752559,
  "selected_cv_std": 0.01097128260661996,
  "accuracy": 0.946793997271487,
  "macro_f1": 0.9466578930847668,
  "test_nonambiguous_n": 484,
  "test_ambiguous_n": 249,
  "fit_plus_predict_seconds": 1.475426164000055
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.925311  0.957082  0.940928      233
1  URLLC   0.965812  0.930041  0.947589      243
2   mMTC   0.949612  0.953307  0.951456      257

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  484  0.991736  0.991668
1          1  249  0.859438  0.858515

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         223           3          7
true_URLLC         11         226          6
true_mMTC           7           5        245

====================================================================================================
L3_generic_kpi
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0        Random Forest  0.886946  0.009592
1    Gradient Boosting  0.885070  0.011657
2        Decision Tree  0.879624  0.016859
3          MLP (64,32)  0.867977  0.013962
4  Logistic Regression  0.858761  0.016514

Selected: Random Forest

SUMMARY:
{
  "seed": 44,
  "condition": "L3_generic_kpi",
  "train_n": 2100,
  "test_n": 900,
  "selected_model": "Random Forest",
  "selected_cv_mean": 0.8869458448140305,
  "selected_cv_std": 0.009592234239587412,
  "accuracy": 0.8988888888888888,
  "macro_f1": 0.8985085193534017,
  "test_nonambiguous_n": 639,
  "test_ambiguous_n": 261,
  "fit_plus_predict_seconds": 1.310548708999704
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.885417  0.850000  0.867347      300
1  URLLC   0.909396  0.903333  0.906355      300
2   mMTC   0.901274  0.943333  0.921824      300

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  639  0.982786  0.982599
1          1  261  0.693487  0.689459

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         255          23         22
true_URLLC         20         271          9
true_mMTC          13           4        283

====================================================================================================
L4_kpi_only
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0        Random Forest  0.886946  0.009592
1    Gradient Boosting  0.885070  0.011657
2        Decision Tree  0.879624  0.016859
3          MLP (64,32)  0.867977  0.013962
4  Logistic Regression  0.858761  0.016514

Selected: Random Forest

SUMMARY:
{
  "seed": 44,
  "condition": "L4_kpi_only",
  "train_n": 2100,
  "test_n": 900,
  "selected_model": "Random Forest",
  "selected_cv_mean": 0.8869458448140305,
  "selected_cv_std": 0.009592234239587412,
  "accuracy": 0.8988888888888888,
  "macro_f1": 0.8985085193534017,
  "test_nonambiguous_n": 639,
  "test_ambiguous_n": 261,
  "fit_plus_predict_seconds": 1.3138456500000757
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.885417  0.850000  0.867347      300
1  URLLC   0.909396  0.903333  0.906355      300
2   mMTC   0.901274  0.943333  0.921824      300

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  639  0.982786  0.982599
1          1  261  0.693487  0.689459

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         255          23         22
true_URLLC         20         271          9
true_mMTC          13           4        283

==============================================================================================================
R1 SEED-44 FOUR-CONDITION COMPARISON
==============================================================================================================

,condition,train_n,test_n,selected_model,selected_cv_mean,accuracy,macro_f1,test_nonambiguous_n,test_ambiguous_n
0,L1_original,2100,900,Gradient Boosting,0.929983,0.942222,0.942292,639,261
1,L2_phrase_family_heldout,1368,733,Gradient Boosting,0.937150,0.946794,0.946658,484,249
2,L3_generic_kpi,2100,900,Random Forest,0.886946,0.898889,0.898509,639,261
3,L4_kpi_only,2100,900,Random Forest,0.886946,0.898889,0.898509,639,261

SEED 44: L3/L4 equivalence gate PASS


##############################################################################################################
R1 FULL RUN — SEED 45
##############################################################################################################

====================================================================================================
L1_original
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0    Gradient Boosting  0.930891  0.011076
1        Random Forest  0.926592  0.009822
2          MLP (64,32)  0.913217  0.014510
3  Logistic Regression  0.907496  0.008013
4        Decision Tree  0.907344  0.013947

Selected: Gradient Boosting

SUMMARY:
{
  "seed": 45,
  "condition": "L1_original",
  "train_n": 2100,
  "test_n": 900,
  "selected_model": "Gradient Boosting",
  "selected_cv_mean": 0.9308914685223437,
  "selected_cv_std": 0.011076167282806196,
  "accuracy": 0.93,
  "macro_f1": 0.9297723922693569,
  "test_nonambiguous_n": 614,
  "test_ambiguous_n": 286,
  "fit_plus_predict_seconds": 2.0519397449997996
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.894569  0.933333  0.913540      300
1  URLLC   0.960000  0.880000  0.918261      300
2   mMTC   0.939103  0.976667  0.957516      300

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  614  0.983713  0.983679
1          1  286  0.814685  0.806561

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         280           9         11
true_URLLC         28         264          8
true_mMTC           5           2        293

====================================================================================================
L2_phrase_family_heldout
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0        Random Forest  0.943129  0.010456
1    Gradient Boosting  0.942537  0.013189
2        Decision Tree  0.927464  0.016960
3          MLP (64,32)  0.925855  0.006537
4  Logistic Regression  0.917325  0.014803

Selected: Random Forest

SUMMARY:
{
  "seed": 45,
  "condition": "L2_phrase_family_heldout",
  "train_n": 1392,
  "test_n": 700,
  "selected_model": "Random Forest",
  "selected_cv_mean": 0.9431286635977847,
  "selected_cv_std": 0.010456258008279097,
  "accuracy": 0.9614285714285714,
  "macro_f1": 0.9609493911719938,
  "test_nonambiguous_n": 468,
  "test_ambiguous_n": 232,
  "fit_plus_predict_seconds": 1.0201010829996449
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.945946  0.958904  0.952381      219
1  URLLC   0.981735  0.938865  0.959821      229
2   mMTC   0.957529  0.984127  0.970646      252

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  468  0.989316  0.989055
1          1  232  0.905172  0.904449

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         210           3          6
true_URLLC          9         215          5
true_mMTC           3           1        248

====================================================================================================
L3_generic_kpi
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0    Gradient Boosting  0.890598  0.012298
1        Random Forest  0.879460  0.009363
2          MLP (64,32)  0.871711  0.021281
3        Decision Tree  0.867147  0.017631
4  Logistic Regression  0.848332  0.009799

Selected: Gradient Boosting

SUMMARY:
{
  "seed": 45,
  "condition": "L3_generic_kpi",
  "train_n": 2100,
  "test_n": 900,
  "selected_model": "Gradient Boosting",
  "selected_cv_mean": 0.8905977899609254,
  "selected_cv_std": 0.012297671348453379,
  "accuracy": 0.8844444444444445,
  "macro_f1": 0.8843907774651912,
  "test_nonambiguous_n": 614,
  "test_ambiguous_n": 286,
  "fit_plus_predict_seconds": 2.630163476999769
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.845426  0.893333  0.868720      300
1  URLLC   0.919708  0.840000  0.878049      300
2   mMTC   0.893204  0.920000  0.906404      300

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  614  0.980456  0.980423
1          1  286  0.678322  0.669023

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         268          13         19
true_URLLC         34         252         14
true_mMTC          15           9        276

====================================================================================================
L4_kpi_only
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0    Gradient Boosting  0.890598  0.012298
1        Random Forest  0.879460  0.009363
2          MLP (64,32)  0.871711  0.021281
3        Decision Tree  0.867147  0.017631
4  Logistic Regression  0.848332  0.009799

Selected: Gradient Boosting

SUMMARY:
{
  "seed": 45,
  "condition": "L4_kpi_only",
  "train_n": 2100,
  "test_n": 900,
  "selected_model": "Gradient Boosting",
  "selected_cv_mean": 0.8905977899609254,
  "selected_cv_std": 0.012297671348453379,
  "accuracy": 0.8844444444444445,
  "macro_f1": 0.8843907774651912,
  "test_nonambiguous_n": 614,
  "test_ambiguous_n": 286,
  "fit_plus_predict_seconds": 2.5583329880000747
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.845426  0.893333  0.868720      300
1  URLLC   0.919708  0.840000  0.878049      300
2   mMTC   0.893204  0.920000  0.906404      300

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  614  0.980456  0.980423
1          1  286  0.678322  0.669023

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         268          13         19
true_URLLC         34         252         14
true_mMTC          15           9        276

==============================================================================================================
R1 SEED-45 FOUR-CONDITION COMPARISON
==============================================================================================================

,condition,train_n,test_n,selected_model,selected_cv_mean,accuracy,macro_f1,test_nonambiguous_n,test_ambiguous_n
0,L1_original,2100,900,Gradient Boosting,0.930891,0.930000,0.929772,614,286
1,L2_phrase_family_heldout,1392,700,Random Forest,0.943129,0.961429,0.960949,468,232
2,L3_generic_kpi,2100,900,Gradient Boosting,0.890598,0.884444,0.884391,614,286
3,L4_kpi_only,2100,900,Gradient Boosting,0.890598,0.884444,0.884391,614,286

SEED 45: L3/L4 equivalence gate PASS


##############################################################################################################
R1 FULL RUN — SEED 46
##############################################################################################################

====================================================================================================
L1_original
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0        Decision Tree  0.923108  0.015850
1    Gradient Boosting  0.921750  0.015101
2        Random Forest  0.918842  0.015306
3          MLP (64,32)  0.909508  0.021682
4  Logistic Regression  0.906769  0.014250

Selected: Decision Tree

SUMMARY:
{
  "seed": 46,
  "condition": "L1_original",
  "train_n": 2100,
  "test_n": 900,
  "selected_model": "Decision Tree",
  "selected_cv_mean": 0.9231075632083046,
  "selected_cv_std": 0.01584979019335158,
  "accuracy": 0.9255555555555556,
  "macro_f1": 0.9256124393782387,
  "test_nonambiguous_n": 643,
  "test_ambiguous_n": 257,
  "fit_plus_predict_seconds": 0.027959562999967602
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.866071  0.970000  0.915094      300
1  URLLC   0.988506  0.860000  0.919786      300
2   mMTC   0.937294  0.946667  0.941957      300

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  643  0.975117  0.975217
1          1  257  0.801556  0.799871

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         291           2          7
true_URLLC         30         258         12
true_mMTC          15           1        284

====================================================================================================
L2_phrase_family_heldout
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0    Gradient Boosting  0.941339  0.003437
1        Random Forest  0.931407  0.008328
2        Decision Tree  0.929308  0.011382
3  Logistic Regression  0.924072  0.009525
4          MLP (64,32)  0.918677  0.012420

Selected: Gradient Boosting

SUMMARY:
{
  "seed": 46,
  "condition": "L2_phrase_family_heldout",
  "train_n": 1403,
  "test_n": 692,
  "selected_model": "Gradient Boosting",
  "selected_cv_mean": 0.9413387506204206,
  "selected_cv_std": 0.003437100235767358,
  "accuracy": 0.9465317919075145,
  "macro_f1": 0.9462672933489592,
  "test_nonambiguous_n": 469,
  "test_ambiguous_n": 223,
  "fit_plus_predict_seconds": 1.5801610320013424
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.958678  0.939271  0.948875      247
1  URLLC   0.966184  0.913242  0.938967      219
2   mMTC   0.917695  0.986726  0.950959      226

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  469  0.991471  0.991619
1          1  223  0.852018  0.849566

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         232           5         10
true_URLLC          9         200         10
true_mMTC           1           2        223

====================================================================================================
L3_generic_kpi
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0    Gradient Boosting  0.879129  0.016916
1        Random Forest  0.862047  0.012563
2          MLP (64,32)  0.857932  0.020562
3        Decision Tree  0.852296  0.011475
4  Logistic Regression  0.838715  0.015867

Selected: Gradient Boosting

SUMMARY:
{
  "seed": 46,
  "condition": "L3_generic_kpi",
  "train_n": 2100,
  "test_n": 900,
  "selected_model": "Gradient Boosting",
  "selected_cv_mean": 0.8791290755839934,
  "selected_cv_std": 0.016916176984445357,
  "accuracy": 0.8977777777777778,
  "macro_f1": 0.8976314813218883,
  "test_nonambiguous_n": 643,
  "test_ambiguous_n": 257,
  "fit_plus_predict_seconds": 2.101949762000004
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.886667  0.886667  0.886667      300
1  URLLC   0.922261  0.870000  0.895369      300
2   mMTC   0.886435  0.936667  0.910859      300

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  643  0.979782  0.979777
1          1  257  0.692607  0.687910

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         266          13         21
true_URLLC         24         261         15
true_mMTC          10           9        281

====================================================================================================
L4_kpi_only
====================================================================================================

TRAINING-ONLY CV:

                 model   cv_mean    cv_std
0    Gradient Boosting  0.879129  0.016916
1        Random Forest  0.862047  0.012563
2          MLP (64,32)  0.857932  0.020562
3        Decision Tree  0.852296  0.011475
4  Logistic Regression  0.838715  0.015867

Selected: Gradient Boosting

SUMMARY:
{
  "seed": 46,
  "condition": "L4_kpi_only",
  "train_n": 2100,
  "test_n": 900,
  "selected_model": "Gradient Boosting",
  "selected_cv_mean": 0.8791290755839934,
  "selected_cv_std": 0.016916176984445357,
  "accuracy": 0.8977777777777778,
  "macro_f1": 0.8976314813218883,
  "test_nonambiguous_n": 643,
  "test_ambiguous_n": 257,
  "fit_plus_predict_seconds": 2.0873579740000423
}

PER CLASS:

   slice  precision    recall        f1  support
0   eMBB   0.886667  0.886667  0.886667      300
1  URLLC   0.922261  0.870000  0.895369      300
2   mMTC   0.886435  0.936667  0.910859      300

AMBIGUITY:

   ambiguous    n  accuracy  macro_f1
0          0  643  0.979782  0.979777
1          1  257  0.692607  0.687910

CONFUSION:

            pred_eMBB  pred_URLLC  pred_mMTC
true_eMBB         266          13         21
true_URLLC         24         261         15
true_mMTC          10           9        281

==============================================================================================================
R1 SEED-46 FOUR-CONDITION COMPARISON
==============================================================================================================

,condition,train_n,test_n,selected_model,selected_cv_mean,accuracy,macro_f1,test_nonambiguous_n,test_ambiguous_n
0,L1_original,2100,900,Decision Tree,0.923108,0.925556,0.925612,643,257
1,L2_phrase_family_heldout,1403,692,Gradient Boosting,0.941339,0.946532,0.946267,469,223
2,L3_generic_kpi,2100,900,Gradient Boosting,0.879129,0.897778,0.897631,643,257
3,L4_kpi_only,2100,900,Gradient Boosting,0.879129,0.897778,0.897631,643,257

SEED 46: L3/L4 equivalence gate PASS


========================================================================================================================
R1 REMAINING-SEED RESULTS — 43 TO 46
========================================================================================================================

,seed,condition,train_n,test_n,selected_model,selected_cv_mean,accuracy,macro_f1
0,43,L1_original,2100,900,Gradient Boosting,0.939478,0.930000,0.930081
1,43,L2_phrase_family_heldout,1376,702,Gradient Boosting,0.938471,0.955840,0.955886
2,43,L3_generic_kpi,2100,900,Gradient Boosting,0.892747,0.882222,0.882580
3,43,L4_kpi_only,2100,900,Gradient Boosting,0.892747,0.882222,0.882580
4,44,L1_original,2100,900,Gradient Boosting,0.929983,0.942222,0.942292
5,44,L2_phrase_family_heldout,1368,733,Gradient Boosting,0.937150,0.946794,0.946658
6,44,L3_generic_kpi,2100,900,Random Forest,0.886946,0.898889,0.898509
7,44,L4_kpi_only,2100,900,Random Forest,0.886946,0.898889,0.898509
8,45,L1_original,2100,900,Gradient Boosting,0.930891,0.930000,0.929772
9,45,L2_phrase_family_heldout,1392,700,Random Forest,0.943129,0.961429,0.960949
10,45,L3_generic_kpi,2100,900,Gradient Boosting,0.890598,0.884444,0.884391
11,45,L4_kpi_only,2100,900,Gradient Boosting,0.890598,0.884444,0.884391
12,46,L1_original,2100,900,Decision Tree,0.923108,0.925556,0.925612
13,46,L2_phrase_family_heldout,1403,692,Gradient Boosting,0.941339,0.946532,0.946267
14,46,L3_generic_kpi,2100,900,Gradient Boosting,0.879129,0.897778,0.897631
15,46,L4_kpi_only,2100,900,Gradient Boosting,0.879129,0.897778,0.897631

========================================================================================================================
R1 SEEDS 43–46 TRAINING: COMPLETE
========================================================================================================================

In [63]:
# ================================================================
# STEP 28 — R1 FINAL FIVE-SEED AGGREGATION
# ================================================================

from pathlib import Path
import pandas as pd
import numpy as np
import json

SEEDS = [42, 43, 44, 45, 46]

AGG_DIR = R1 / "results" / "aggregate"
AGG_DIR.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------
# 1. LOAD ALL FIVE SEED COMPARISON FILES
# ------------------------------------------------------------

frames = []

for seed in SEEDS:

    path = (
        R1 /
        "results" /
        f"seed_{seed}" /
        f"seed{seed}_condition_comparison.csv"
    )

    assert path.exists(), f"Missing: {path}"

    df = pd.read_csv(path)

    assert len(df) == 4, (
        f"Seed {seed}: expected 4 conditions, "
        f"found {len(df)}"
    )

    df["seed"] = seed

    frames.append(df)


all_results = pd.concat(
    frames,
    ignore_index=True
)

# ------------------------------------------------------------
# 2. BASIC HARD GATES
# ------------------------------------------------------------

expected_conditions = {
    "L1_original",
    "L2_phrase_family_heldout",
    "L3_generic_kpi",
    "L4_kpi_only",
}

assert set(all_results["condition"]) == expected_conditions

for seed in SEEDS:

    sdf = all_results[
        all_results["seed"] == seed
    ]

    assert len(sdf) == 4

    assert set(
        sdf["condition"]
    ) == expected_conditions


# ------------------------------------------------------------
# 3. L3/L4 EQUIVALENCE — ALL FIVE SEEDS
# ------------------------------------------------------------

equivalence_rows = []

for seed in SEEDS:

    sdf = all_results[
        all_results["seed"] == seed
    ]

    l3 = sdf[
        sdf["condition"] == "L3_generic_kpi"
    ].iloc[0]

    l4 = sdf[
        sdf["condition"] == "L4_kpi_only"
    ].iloc[0]

    same_model = (
        l3["selected_model"]
        == l4["selected_model"]
    )

    same_cv = np.isclose(
        l3["selected_cv_mean"],
        l4["selected_cv_mean"],
        atol=1e-12,
        rtol=0
    )

    same_acc = np.isclose(
        l3["accuracy"],
        l4["accuracy"],
        atol=1e-12,
        rtol=0
    )

    same_f1 = np.isclose(
        l3["macro_f1"],
        l4["macro_f1"],
        atol=1e-12,
        rtol=0
    )

    passed = (
        same_model
        and same_cv
        and same_acc
        and same_f1
    )

    equivalence_rows.append({
        "seed": seed,
        "same_model": same_model,
        "same_cv": same_cv,
        "same_accuracy": same_acc,
        "same_macro_f1": same_f1,
        "pass": passed,
    })


equivalence = pd.DataFrame(
    equivalence_rows
)

assert equivalence["pass"].all(), (
    "STOP: L3/L4 equivalence failed."
)


# ------------------------------------------------------------
# 4. FIVE-SEED AGGREGATION
# ------------------------------------------------------------

aggregate = (
    all_results
    .groupby(
        "condition",
        sort=False
    )
    .agg(
        n_seeds=("seed", "count"),

        accuracy_mean=("accuracy", "mean"),
        accuracy_std=("accuracy", "std"),

        macro_f1_mean=("macro_f1", "mean"),
        macro_f1_std=("macro_f1", "std"),

        cv_mean=("selected_cv_mean", "mean"),
        cv_across_seed_std=("selected_cv_mean", "std"),

        train_n_mean=("train_n", "mean"),
        test_n_mean=("test_n", "mean"),
    )
    .reset_index()
)

assert (
    aggregate["n_seeds"] == 5
).all()


# ------------------------------------------------------------
# 5. MODEL SELECTION COUNTS
# ------------------------------------------------------------

model_counts = (
    all_results
    .groupby(
        ["condition", "selected_model"]
    )
    .size()
    .reset_index(name="count")
    .sort_values(
        ["condition", "count"],
        ascending=[True, False]
    )
)


# ------------------------------------------------------------
# 6. PAIRED L1 -> L3/L4 DEGRADATION
# ------------------------------------------------------------

wide = all_results.pivot(
    index="seed",
    columns="condition",
    values=[
        "accuracy",
        "macro_f1"
    ]
)

paired_rows = []

for seed in SEEDS:

    l1_acc = wide.loc[
        seed,
        ("accuracy", "L1_original")
    ]

    l3_acc = wide.loc[
        seed,
        ("accuracy", "L3_generic_kpi")
    ]

    l1_f1 = wide.loc[
        seed,
        ("macro_f1", "L1_original")
    ]

    l3_f1 = wide.loc[
        seed,
        ("macro_f1", "L3_generic_kpi")
    ]

    paired_rows.append({
        "seed": seed,

        "L1_accuracy": l1_acc,
        "L3_L4_accuracy": l3_acc,
        "accuracy_drop": l1_acc - l3_acc,

        "L1_macro_f1": l1_f1,
        "L3_L4_macro_f1": l3_f1,
        "macro_f1_drop": l1_f1 - l3_f1,
    })


paired = pd.DataFrame(
    paired_rows
)


paired_summary = pd.DataFrame([{
    "accuracy_drop_mean":
        paired["accuracy_drop"].mean(),

    "accuracy_drop_std":
        paired["accuracy_drop"].std(),

    "macro_f1_drop_mean":
        paired["macro_f1_drop"].mean(),

    "macro_f1_drop_std":
        paired["macro_f1_drop"].std(),
}])


# ------------------------------------------------------------
# 7. L2 DESCRIPTIVE COMPARISON
#
# IMPORTANT:
# This is descriptive only.
# L2 uses a different test population from L1.
# ------------------------------------------------------------

l2_descriptive = []

for seed in SEEDS:

    sdf = all_results[
        all_results["seed"] == seed
    ]

    l1 = sdf[
        sdf["condition"] == "L1_original"
    ].iloc[0]

    l2 = sdf[
        sdf["condition"]
        == "L2_phrase_family_heldout"
    ].iloc[0]

    l2_descriptive.append({
        "seed": seed,

        "L1_accuracy":
            l1["accuracy"],

        "L2_accuracy":
            l2["accuracy"],

        "L2_minus_L1_accuracy":
            l2["accuracy"] - l1["accuracy"],

        "L1_macro_f1":
            l1["macro_f1"],

        "L2_macro_f1":
            l2["macro_f1"],

        "L2_minus_L1_macro_f1":
            l2["macro_f1"] - l1["macro_f1"],

        "L1_test_n":
            l1["test_n"],

        "L2_test_n":
            l2["test_n"],
    })


l2_descriptive = pd.DataFrame(
    l2_descriptive
)


# ------------------------------------------------------------
# 8. SAVE FINAL R1 TABLES
# ------------------------------------------------------------

all_results.to_csv(
    AGG_DIR /
    "r1_all_20_runs.csv",
    index=False
)

aggregate.to_csv(
    AGG_DIR /
    "r1_five_seed_summary.csv",
    index=False
)

model_counts.to_csv(
    AGG_DIR /
    "r1_model_selection_counts.csv",
    index=False
)

equivalence.to_csv(
    AGG_DIR /
    "r1_L3_L4_equivalence.csv",
    index=False
)

paired.to_csv(
    AGG_DIR /
    "r1_L1_vs_L3L4_paired.csv",
    index=False
)

paired_summary.to_csv(
    AGG_DIR /
    "r1_L1_vs_L3L4_summary.csv",
    index=False
)

l2_descriptive.to_csv(
    AGG_DIR /
    "r1_L2_descriptive_comparison.csv",
    index=False
)


# ------------------------------------------------------------
# 9. DISPLAY
# ------------------------------------------------------------

print("\n" + "=" * 120)
print("R1 FINAL FIVE-SEED SUMMARY")
print("=" * 120)

display(
    aggregate[
        [
            "condition",
            "n_seeds",
            "accuracy_mean",
            "accuracy_std",
            "macro_f1_mean",
            "macro_f1_std",
        ]
    ]
)


print("\n" + "=" * 120)
print("MODEL SELECTION COUNTS")
print("=" * 120)

display(model_counts)


print("\n" + "=" * 120)
print("L1 -> L3/L4 PAIRED DEGRADATION")
print("=" * 120)

display(paired)

print("\nMEAN DEGRADATION:")
display(paired_summary)


print("\n" + "=" * 120)
print("L2 DESCRIPTIVE COMPARISON — DO NOT INTERPRET AS PAIRED IMPROVEMENT")
print("=" * 120)

display(l2_descriptive)


print("\n" + "=" * 120)
print("L3/L4 FIVE-SEED EQUIVALENCE")
print("=" * 120)

display(equivalence)


print("\nSaved aggregate evidence to:")
print(AGG_DIR)

print("\n" + "=" * 120)
print("R1 FIVE-SEED AGGREGATION: PASS")
print("=" * 120)

========================================================================================================================
R1 FINAL FIVE-SEED SUMMARY
========================================================================================================================

,condition,n_seeds,accuracy_mean,accuracy_std,macro_f1_mean,macro_f1_std
0,L1_original,5,0.931111,0.006479,0.931118,0.006497
1,L2_phrase_family_heldout,5,0.954890,0.008054,0.954764,0.008121
2,L3_generic_kpi,5,0.892000,0.007989,0.891955,0.007785
3,L4_kpi_only,5,0.892000,0.007989,0.891955,0.007785

========================================================================================================================
MODEL SELECTION COUNTS
========================================================================================================================

                  condition     selected_model  count
1               L1_original  Gradient Boosting      4
0               L1_original      Decision Tree      1
2  L2_phrase_family_heldout  Gradient Boosting      4
3  L2_phrase_family_heldout      Random Forest      1
4            L3_generic_kpi  Gradient Boosting      4
5            L3_generic_kpi      Random Forest      1
6               L4_kpi_only  Gradient Boosting      4
7               L4_kpi_only      Random Forest      1

========================================================================================================================
L1 -> L3/L4 PAIRED DEGRADATION
========================================================================================================================

,seed,L1_accuracy,L3_L4_accuracy,accuracy_drop,L1_macro_f1,L3_L4_macro_f1,macro_f1_drop
0,42,0.927778,0.896667,0.031111,0.927832,0.896663,0.031169
1,43,0.930000,0.882222,0.047778,0.930081,0.882580,0.047502
2,44,0.942222,0.898889,0.043333,0.942292,0.898509,0.043783
3,45,0.930000,0.884444,0.045556,0.929772,0.884391,0.045382
4,46,0.925556,0.897778,0.027778,0.925612,0.897631,0.027981

MEAN DEGRADATION:

,accuracy_drop_mean,accuracy_drop_std,macro_f1_drop_mean,macro_f1_drop_std
0,0.039111,0.00904,0.039163,0.008923

========================================================================================================================
L2 DESCRIPTIVE COMPARISON — DO NOT INTERPRET AS PAIRED IMPROVEMENT
========================================================================================================================

,seed,L1_accuracy,L2_accuracy,L2_minus_L1_accuracy,L1_macro_f1,L2_macro_f1,L2_minus_L1_macro_f1,L1_test_n,L2_test_n
0,42,0.927778,0.963855,0.036078,0.927832,0.964058,0.036226,900,664
1,43,0.930000,0.955840,0.025840,0.930081,0.955886,0.025805,900,702
2,44,0.942222,0.946794,0.004572,0.942292,0.946658,0.004366,900,733
3,45,0.930000,0.961429,0.031429,0.929772,0.960949,0.031177,900,700
4,46,0.925556,0.946532,0.020976,0.925612,0.946267,0.020655,900,692

========================================================================================================================
L3/L4 FIVE-SEED EQUIVALENCE
========================================================================================================================

   seed  same_model  same_cv  same_accuracy  same_macro_f1  pass
0    42        True     True           True           True  True
1    43        True     True           True           True  True
2    44        True     True           True           True  True
3    45        True     True           True           True  True
4    46        True     True           True           True  True

Saved aggregate evidence to:
/content/revision_experiments/R1_phrase_generalization/results/aggregate

========================================================================================================================
R1 FIVE-SEED AGGREGATION: PASS
========================================================================================================================

In [64]:
# ================================================================
# STEP 29 — FREEZE / PACKAGE / CLOSE R1
# ================================================================

from pathlib import Path
import pandas as pd
import numpy as np
import hashlib
import json
from datetime import datetime, timezone

AGG_DIR = R1 / "results" / "aggregate"
CLOSE_DIR = R1 / "final_evidence"
CLOSE_DIR.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------
# 1. LOAD FINAL AGGREGATES
# ------------------------------------------------------------

summary = pd.read_csv(
    AGG_DIR / "r1_five_seed_summary.csv"
)

paired_summary = pd.read_csv(
    AGG_DIR / "r1_L1_vs_L3L4_summary.csv"
)

equivalence = pd.read_csv(
    AGG_DIR / "r1_L3_L4_equivalence.csv"
)

model_counts = pd.read_csv(
    AGG_DIR / "r1_model_selection_counts.csv"
)

all_runs = pd.read_csv(
    AGG_DIR / "r1_all_20_runs.csv"
)

assert len(all_runs) == 20
assert equivalence["pass"].all()

# ------------------------------------------------------------
# 2. PUBLICATION-READY TABLE
# ------------------------------------------------------------

condition_labels = {
    "L1_original":
        "L1 — Original",

    "L2_phrase_family_heldout":
        "L2 — Phrase-family-held-out",

    "L3_generic_kpi":
        "L3 — Generic + KPI",

    "L4_kpi_only":
        "L4 — KPI-only",
}

pub = summary.copy()

pub["Condition"] = pub["condition"].map(
    condition_labels
)

pub["Accuracy (mean ± SD)"] = pub.apply(
    lambda r:
        f'{r["accuracy_mean"]:.4f} ± '
        f'{r["accuracy_std"]:.4f}',
    axis=1
)

pub["Macro-F1 (mean ± SD)"] = pub.apply(
    lambda r:
        f'{r["macro_f1_mean"]:.4f} ± '
        f'{r["macro_f1_std"]:.4f}',
    axis=1
)

publication_table = pub[
    [
        "Condition",
        "n_seeds",
        "Accuracy (mean ± SD)",
        "Macro-F1 (mean ± SD)",
    ]
].rename(
    columns={"n_seeds": "Seeds"}
)

publication_table.to_csv(
    CLOSE_DIR /
    "R1_publication_table.csv",
    index=False
)

# ------------------------------------------------------------
# 3. EXTRACT KEY VALUES
# ------------------------------------------------------------

def row_for(condition):
    return summary[
        summary["condition"] == condition
    ].iloc[0]


l1 = row_for("L1_original")
l2 = row_for("L2_phrase_family_heldout")
l3 = row_for("L3_generic_kpi")
l4 = row_for("L4_kpi_only")

drop = paired_summary.iloc[0]

# ------------------------------------------------------------
# 4. REVIEWER-SAFE FINDINGS
# ------------------------------------------------------------

findings = f"""
R1 — Phrase Generalization and Lexical Ablation
================================================

Experimental design
-------------------
R1 was evaluated across five random seeds:
42, 43, 44, 45, and 46.

Four conditions were evaluated:

L1 — Original:
Original synthetic intent text using the frozen feature pipeline.

L2 — Phrase-family-held-out:
Strict class-specific phrase/use-case family holdout.
Train and test phrase families are disjoint.
Generic use cases are excluded from this condition.

L3 — Generic + KPI:
Use-case semantic phrases are replaced with a neutral
"network service" expression while preserving observable KPI
information.

L4 — KPI-only:
Only KPI information observable to the frozen parser is retained.

Final five-seed results
-----------------------
L1 accuracy:
{l1["accuracy_mean"]:.4f} ± {l1["accuracy_std"]:.4f}

L1 macro-F1:
{l1["macro_f1_mean"]:.4f} ± {l1["macro_f1_std"]:.4f}

L2 accuracy:
{l2["accuracy_mean"]:.4f} ± {l2["accuracy_std"]:.4f}

L2 macro-F1:
{l2["macro_f1_mean"]:.4f} ± {l2["macro_f1_std"]:.4f}

L3 accuracy:
{l3["accuracy_mean"]:.4f} ± {l3["accuracy_std"]:.4f}

L3 macro-F1:
{l3["macro_f1_mean"]:.4f} ± {l3["macro_f1_std"]:.4f}

L4 accuracy:
{l4["accuracy_mean"]:.4f} ± {l4["accuracy_std"]:.4f}

L4 macro-F1:
{l4["macro_f1_mean"]:.4f} ± {l4["macro_f1_std"]:.4f}

Lexical-ablation effect
-----------------------
Mean L1 -> L3/L4 accuracy reduction:
{drop["accuracy_drop_mean"]:.4f} ±
{drop["accuracy_drop_std"]:.4f}

Mean L1 -> L3/L4 macro-F1 reduction:
{drop["macro_f1_drop_mean"]:.4f} ±
{drop["macro_f1_drop_std"]:.4f}

Interpretation
--------------
1. Performance remains strong under strict held-out
   class-specific phrase families.

2. Therefore, the classifier does not exhibit performance
   collapse when evaluated on phrase families excluded from
   training.

3. Removing lexical/use-case information produces a consistent
   performance reduction across all five seeds.

4. Consequently, lexical intent cues provide useful predictive
   information, but classification is not solely dependent on
   lexical phrase memorization.

5. L2 must NOT be described as an improvement over L1.
   L2 uses a different evaluation population because generic
   examples are excluded.

6. L3 and L4 produce identical frozen feature representations
   across all five evaluated corpora. Their identical results are
   therefore an architectural/representation finding rather than
   independent evidence from two distinct model representations.

7. Ambiguous intents require separate interpretation because the
   synthetic ground-truth label is defined before KPI blending.
   KPI-only disagreement on such cases should not automatically be
   interpreted as ordinary classification failure.

Conclusion
----------
R1 provides evidence against the concern that the reported
classifier performance is explained solely by memorization of
class-specific intent phrases.

The experiment also quantifies the contribution of lexical cues:
removing those cues reduces macro-F1 by approximately
{100 * drop["macro_f1_drop_mean"]:.2f} percentage points on average.

Claims should remain limited to the evaluated synthetic corpus,
frozen parser, feature representation, model-selection procedure,
and phrase families used in this experiment.
""".strip()

(CLOSE_DIR / "R1_final_findings.txt").write_text(
    findings,
    encoding="utf-8"
)

# ------------------------------------------------------------
# 5. MACHINE-READABLE CLOSURE RECORD
# ------------------------------------------------------------

closure = {
    "experiment": "R1_phrase_generalization",
    "status": "PASS_CLOSED",

    "seeds": [42, 43, 44, 45, 46],
    "number_of_condition_runs": 20,

    "conditions": [
        "L1_original",
        "L2_phrase_family_heldout",
        "L3_generic_kpi",
        "L4_kpi_only",
    ],

    "L1_macro_f1_mean":
        float(l1["macro_f1_mean"]),

    "L1_macro_f1_std":
        float(l1["macro_f1_std"]),

    "L2_macro_f1_mean":
        float(l2["macro_f1_mean"]),

    "L2_macro_f1_std":
        float(l2["macro_f1_std"]),

    "L3_macro_f1_mean":
        float(l3["macro_f1_mean"]),

    "L3_macro_f1_std":
        float(l3["macro_f1_std"]),

    "L4_macro_f1_mean":
        float(l4["macro_f1_mean"]),

    "L4_macro_f1_std":
        float(l4["macro_f1_std"]),

    "lexical_ablation_macro_f1_drop_mean":
        float(drop["macro_f1_drop_mean"]),

    "lexical_ablation_macro_f1_drop_std":
        float(drop["macro_f1_drop_std"]),

    "L3_L4_equivalence_all_seeds":
        bool(equivalence["pass"].all()),

    "important_interpretation": {
        "L2_is_directly_comparable_to_L1":
            False,

        "L3_L4_are_independent_feature_conditions":
            False,

        "phrase_family_performance_collapse_observed":
            False,

        "lexical_information_contributes":
            True,
    },

    "provenance_note":
        (
            "Current frozen source snapshot is authoritative "
            "for R1. Historical archived E1 metric mismatch "
            "was separately documented and was not forced "
            "into the R1 results."
        ),

    "closed_utc":
        datetime.now(timezone.utc).isoformat(),
}

with open(
    CLOSE_DIR / "R1_closure.json",
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        closure,
        f,
        indent=2
    )

# ------------------------------------------------------------
# 6. CREATE SHA-256 MANIFEST
# ------------------------------------------------------------

def sha256_file(path):
    h = hashlib.sha256()

    with open(path, "rb") as f:
        for block in iter(
            lambda: f.read(1024 * 1024),
            b""
        ):
            h.update(block)

    return h.hexdigest()


# Include final aggregate evidence + closure evidence
files_to_hash = []

for p in AGG_DIR.glob("*"):
    if p.is_file():
        files_to_hash.append(p)

for p in CLOSE_DIR.glob("*"):
    if (
        p.is_file()
        and p.name != "R1_SHA256_MANIFEST.csv"
    ):
        files_to_hash.append(p)


manifest_rows = []

for p in sorted(
    files_to_hash,
    key=lambda x: str(x)
):

    manifest_rows.append({
        "relative_path":
            str(p.relative_to(R1)),

        "size_bytes":
            p.stat().st_size,

        "sha256":
            sha256_file(p),
    })


manifest = pd.DataFrame(
    manifest_rows
)

manifest.to_csv(
    CLOSE_DIR /
    "R1_SHA256_MANIFEST.csv",
    index=False
)

# ------------------------------------------------------------
# 7. FINAL VALIDATION
# ------------------------------------------------------------

required = [
    CLOSE_DIR / "R1_publication_table.csv",
    CLOSE_DIR / "R1_final_findings.txt",
    CLOSE_DIR / "R1_closure.json",
    CLOSE_DIR / "R1_SHA256_MANIFEST.csv",
]

for p in required:
    assert p.exists()
    assert p.stat().st_size > 0


with open(
    CLOSE_DIR / "R1_closure.json",
    encoding="utf-8"
) as f:
    check = json.load(f)

assert check["status"] == "PASS_CLOSED"
assert check["number_of_condition_runs"] == 20
assert check["L3_L4_equivalence_all_seeds"] is True


# ------------------------------------------------------------
# 8. DISPLAY FINAL RESULTS
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("R1 PUBLICATION-READY RESULT")
print("=" * 100)

display(publication_table)


print("\n" + "=" * 100)
print("R1 FINAL INTERPRETATION")
print("=" * 100)

print(findings)


print("\n" + "=" * 100)
print("R1 EVIDENCE MANIFEST")
print("=" * 100)

display(manifest)


print("\nFinal evidence directory:")
print(CLOSE_DIR)

print("\n" + "=" * 100)
print("R1 STATUS: PASS — CLOSED AND FROZEN")
print("=" * 100)

====================================================================================================
R1 PUBLICATION-READY RESULT
====================================================================================================

,Condition,Seeds,Accuracy (mean ± SD),Macro-F1 (mean ± SD)
0,L1 — Original,5,0.9311 ± 0.0065,0.9311 ± 0.0065
1,L2 — Phrase-family-held-out,5,0.9549 ± 0.0081,0.9548 ± 0.0081
2,L3 — Generic + KPI,5,0.8920 ± 0.0080,0.8920 ± 0.0078
3,L4 — KPI-only,5,0.8920 ± 0.0080,0.8920 ± 0.0078

====================================================================================================
R1 FINAL INTERPRETATION
====================================================================================================
R1 — Phrase Generalization and Lexical Ablation
================================================

Experimental design
-------------------
R1 was evaluated across five random seeds:
42, 43, 44, 45, and 46.

Four conditions were evaluated:

L1 — Original:
Original synthetic intent text using the frozen feature pipeline.

L2 — Phrase-family-held-out:
Strict class-specific phrase/use-case family holdout.
Train and test phrase families are disjoint.
Generic use cases are excluded from this condition.

L3 — Generic + KPI:
Use-case semantic phrases are replaced with a neutral
"network service" expression while preserving observable KPI
information.

L4 — KPI-only:
Only KPI information observable to the frozen parser is retained.

Final five-seed results
-----------------------
L1 accuracy:
0.9311 ± 0.0065

L1 macro-F1:
0.9311 ± 0.0065

L2 accuracy:
0.9549 ± 0.0081

L2 macro-F1:
0.9548 ± 0.0081

L3 accuracy:
0.8920 ± 0.0080

L3 macro-F1:
0.8920 ± 0.0078

L4 accuracy:
0.8920 ± 0.0080

L4 macro-F1:
0.8920 ± 0.0078

Lexical-ablation effect
-----------------------
Mean L1 -> L3/L4 accuracy reduction:
0.0391 ±
0.0090

Mean L1 -> L3/L4 macro-F1 reduction:
0.0392 ±
0.0089

Interpretation
--------------
1. Performance remains strong under strict held-out
   class-specific phrase families.

2. Therefore, the classifier does not exhibit performance
   collapse when evaluated on phrase families excluded from
   training.

3. Removing lexical/use-case information produces a consistent
   performance reduction across all five seeds.

4. Consequently, lexical intent cues provide useful predictive
   information, but classification is not solely dependent on
   lexical phrase memorization.

5. L2 must NOT be described as an improvement over L1.
   L2 uses a different evaluation population because generic
   examples are excluded.

6. L3 and L4 produce identical frozen feature representations
   across all five evaluated corpora. Their identical results are
   therefore an architectural/representation finding rather than
   independent evidence from two distinct model representations.

7. Ambiguous intents require separate interpretation because the
   synthetic ground-truth label is defined before KPI blending.
   KPI-only disagreement on such cases should not automatically be
   interpreted as ordinary classification failure.

Conclusion
----------
R1 provides evidence against the concern that the reported
classifier performance is explained solely by memorization of
class-specific intent phrases.

The experiment also quantifies the contribution of lexical cues:
removing those cues reduces macro-F1 by approximately
3.92 percentage points on average.

Claims should remain limited to the evaluated synthetic corpus,
frozen parser, feature representation, model-selection procedure,
and phrase families used in this experiment.

====================================================================================================
R1 EVIDENCE MANIFEST
====================================================================================================

,relative_path,size_bytes,sha256
0,final_evidence/R1_closure.json,1247,39dab26aa75dd84682c5198a8ce9ccda019f3266a59ee3...
1,final_evidence/R1_final_findings.txt,2871,3e37bb5d1e596381fdcafd95fdc3db29729835e552b15c...
2,final_evidence/R1_publication_table.csv,287,41cece77e764f189b0424e1c251eb08f3196158015b1a8...
3,results/aggregate/r1_L1_vs_L3L4_paired.csv,654,abbd164db63a0c288215b6682b65d926445540b21dafbf...
4,results/aggregate/r1_L1_vs_L3L4_summary.csv,156,3c6abede7a66cfb78423d72bfb01c9284d5b3c91ba2b09...
5,results/aggregate/r1_L2_descriptive_comparison...,722,efa30e67409004d6ea664cbabb4b072a8dc4acf7161069...
6,results/aggregate/r1_L3_L4_equivalence.csv,197,935b778e48ac561fe90473071a9c17d2ba47c5380d92f6...
7,results/aggregate/r1_all_20_runs.csv,3074,335adee09e6619f222e6da7054e0a23d8924ba9c9c92c2...
8,results/aggregate/r1_five_seed_summary.csv,702,bef737c135a169b807fe36b73d598bdba3a43f8d9ed7a6...
9,results/aggregate/r1_model_selection_counts.csv,303,090b363017a0c1e10b8e726bd913c90e5a76af22eac283...

Final evidence directory:
/content/revision_experiments/R1_phrase_generalization/final_evidence

====================================================================================================
R1 STATUS: PASS — CLOSED AND FROZEN
====================================================================================================

In [65]:
from pathlib import Path

R1 = Path("/content/revision_experiments/R1_phrase_generalization")

assert R1.exists(), f"R1 directory not found: {R1}"

print("=" * 100)
print("R1 FINAL DIRECTORY CHECK")
print("=" * 100)

for p in sorted(R1.iterdir()):
    if p.is_dir():
        nfiles = sum(1 for x in p.rglob("*") if x.is_file())
        size = sum(x.stat().st_size for x in p.rglob("*") if x.is_file())

        print(
            f"{p.name:<25} "
            f"{nfiles:>5} files   "
            f"{size / (1024*1024):>8.2f} MB"
        )
    else:
        print(f"{p.name:<25} FILE")

print("\nR1 root:")
print(R1)

====================================================================================================
R1 FINAL DIRECTORY CHECK
====================================================================================================
audit                        20 files       0.11 MB
data                         31 files      25.02 MB
figures                       0 files       0.00 MB
final_evidence                4 files       0.01 MB
frozen_reference              1 files       0.00 MB
manifests                     5 files       0.01 MB
notebooks                     0 files       0.00 MB
results                     132 files       1.14 MB
splits                       25 files       0.15 MB
src                           0 files       0.00 MB

R1 root:
/content/revision_experiments/R1_phrase_generalization

In [66]:
from pathlib import Path

HANDOFF = R1 / "R1_HANDOFF_README.md"

handoff_text = r"""
# R1 — Phrase Generalization and Lexical Ablation

## Status

**PASS — CLOSED AND FROZEN**

R1 must not be rerun, modified, or overwritten unless a deliberate
new experiment version is created.

---

## Purpose

R1 addresses the reviewer concern that classification performance
may be caused primarily by memorization of synthetic class-specific
phrases or lexical cues.

The experiment evaluates phrase-family generalization and lexical
ablation while preserving the frozen implementation used for the
revision experiments.

---

## Seeds

Five independent corpus seeds were evaluated:

- 42
- 43
- 44
- 45
- 46

Total evaluated condition runs:

**5 seeds × 4 conditions = 20 runs**

---

## Experimental Conditions

### L1 — Original

Original synthetic intent text evaluated using the frozen feature
pipeline and training-only model selection.

### L2 — Phrase-family-held-out

Strict class-specific phrase/use-case family holdout.

Train and test phrase families are disjoint.

Generic use cases are excluded from the main L2 evaluation.

This condition directly tests whether the classifier collapses when
evaluated on phrase families that were absent from training.

### L3 — Generic + KPI

Class-specific use-case phrases are replaced with the neutral phrase:

`network service`

Observable KPI information is preserved.

### L4 — KPI-only

Only KPI information observable to the frozen parser is retained.

No hidden latent KPI values are introduced.

---

## Final Five-Seed Results

| Condition | Accuracy mean ± SD | Macro-F1 mean ± SD |
|---|---:|---:|
| L1 Original | 0.9311 ± 0.0065 | 0.9311 ± 0.0065 |
| L2 Phrase-family-held-out | 0.9549 ± 0.0081 | 0.9548 ± 0.0081 |
| L3 Generic + KPI | 0.8920 ± 0.0080 | 0.8920 ± 0.0078 |
| L4 KPI-only | 0.8920 ± 0.0080 | 0.8920 ± 0.0078 |

---

## Lexical Ablation Result

Mean L1 -> L3/L4 accuracy reduction:

**0.0391 ± 0.0090**

Mean L1 -> L3/L4 macro-F1 reduction:

**0.0392 ± 0.0089**

This corresponds to approximately:

**3.92 percentage points macro-F1**

---

## Main Scientific Finding

Performance does not collapse when class-specific phrase families
are held out from training.

Removing lexical/use-case information causes a consistent performance
reduction across all five seeds.

Therefore:

**Lexical intent information contributes to classification, but the
classifier is not solely dependent on memorization of class-specific
phrases.**

---

## Important Interpretation Restrictions

### L2

Do NOT claim:

> L2 improves performance over L1.

L2 and L1 use different evaluation populations because generic
examples are excluded from L2.

L2 should instead be interpreted as evidence that held-out phrase
families do not cause performance collapse.

### L3 and L4

L3 and L4 are different text interventions but produce identical
frozen model feature representations.

Their identical results are therefore an architectural /
representation finding.

They must NOT be presented as two independent model-level pieces
of evidence.

### Ambiguous intents

Synthetic ground-truth slice labels are assigned before KPI blending.

Therefore, KPI-only disagreement for ambiguous samples should not
automatically be interpreted as conventional classification error.

---

## Model Selection

Model selection was performed using training data only.

The held-out test set was not used for model selection.

Across seeds, model selection was not artificially fixed.

Gradient Boosting was selected most frequently, while Decision Tree
or Random Forest was selected for some seed/condition combinations.

---

## Reproducibility Note

During R1 preparation, a discrepancy was identified between an older
archived E1 result and reproduction using the currently packaged
source.

Direct execution of the current packaged source reproduced the new
R1 baseline exactly.

Therefore:

**The current frozen source snapshot is the authoritative
implementation for R1.**

The historical archived metric was preserved as historical evidence
and was NOT forced into the R1 results.

---

## Evidence Structure

Important directories include:

- `data/`
- `splits/`
- `results/`
- `audit/`
- `manifests/`
- `frozen_reference/`
- `final_evidence/`

Final aggregate evidence:

`results/aggregate/`

Final frozen evidence:

`final_evidence/`

---

## Key Final Files

### Aggregate

- `r1_all_20_runs.csv`
- `r1_five_seed_summary.csv`
- `r1_model_selection_counts.csv`
- `r1_L1_vs_L3L4_paired.csv`
- `r1_L1_vs_L3L4_summary.csv`
- `r1_L2_descriptive_comparison.csv`
- `r1_L3_L4_equivalence.csv`

### Final evidence

- `R1_publication_table.csv`
- `R1_final_findings.txt`
- `R1_closure.json`
- `R1_SHA256_MANIFEST.csv`

---

## Final R1 Status

**R1 STATUS: PASS — CLOSED AND FROZEN**

Do not modify R1 evidence while conducting R2 or later experiments.

Create separate experiment directories for subsequent reviewer
experiments.

---

## Next Planned Experiment

R2 — Strict Feasibility / Validity Audit

Primary objective:

Evaluate whether the current feasibility/validity mechanism is too
permissive and quantify false-feasible decisions under stricter
network-slicing constraints.

R2 should be started as a separate experiment and should not modify
R1.
"""

HANDOFF.write_text(handoff_text.strip() + "\n", encoding="utf-8")

print("Created:")
print(HANDOFF)
print("\nSize:", HANDOFF.stat().st_size, "bytes")

Created:
/content/revision_experiments/R1_phrase_generalization/R1_HANDOFF_README.md

Size: 5232 bytes

In [67]:
import pandas as pd
import hashlib

def sha256_file(path):
    h = hashlib.sha256()

    with open(path, "rb") as f:
        for block in iter(
            lambda: f.read(1024 * 1024),
            b""
        ):
            h.update(block)

    return h.hexdigest()


rows = []

files = sorted(
    p for p in R1.rglob("*")
    if p.is_file()
)

print("Files to inventory:", len(files))

for i, p in enumerate(files, 1):

    rows.append({
        "relative_path": str(p.relative_to(R1)),
        "size_bytes": p.stat().st_size,
        "sha256": sha256_file(p),
    })

    if i % 50 == 0:
        print("Processed:", i)


inventory = pd.DataFrame(rows)

inventory_path = (
    R1 /
    "R1_COMPLETE_ARTIFACT_INVENTORY.csv"
)

inventory.to_csv(
    inventory_path,
    index=False
)

print("\nInventory created:")
print(inventory_path)

print("\nTotal files:", len(inventory))
print(
    "Total size:",
    round(
        inventory["size_bytes"].sum()
        / 1024 / 1024,
        2
    ),
    "MB"
)

display(inventory.head(20))

Files to inventory: 219
Processed: 50
Processed: 100
Processed: 150
Processed: 200

Inventory created:
/content/revision_experiments/R1_phrase_generalization/R1_COMPLETE_ARTIFACT_INVENTORY.csv

Total files: 219
Total size: 26.44 MB

,relative_path,size_bytes,sha256
0,R1_HANDOFF_README.md,5232,3510db2b8ac727e06a909651fd1acb756361d3a3ae91e4...
1,audit/L2_final_pretraining_audit.csv,472,270c1cb11fa55b31092262f5d7ad6366ae6b36d21b8fe5...
2,audit/direct_e1_seed42/e1_confusion.csv,28,1080c085abe44f790ceca8382d57c3784d8b64c07dce3e...
3,audit/direct_e1_seed42/e1_escalation.csv,450,eaff09c4419274b89f66a82545b898b3c52db2452a2c4d...
4,audit/direct_e1_seed42/e1_escalation_oof.csv,424,fbb313c4a7bd97c9e800151f4a9aa4ca3251fb8b35df16...
5,audit/direct_e1_seed42/e1_escalation_signals.csv,416,a3a0d14306a80a5e8f95b2ea5f79041ac9fb8b3c0cc172...
6,audit/direct_e1_seed42/e1_local_explanations.json,1513,5ddce00119eb2991362f5f5385cc7064b3e1ee8ee52a1c...
7,audit/direct_e1_seed42/e1_models.csv,893,7469cc900f244c94c642d717ef28b87dc30748f4b8fce7...
8,audit/direct_e1_seed42/e1_per_class.csv,203,296fe0156a0d1ff081ba8ec6bab39cb2a1bae7f094169f...
9,audit/direct_e1_seed42/e1_shap_global.csv,506,027656a188a38e826cec2e48e81196579ab5828a3d23a0...
10,audit/direct_e1_seed42/e1_summary.json,4662,e667431f97c2121e00430f816c195677a73bff0ff87a93...
11,audit/final_L1_L3_L4_feature_audit.csv,385,3a58bb0a1da5804c42a3e85d5ad9937d4d0045334ffd29...
12,audit/final_L2_phrase_family_audit.csv,1230,bc27916d1b2ec90574881d16d4963f012d8e4f515a2c7b...
13,audit/l4_observable_kpi_coverage.csv,38892,6059b2a7188bea89d86a5a33e3c928340d77961c0fadc5...
14,audit/original_phrase_inventory.csv,2014,99d3529b595c8adbe51a0fbd38eae802a9ee1349c6eeaf...
15,audit/phrase_family_leakage_audit.csv,695,66b7426d603a5dd7029d3a67f812e017bcd97eaae2b897...
16,audit/r1_baseline_provenance.json,1073,720bc14836134abb14ba74f44c5ef86ffcb793449b1b3b...
17,audit/r1_condition_sanity.csv,59612,d4943734a43f93d8c0102d8b012f91f8831a6a26dad63c...
18,audit/r1_feature_preservation.csv,297,8758a873f526981bd7e7e9cbd6950fb9f406a7d8a22734...
19,audit/r1_final_corpus_generation.csv,625,fc6c7c3a8343832533d1ccd1e8ad4f91fa4516d6c1728a...

In [68]:
import json
from datetime import datetime, timezone

completion = {
    "experiment": "R1_phrase_generalization",
    "status": "PASS_CLOSED_FROZEN_ARCHIVED",
    "seeds": [42, 43, 44, 45, 46],
    "conditions": [
        "L1_original",
        "L2_phrase_family_heldout",
        "L3_generic_kpi",
        "L4_kpi_only"
    ],
    "total_condition_runs": 20,
    "macro_f1": {
        "L1_original": 0.9311,
        "L2_phrase_family_heldout": 0.9548,
        "L3_generic_kpi": 0.8920,
        "L4_kpi_only": 0.8920
    },
    "lexical_ablation_macro_f1_drop": 0.0392,
    "next_experiment": "R2_strict_feasibility_validity",
    "instruction": (
        "Do not modify R1. "
        "Start subsequent experiments in separate directories."
    ),
    "archive_created_utc":
        datetime.now(timezone.utc).isoformat()
}

completion_path = (
    R1 /
    "R1_EXPERIMENT_COMPLETE.json"
)

with open(
    completion_path,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        completion,
        f,
        indent=2
    )

print(completion_path)

/content/revision_experiments/R1_phrase_generalization/R1_EXPERIMENT_COMPLETE.json

In [69]:
import shutil
from pathlib import Path

ARCHIVE_BASE = Path(
    "/content/"
    "XAgentic_R1_Phrase_Generalization_FINAL_2026-10-07"
)

zip_path = shutil.make_archive(
    str(ARCHIVE_BASE),
    "zip",
    root_dir=str(R1.parent),
    base_dir=R1.name
)

print("=" * 100)
print("R1 FINAL ARCHIVE CREATED")
print("=" * 100)

print(zip_path)

size_mb = (
    Path(zip_path).stat().st_size
    / 1024 / 1024
)

print(f"\nZIP size: {size_mb:.2f} MB")

====================================================================================================
R1 FINAL ARCHIVE CREATED
====================================================================================================
/content/XAgentic_R1_Phrase_Generalization_FINAL_2026-10-07.zip

ZIP size: 5.15 MB

In [70]:
import zipfile
import hashlib
from pathlib import Path

ZIP = Path(
    "/content/"
    "XAgentic_R1_Phrase_Generalization_FINAL_2026-10-07.zip"
)

assert ZIP.exists()

with zipfile.ZipFile(ZIP, "r") as z:

    bad = z.testzip()

    names = z.namelist()

    print("ZIP entries:", len(names))

    assert bad is None, (
        f"Corrupt ZIP entry: {bad}"
    )

    required = [
        "R1_phrase_generalization/R1_HANDOFF_README.md",
        "R1_phrase_generalization/R1_EXPERIMENT_COMPLETE.json",

        "R1_phrase_generalization/"
        "final_evidence/R1_closure.json",

        "R1_phrase_generalization/"
        "final_evidence/R1_final_findings.txt",

        "R1_phrase_generalization/"
        "final_evidence/R1_publication_table.csv",

        "R1_phrase_generalization/"
        "final_evidence/R1_SHA256_MANIFEST.csv",

        "R1_phrase_generalization/"
        "results/aggregate/r1_all_20_runs.csv",

        "R1_phrase_generalization/"
        "results/aggregate/r1_five_seed_summary.csv",
    ]

    for item in required:
        assert item in names, (
            f"Missing from ZIP: {item}"
        )

print("\nZIP integrity: PASS")
print("Required final evidence: PASS")


def sha256(path):
    h = hashlib.sha256()

    with open(path, "rb") as f:
        for block in iter(
            lambda: f.read(1024 * 1024),
            b""
        ):
            h.update(block)

    return h.hexdigest()


digest = sha256(ZIP)

print("\nZIP SHA-256:")
print(digest)

print("\nZIP:")
print(ZIP)

print("\n" + "=" * 100)
print("R1 ARCHIVE VERIFICATION: PASS")
print("=" * 100)

ZIP entries: 251

ZIP integrity: PASS
Required final evidence: PASS

ZIP SHA-256:
bdac27c42a7514700dc878c372c7a2555dd6a1bfcaca9326b1df9900a2e371a4

ZIP:
/content/XAgentic_R1_Phrase_Generalization_FINAL_2026-10-07.zip

====================================================================================================
R1 ARCHIVE VERIFICATION: PASS
====================================================================================================

In [71]:
from google.colab import files

files.download(
    "/content/"
    "XAgentic_R1_Phrase_Generalization_FINAL_2026-10-07.zip"
)