In [34]:
from google.colab import files
uploaded = files.upload()

Saving xagentic-slicing.zip to xagentic-slicing.zip

In [35]:
!ls -lh /content/xagentic-slicing.zip

-rw-r--r-- 1 root root 7.1M Oct  5 10:19 /content/xagentic-slicing.zip

In [36]:
import os
import zipfile
import shutil

ZIP_FILE = "/content/xagentic-slicing.zip"
EXTRACT_DIR = "/content/xagentic_work"

if os.path.exists(EXTRACT_DIR):
    shutil.rmtree(EXTRACT_DIR)

os.makedirs(EXTRACT_DIR, exist_ok=True)

with zipfile.ZipFile(ZIP_FILE, "r") as z:
    z.extractall(EXTRACT_DIR)

print("Extraction completed.")

Extraction completed.

In [37]:
PROJECT_DIR = "/content/xagentic_work/xagentic-slicing"
EXPERIMENT_DIR = os.path.join(PROJECT_DIR, "experiment")

assert os.path.isdir(EXPERIMENT_DIR)

print("Experiment directory:", EXPERIMENT_DIR)
print("PASS")

Experiment directory: /content/xagentic_work/xagentic-slicing/experiment
PASS

In [38]:
%pip install -q \
    "numpy>=1.24" \
    "pandas>=2.0" \
    "scikit-learn>=1.3" \
    "matplotlib>=3.7" \
    "shap>=0.44" \
    lime \
    sentence-transformers \
    requests

shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
The folder you are executing pip from can no longer be found.

In [39]:
%cd /content

/content

In [40]:
import os

print("Current directory:", os.getcwd())
print("Exists:", os.path.isdir(os.getcwd()))

Current directory: /content
Exists: True

In [41]:
import os

PROJECT_DIR = "/content/xagentic_work/xagentic-slicing"
EXPERIMENT_DIR = os.path.join(PROJECT_DIR, "experiment")

print("Project exists    :", os.path.isdir(PROJECT_DIR))
print("Experiment exists :", os.path.isdir(EXPERIMENT_DIR))

assert os.path.isdir(PROJECT_DIR), "Project directory missing"
assert os.path.isdir(EXPERIMENT_DIR), "Experiment directory missing"

print("\nPASS — project structure is OK.")

Project exists    : True
Experiment exists : True

PASS — project structure is OK.

In [42]:
%pip install -q \
    "numpy>=1.24" \
    "pandas>=2.0" \
    "scikit-learn>=1.3" \
    "matplotlib>=3.7" \
    "shap>=0.44" \
    lime \
    sentence-transformers \
    requests

In [43]:
import numpy
import pandas
import sklearn
import matplotlib
import shap
import lime
import requests

print("numpy        :", numpy.__version__)
print("pandas       :", pandas.__version__)
print("scikit-learn :", sklearn.__version__)
print("matplotlib   :", matplotlib.__version__)
print("shap         :", shap.__version__)
print("requests     :", requests.__version__)

print("\nPASS — dependencies available.")

numpy        : 2.1.3
pandas       : 2.2.3
scikit-learn : 1.6.1
matplotlib   : 3.10.0
shap         : 0.52.0
requests     : 2.32.4

PASS — dependencies available.

In [44]:
%cd /content/xagentic_work/xagentic-slicing/experiment

/content/xagentic_work/xagentic-slicing/experiment

In [45]:
import os

print("Current directory:")
print(os.getcwd())

print("\nImportant files:")
for f in ["run_all.py", "run_seeds.py"]:
    print(f"{f:20s}", "PASS" if os.path.isfile(f) else "MISSING")

Current directory:
/content/xagentic_work/xagentic-slicing/experiment

Important files:
run_all.py           PASS
run_seeds.py         PASS

In [46]:
!python run_seeds.py --help

usage: run_seeds.py [-h] [--seeds SEEDS [SEEDS ...]] [--quick]
                    [--collect-only] [--no-llm] [--no-embeddings]

options:
  -h, --help            show this help message and exit
  --seeds SEEDS [SEEDS ...]
  --quick
  --collect-only        skip running; just re-aggregate existing seed outputs
  --no-llm
  --no-embeddings

In [47]:
%cd /content/xagentic_work/xagentic-slicing/experiment

import os

print("Current directory:", os.getcwd())

for item in sorted(os.listdir(".")):
    if "seed" in item.lower():
        print(item)

/content/xagentic_work/xagentic-slicing/experiment
Current directory: /content/xagentic_work/xagentic-slicing/experiment
run_seeds.py

In [48]:
!find . -maxdepth 2 -type d | sort

.
./__pycache__
./results
./results_before_e4

In [49]:
!python run_seeds.py \
    --seeds 42 43 44 45 46 \
    --quick \
    --no-llm \
    --no-embeddings \
    2>&1 | tee /content/xagentic_5seed_quick.log

========================================================================
SEED 42
========================================================================
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names

In [50]:
!tail -150 /content/xagentic_5seed_quick.log

 0.7   0.083333   0.433333 0.371429        0.933333
 0.8   0.141667   0.392157 0.571429        0.951456
 0.9   0.222222   0.312500 0.714286        0.964286
[S5] tau=0.90  OOF(selection) esc 20.4% rec 84.1% auto 98.5%  |  TEST esc 22.2% rec 71.4% auto 96.4%
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e1_escalation_signals.csv
[S5b] escalation signal ablation at matched budget:
                             signal   budget  escalated  precision   recall  autonomous_acc
                    Confidence only 0.208333   0.208333   0.333333 0.714286        0.964912
     Attribution concentration only 0.208333   0.208333   0.240000 0.514286        0.940351
              Confidence + contract 0.208333   0.208333   0.333333 0.714286        0.964912
Confidence + contract + attribution 0.208333   0.208333   0.320000 0.685714        0.961404
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e1_local_explanations.json
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e1_summary.json
[E1] accuracy 0.9028 | macro F1 0.9028 | OOV gap 13.9 pts | explanation 251.21 ms/intent
========================================================================
EXPERIMENT 2 -- In-hoc vs post-hoc explanation
========================================================================
[E2] in-hoc: Linear-Attribution (logistic regression) ...
  Linear-Attribution       acc=0.8861 expl=   0.0075 ms  fidelity(top1/rand1)=12.5x
[E2] in-hoc: Decision-Path (depth-8 tree) ...
  Decision-Path            acc=0.8889 expl=   0.0124 ms  fidelity(top1/rand1)=9.7x
[E2] in-hoc: SENN (self-explaining network) ...
  SENN                     acc=0.8944 expl=   0.0029 ms  fidelity(top1/rand1)=8.1x
[E2] post-hoc: SHAP on gradient boosting ...
  SHAP                     acc=0.9028 expl= 230.3909 ms  fidelity(top1/rand1)=6.4x
[E2] post-hoc: LIME on 150 instances (subsampled; slow) ...
  LIME                     expl=  84.5398 ms  fidelity(top1/rand1)=60000000.0x
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e2_explainers.csv

         explainer     kind               model      acc       f1  infer_ms    expl_ms        ratio     top1    rand1         fid1     top3    rand3      fid3
Linear-Attribution   in-hoc Logistic Regression 0.886111 0.885944  0.006440   0.007481     1.161524 0.277778 0.022222 1.250000e+01 0.622222 0.075000  8.296296
     Decision-Path   in-hoc Decision Tree (d=8) 0.888889 0.888943  0.005218   0.012355     2.367658 0.297222 0.030556 9.727273e+00 0.341667 0.077778  4.392857
              SENN   in-hoc    SENN (32 hidden) 0.894444 0.894630  0.005714   0.002940     0.514506 0.358333 0.044444 8.062500e+00 0.591667 0.102778  5.756757
              SHAP post-hoc   Gradient Boosting 0.902778 0.902753  0.020482 230.390914 11248.575350 0.161111 0.025000 6.444444e+00 0.436111 0.033333 13.083333
              LIME post-hoc   Gradient Boosting 0.920000 0.919545  0.020482  84.539759  4127.557956 0.060000 0.000000 6.000000e+07 0.120000 0.060000  2.000000
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e2_summary.json

[E2] best in-hoc = SENN: 78360x cheaper than SHAP, accuracy cost 0.8 pts, fidelity 8.1x vs SHAP 6.4x
========================================================================
EXPERIMENT 3 -- Semantic Intent Agent vs design-time lexicon
========================================================================
[E3] 35 distinct use-case phrases in the corpus
[E3] building TF-IDF char n-gram scorer ...
[E3] TOGETHER_API_KEY not set -- skipping LLM variant
[E3] evaluating A. Lexicon (E1) ...
  acc=0.9028 known=0.9924 unseen=0.8320 generic=0.8750 OOV gap=13.9 pts
[E3] evaluating B. TF-IDF n-gram ...
  acc=0.9194 known=0.9924 unseen=0.9040 generic=0.8462 OOV gap=11.7 pts
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e3_variants.csv

         variant      acc       f1  acc_known  acc_unseen  acc_generic  oov_gap  acc_ambiguous  intent_ms  escalated80  autonomous80
 A. Lexicon (E1) 0.902778 0.902753   0.992366       0.832     0.875000 0.138866       0.732283   0.268269     0.141667      0.951456
B. TF-IDF n-gram 0.919444 0.919263   0.992366       0.904     0.846154 0.117289       0.787402   0.148412     0.138889      0.961290
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e3_summary.json

[E3] B. TF-IDF n-gram closes the open-vocabulary gap by 2.2 pts (13.9 -> 11.7) and lifts accuracy by 1.7 pts
========================================================================
EXPERIMENT 4 -- Combined configuration (E2 x E3 factorial)
========================================================================
[E4] 35 distinct use-case phrases; 4 cells to evaluate
[E4] E1  exact + SHAP ...
     acc=0.9028  expl=  24.0864 ms  fid1=6.3x  oov_gap=13.9 pts/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

[E4] E2  exact + Decision-Path ...
     acc=0.8889  expl=   0.0123 ms  fid1=9.7x  oov_gap=12.4 pts
[E4] E3  TF-IDF + SHAP ...
     acc=0.9194  expl=  24.4900 ms  fid1=4.8x  oov_gap=11.7 pts
[E4] E4  TF-IDF + Decision-Path ...
     acc=0.8806  expl=   0.0246 ms  fid1=9.3x  oov_gap=11.8 pts
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e4_factorial.csv
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e4_summary.json

------------------------------------------------------------------------
                      cell      acc   expl_ms     fid1  oov_gap
          E1  exact + SHAP 0.902778 24.086384 6.333333 0.138866
 E2  exact + Decision-Path 0.888889  0.012253 9.727273 0.123966
         E3  TF-IDF + SHAP 0.919444 24.490031 4.833333 0.117289
E4  TF-IDF + Decision-Path 0.880556  0.024557 9.333333 0.117545
------------------------------------------------------------------------
[E4] accuracy effect  explainer only : -1.4 pts
[E4] accuracy effect  prior only     : +1.7 pts
[E4] accuracy effect  both combined  : -2.2 pts
[E4] interaction (combined - sum)    : -2.5 pts
[E4] OOV gap  13.9 -> 11.8 pts
[E4] explanation cost speedup        : 981x
  -> /content/xagentic_work/xagentic-slicing/experiment/results/comparison.csv

========================================================================
CROSS-EXPERIMENT COMPARISON
========================================================================
experiment                   focus  intent_agent              explainer      acc       f1    expl_ms  fidelity  oov_gap
        E1    Post-hoc explanation       Lexicon        SHAP (post-hoc) 0.902778 0.902753 251.208365  6.444444 0.138866
        E2      In-hoc explanation       Lexicon          SENN (in-hoc) 0.894444 0.894630   0.002940  8.062500 0.163308
        E3 Semantic intent parsing TF-IDF n-gram        SHAP (post-hoc) 0.919444 0.919263 251.208365  6.444444 0.117289
        E4      Combined (E2 + E3) TF-IDF n-gram Decision-Path (in-hoc) 0.880556 0.880714   0.024557  9.333333 0.117545

[run_all] writing LaTeX macros ...
  -> /content/xagentic_work/xagentic-slicing/experiment/results/results_macros.tex  (69 macros)
[run_all] rendering figures ...
  -> /content/xagentic_work/xagentic-slicing/experiment/results/fig_shap_global.pdf
  -> /content/xagentic_work/xagentic-slicing/experiment/results/fig_escalation.pdf
  -> /content/xagentic_work/xagentic-slicing/experiment/results/fig_e2_latency.pdf
  -> /content/xagentic_work/xagentic-slicing/experiment/results/fig_e3_oov.pdf
  -> /content/xagentic_work/xagentic-slicing/experiment/results/fig_e4_combined.pdf
  -> /content/xagentic_work/xagentic-slicing/experiment/results/all_summary.json

[run_all] done. Copy these back into the paper directory:
  OK /content/xagentic_work/xagentic-slicing/experiment/results/results_macros.tex
  OK /content/xagentic_work/xagentic-slicing/experiment/results/fig_shap_global.pdf
  OK /content/xagentic_work/xagentic-slicing/experiment/results/fig_escalation.pdf
  OK /content/xagentic_work/xagentic-slicing/experiment/results/fig_e2_latency.pdf
  OK /content/xagentic_work/xagentic-slicing/experiment/results/fig_e3_oov.pdf
  OK /content/xagentic_work/xagentic-slicing/experiment/results/fig_e4_combined.pdf
  -- /content/xagentic_work/xagentic-slicing/experiment/results/fig_e5_agentic.pdf
  OK /content/xagentic_work/xagentic-slicing/experiment/results/comparison.csv
  OK /content/xagentic_work/xagentic-slicing/experiment/results/e4_factorial.csv
  -- /content/xagentic_work/xagentic-slicing/experiment/results/e5_agentic.csv
  -- /content/xagentic_work/xagentic-slicing/experiment/results/e5_summary.json
  -- /content/xagentic_work/xagentic-slicing/experiment/results/llm_cache.json
  OK /content/xagentic_work/xagentic-slicing/experiment/results/all_summary.json

[run_all] tip: zip the whole results folder and download it:
  shutil.make_archive('xagentic_results', 'zip', '/content/xagentic_work/xagentic-slicing/experiment/results')
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e1_seeds.csv
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e4_seeds.csv

========================================================================
MULTI-SEED SUMMARY  (n = 5 seeds)
========================================================================
  EOneAccS              +91.7  std    1.3  95% CI [+90.7, +92.7]  (n=5)
  EOneOOVS              +12.7  std    2.2  95% CI [+11.0, +14.3]  (n=5)
  EOneFidS               +8.6  std    4.2  95% CI [+5.9, +12.2]  (n=5)
  model selected    Gradient Boosting in 4/5 seeds
  tau selected      0.90 in 4/5 seeds
  EFourAccS             +88.3  std    0.5  95% CI [+87.9, +88.6]  (n=5)
  EFourOOVS             +10.3  std    2.9  95% CI [+8.1, +12.5]  (n=5)
  DeltaExpl              -2.0  std    2.1  95% CI [-3.7, -0.4]  (n=5)
  DeltaPrior             +1.4  std    0.9  95% CI [+0.7, +2.0]  (n=5)
  Gamma                  -2.9  std    2.1  95% CI [-4.5, -1.2]  (n=5)

  --------------------------------------------------------------------
  INTERACTION gamma = -2.9 +/- 2.1 pts, 95% CI [-4.5, -1.2]
  -> the interval EXCLUDES zero: the gains demonstrably do not compose.
  --------------------------------------------------------------------

  -> /content/xagentic_work/xagentic-slicing/experiment/results/results_macros_seeds.tex
[run_seeds] copy results_macros_seeds.tex next to paper.tex.

In [51]:
logfile = "/content/xagentic_5seed_quick.log"

with open(logfile, "r", errors="ignore") as f:
    log = f.read()

print("Traceback :", "YES" if "Traceback" in log else "NO")
print("ERROR     :", "YES" if "ERROR" in log.upper() else "NO")

for seed in [42, 43, 44, 45, 46]:
    print(
        f"Seed {seed}:",
        "mentioned" if str(seed) in log else "NOT FOUND"
    )

Traceback : NO
ERROR     : YES
Seed 42: mentioned
Seed 43: mentioned
Seed 44: mentioned
Seed 45: mentioned
Seed 46: mentioned

In [56]:
!grep -in -C 3 "error" /content/xagentic_5seed_quick.log

360- 0.9   0.292857   0.195122 0.761905        0.974747
361-  -> /content/xagentic_work/xagentic-slicing/experiment/results/e1_per_class.csv
362-[S6] computing SHAP attributions ...
363:     TreeExplainer unavailable (InvalidModelError); falling back to PermutationExplainer
364-  -> /content/xagentic_work/xagentic-slicing/experiment/results/e1_shap_global.csv
365-            feature  importance
366-    reliability (%)    0.274724
--
890- 0.9   0.254762   0.224299 0.827586        0.984026
891-  -> /content/xagentic_work/xagentic-slicing/experiment/results/e1_per_class.csv
892-[S6] computing SHAP attributions ...
893:     TreeExplainer unavailable (InvalidModelError); falling back to PermutationExplainer
894-  -> /content/xagentic_work/xagentic-slicing/experiment/results/e1_shap_global.csv
895-            feature  importance
896-    reliability (%)    0.260477
--
1420- 0.9   0.197619   0.277108 0.730159        0.974777
1421-  -> /content/xagentic_work/xagentic-slicing/experiment/results/e1_per_class.csv
1422-[S6] computing SHAP attributions ...
1423:     TreeExplainer unavailable (InvalidModelError); falling back to PermutationExplainer
1424-  -> /content/xagentic_work/xagentic-slicing/experiment/results/e1_shap_global.csv
1425-            feature  importance
1426-    reliability (%)    0.277539
--
2479- 0.9   0.203571   0.309942 0.841270        0.985052
2480-  -> /content/xagentic_work/xagentic-slicing/experiment/results/e1_per_class.csv
2481-[S6] computing SHAP attributions ...
2482:     TreeExplainer unavailable (InvalidModelError); falling back to PermutationExplainer
2483-  -> /content/xagentic_work/xagentic-slicing/experiment/results/e1_shap_global.csv
2484-            feature  importance
2485-    reliability (%)    0.254890

In [57]:
!grep -Ein -C 3 "traceback|exception|failed|failure|fatal" /content/xagentic_5seed_quick.log

In [60]:
!grep -inE "seed.*(42|43|44|45|46)|completed|done|aggregate" \
    /content/xagentic_5seed_quick.log | tail -100

3:SEED 42
331:[run_all] generating shared corpus (n=1200, seed=42) ...
514:[run_all] done. Copy these back into the paper directory:
533:SEED 43
861:[run_all] generating shared corpus (n=1200, seed=43) ...
1044:[run_all] done. Copy these back into the paper directory:
1063:SEED 44
1391:[run_all] generating shared corpus (n=1200, seed=44) ...
1574:[run_all] done. Copy these back into the paper directory:
1593:SEED 45
1923:[run_all] generating shared corpus (n=1200, seed=45) ...
2103:[run_all] done. Copy these back into the paper directory:
2122:SEED 46
2450:[run_all] generating shared corpus (n=1200, seed=46) ...
2633:[run_all] done. Copy these back into the paper directory:

In [61]:
!tail -80 /content/xagentic_5seed_quick.log

[E4] E4  TF-IDF + Decision-Path ...
     acc=0.8806  expl=   0.0246 ms  fid1=9.3x  oov_gap=11.8 pts
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e4_factorial.csv
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e4_summary.json

------------------------------------------------------------------------
                      cell      acc   expl_ms     fid1  oov_gap
          E1  exact + SHAP 0.902778 24.086384 6.333333 0.138866
 E2  exact + Decision-Path 0.888889  0.012253 9.727273 0.123966
         E3  TF-IDF + SHAP 0.919444 24.490031 4.833333 0.117289
E4  TF-IDF + Decision-Path 0.880556  0.024557 9.333333 0.117545
------------------------------------------------------------------------
[E4] accuracy effect  explainer only : -1.4 pts
[E4] accuracy effect  prior only     : +1.7 pts
[E4] accuracy effect  both combined  : -2.2 pts
[E4] interaction (combined - sum)    : -2.5 pts
[E4] OOV gap  13.9 -> 11.8 pts
[E4] explanation cost speedup        : 981x
  -> /content/xagentic_work/xagentic-slicing/experiment/results/comparison.csv

========================================================================
CROSS-EXPERIMENT COMPARISON
========================================================================
experiment                   focus  intent_agent              explainer      acc       f1    expl_ms  fidelity  oov_gap
        E1    Post-hoc explanation       Lexicon        SHAP (post-hoc) 0.902778 0.902753 251.208365  6.444444 0.138866
        E2      In-hoc explanation       Lexicon          SENN (in-hoc) 0.894444 0.894630   0.002940  8.062500 0.163308
        E3 Semantic intent parsing TF-IDF n-gram        SHAP (post-hoc) 0.919444 0.919263 251.208365  6.444444 0.117289
        E4      Combined (E2 + E3) TF-IDF n-gram Decision-Path (in-hoc) 0.880556 0.880714   0.024557  9.333333 0.117545

[run_all] writing LaTeX macros ...
  -> /content/xagentic_work/xagentic-slicing/experiment/results/results_macros.tex  (69 macros)
[run_all] rendering figures ...
  -> /content/xagentic_work/xagentic-slicing/experiment/results/fig_shap_global.pdf
  -> /content/xagentic_work/xagentic-slicing/experiment/results/fig_escalation.pdf
  -> /content/xagentic_work/xagentic-slicing/experiment/results/fig_e2_latency.pdf
  -> /content/xagentic_work/xagentic-slicing/experiment/results/fig_e3_oov.pdf
  -> /content/xagentic_work/xagentic-slicing/experiment/results/fig_e4_combined.pdf
  -> /content/xagentic_work/xagentic-slicing/experiment/results/all_summary.json

[run_all] done. Copy these back into the paper directory:
  OK /content/xagentic_work/xagentic-slicing/experiment/results/results_macros.tex
  OK /content/xagentic_work/xagentic-slicing/experiment/results/fig_shap_global.pdf
  OK /content/xagentic_work/xagentic-slicing/experiment/results/fig_escalation.pdf
  OK /content/xagentic_work/xagentic-slicing/experiment/results/fig_e2_latency.pdf
  OK /content/xagentic_work/xagentic-slicing/experiment/results/fig_e3_oov.pdf
  OK /content/xagentic_work/xagentic-slicing/experiment/results/fig_e4_combined.pdf
  -- /content/xagentic_work/xagentic-slicing/experiment/results/fig_e5_agentic.pdf
  OK /content/xagentic_work/xagentic-slicing/experiment/results/comparison.csv
  OK /content/xagentic_work/xagentic-slicing/experiment/results/e4_factorial.csv
  -- /content/xagentic_work/xagentic-slicing/experiment/results/e5_agentic.csv
  -- /content/xagentic_work/xagentic-slicing/experiment/results/e5_summary.json
  -- /content/xagentic_work/xagentic-slicing/experiment/results/llm_cache.json
  OK /content/xagentic_work/xagentic-slicing/experiment/results/all_summary.json

[run_all] tip: zip the whole results folder and download it:
  shutil.make_archive('xagentic_results', 'zip', '/content/xagentic_work/xagentic-slicing/experiment/results')
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e1_seeds.csv
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e4_seeds.csv

========================================================================
MULTI-SEED SUMMARY  (n = 5 seeds)
========================================================================
  EOneAccS              +91.7  std    1.3  95% CI [+90.7, +92.7]  (n=5)
  EOneOOVS              +12.7  std    2.2  95% CI [+11.0, +14.3]  (n=5)
  EOneFidS               +8.6  std    4.2  95% CI [+5.9, +12.2]  (n=5)
  model selected    Gradient Boosting in 4/5 seeds
  tau selected      0.90 in 4/5 seeds
  EFourAccS             +88.3  std    0.5  95% CI [+87.9, +88.6]  (n=5)
  EFourOOVS             +10.3  std    2.9  95% CI [+8.1, +12.5]  (n=5)
  DeltaExpl              -2.0  std    2.1  95% CI [-3.7, -0.4]  (n=5)
  DeltaPrior             +1.4  std    0.9  95% CI [+0.7, +2.0]  (n=5)
  Gamma                  -2.9  std    2.1  95% CI [-4.5, -1.2]  (n=5)

  --------------------------------------------------------------------
  INTERACTION gamma = -2.9 +/- 2.1 pts, 95% CI [-4.5, -1.2]
  -> the interval EXCLUDES zero: the gains demonstrably do not compose.
  --------------------------------------------------------------------

  -> /content/xagentic_work/xagentic-slicing/experiment/results/results_macros_seeds.tex
[run_seeds] copy results_macros_seeds.tex next to paper.tex.

In [58]:
!tail -100 /content/xagentic_5seed_quick.log

         variant      acc       f1  acc_known  acc_unseen  acc_generic  oov_gap  acc_ambiguous  intent_ms  escalated80  autonomous80
 A. Lexicon (E1) 0.902778 0.902753   0.992366       0.832     0.875000 0.138866       0.732283   0.268269     0.141667      0.951456
B. TF-IDF n-gram 0.919444 0.919263   0.992366       0.904     0.846154 0.117289       0.787402   0.148412     0.138889      0.961290
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e3_summary.json

[E3] B. TF-IDF n-gram closes the open-vocabulary gap by 2.2 pts (13.9 -> 11.7) and lifts accuracy by 1.7 pts
========================================================================
EXPERIMENT 4 -- Combined configuration (E2 x E3 factorial)
========================================================================
[E4] 35 distinct use-case phrases; 4 cells to evaluate
[E4] E1  exact + SHAP ...
     acc=0.9028  expl=  24.0864 ms  fid1=6.3x  oov_gap=13.9 pts/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

[E4] E2  exact + Decision-Path ...
     acc=0.8889  expl=   0.0123 ms  fid1=9.7x  oov_gap=12.4 pts
[E4] E3  TF-IDF + SHAP ...
     acc=0.9194  expl=  24.4900 ms  fid1=4.8x  oov_gap=11.7 pts
[E4] E4  TF-IDF + Decision-Path ...
     acc=0.8806  expl=   0.0246 ms  fid1=9.3x  oov_gap=11.8 pts
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e4_factorial.csv
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e4_summary.json

------------------------------------------------------------------------
                      cell      acc   expl_ms     fid1  oov_gap
          E1  exact + SHAP 0.902778 24.086384 6.333333 0.138866
 E2  exact + Decision-Path 0.888889  0.012253 9.727273 0.123966
         E3  TF-IDF + SHAP 0.919444 24.490031 4.833333 0.117289
E4  TF-IDF + Decision-Path 0.880556  0.024557 9.333333 0.117545
------------------------------------------------------------------------
[E4] accuracy effect  explainer only : -1.4 pts
[E4] accuracy effect  prior only     : +1.7 pts
[E4] accuracy effect  both combined  : -2.2 pts
[E4] interaction (combined - sum)    : -2.5 pts
[E4] OOV gap  13.9 -> 11.8 pts
[E4] explanation cost speedup        : 981x
  -> /content/xagentic_work/xagentic-slicing/experiment/results/comparison.csv

========================================================================
CROSS-EXPERIMENT COMPARISON
========================================================================
experiment                   focus  intent_agent              explainer      acc       f1    expl_ms  fidelity  oov_gap
        E1    Post-hoc explanation       Lexicon        SHAP (post-hoc) 0.902778 0.902753 251.208365  6.444444 0.138866
        E2      In-hoc explanation       Lexicon          SENN (in-hoc) 0.894444 0.894630   0.002940  8.062500 0.163308
        E3 Semantic intent parsing TF-IDF n-gram        SHAP (post-hoc) 0.919444 0.919263 251.208365  6.444444 0.117289
        E4      Combined (E2 + E3) TF-IDF n-gram Decision-Path (in-hoc) 0.880556 0.880714   0.024557  9.333333 0.117545

[run_all] writing LaTeX macros ...
  -> /content/xagentic_work/xagentic-slicing/experiment/results/results_macros.tex  (69 macros)
[run_all] rendering figures ...
  -> /content/xagentic_work/xagentic-slicing/experiment/results/fig_shap_global.pdf
  -> /content/xagentic_work/xagentic-slicing/experiment/results/fig_escalation.pdf
  -> /content/xagentic_work/xagentic-slicing/experiment/results/fig_e2_latency.pdf
  -> /content/xagentic_work/xagentic-slicing/experiment/results/fig_e3_oov.pdf
  -> /content/xagentic_work/xagentic-slicing/experiment/results/fig_e4_combined.pdf
  -> /content/xagentic_work/xagentic-slicing/experiment/results/all_summary.json

[run_all] done. Copy these back into the paper directory:
  OK /content/xagentic_work/xagentic-slicing/experiment/results/results_macros.tex
  OK /content/xagentic_work/xagentic-slicing/experiment/results/fig_shap_global.pdf
  OK /content/xagentic_work/xagentic-slicing/experiment/results/fig_escalation.pdf
  OK /content/xagentic_work/xagentic-slicing/experiment/results/fig_e2_latency.pdf
  OK /content/xagentic_work/xagentic-slicing/experiment/results/fig_e3_oov.pdf
  OK /content/xagentic_work/xagentic-slicing/experiment/results/fig_e4_combined.pdf
  -- /content/xagentic_work/xagentic-slicing/experiment/results/fig_e5_agentic.pdf
  OK /content/xagentic_work/xagentic-slicing/experiment/results/comparison.csv
  OK /content/xagentic_work/xagentic-slicing/experiment/results/e4_factorial.csv
  -- /content/xagentic_work/xagentic-slicing/experiment/results/e5_agentic.csv
  -- /content/xagentic_work/xagentic-slicing/experiment/results/e5_summary.json
  -- /content/xagentic_work/xagentic-slicing/experiment/results/llm_cache.json
  OK /content/xagentic_work/xagentic-slicing/experiment/results/all_summary.json

[run_all] tip: zip the whole results folder and download it:
  shutil.make_archive('xagentic_results', 'zip', '/content/xagentic_work/xagentic-slicing/experiment/results')
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e1_seeds.csv
  -> /content/xagentic_work/xagentic-slicing/experiment/results/e4_seeds.csv

========================================================================
MULTI-SEED SUMMARY  (n = 5 seeds)
========================================================================
  EOneAccS              +91.7  std    1.3  95% CI [+90.7, +92.7]  (n=5)
  EOneOOVS              +12.7  std    2.2  95% CI [+11.0, +14.3]  (n=5)
  EOneFidS               +8.6  std    4.2  95% CI [+5.9, +12.2]  (n=5)
  model selected    Gradient Boosting in 4/5 seeds
  tau selected      0.90 in 4/5 seeds
  EFourAccS             +88.3  std    0.5  95% CI [+87.9, +88.6]  (n=5)
  EFourOOVS             +10.3  std    2.9  95% CI [+8.1, +12.5]  (n=5)
  DeltaExpl              -2.0  std    2.1  95% CI [-3.7, -0.4]  (n=5)
  DeltaPrior             +1.4  std    0.9  95% CI [+0.7, +2.0]  (n=5)
  Gamma                  -2.9  std    2.1  95% CI [-4.5, -1.2]  (n=5)

  --------------------------------------------------------------------
  INTERACTION gamma = -2.9 +/- 2.1 pts, 95% CI [-4.5, -1.2]
  -> the interval EXCLUDES zero: the gains demonstrably do not compose.
  --------------------------------------------------------------------

  -> /content/xagentic_work/xagentic-slicing/experiment/results/results_macros_seeds.tex
[run_seeds] copy results_macros_seeds.tex next to paper.tex.

In [59]:
!find /content/xagentic_work/xagentic-slicing/experiment \
    -maxdepth 3 \
    -type f \
    | grep -Ei "seed|aggregate|summary|comparison" \
    | sort

/content/xagentic_work/xagentic-slicing/experiment/results/all_summary.json
/content/xagentic_work/xagentic-slicing/experiment/results_before_e4/all_summary.json
/content/xagentic_work/xagentic-slicing/experiment/results_before_e4/comparison.csv
/content/xagentic_work/xagentic-slicing/experiment/results_before_e4/e1_summary.json
/content/xagentic_work/xagentic-slicing/experiment/results_before_e4/e2_summary.json
/content/xagentic_work/xagentic-slicing/experiment/results_before_e4/e3_summary.json
/content/xagentic_work/xagentic-slicing/experiment/results/comparison.csv
/content/xagentic_work/xagentic-slicing/experiment/results/e1_seeds.csv
/content/xagentic_work/xagentic-slicing/experiment/results/e1_summary.json
/content/xagentic_work/xagentic-slicing/experiment/results/e2_summary.json
/content/xagentic_work/xagentic-slicing/experiment/results/e3_summary.json
/content/xagentic_work/xagentic-slicing/experiment/results/e4_seeds.csv
/content/xagentic_work/xagentic-slicing/experiment/results/e4_summary.json
/content/xagentic_work/xagentic-slicing/experiment/results/results_macros_seeds.tex
/content/xagentic_work/xagentic-slicing/experiment/results/seeds/all_summary_seed42.json
/content/xagentic_work/xagentic-slicing/experiment/results/seeds/all_summary_seed43.json
/content/xagentic_work/xagentic-slicing/experiment/results/seeds/all_summary_seed44.json
/content/xagentic_work/xagentic-slicing/experiment/results/seeds/all_summary_seed45.json
/content/xagentic_work/xagentic-slicing/experiment/results/seeds/all_summary_seed46.json
/content/xagentic_work/xagentic-slicing/experiment/results/seeds/e1_models_seed42.csv
/content/xagentic_work/xagentic-slicing/experiment/results/seeds/e1_models_seed43.csv
/content/xagentic_work/xagentic-slicing/experiment/results/seeds/e1_models_seed44.csv
/content/xagentic_work/xagentic-slicing/experiment/results/seeds/e1_models_seed45.csv
/content/xagentic_work/xagentic-slicing/experiment/results/seeds/e1_models_seed46.csv
/content/xagentic_work/xagentic-slicing/experiment/results/seeds/e4_factorial_seed42.csv
/content/xagentic_work/xagentic-slicing/experiment/results/seeds/e4_factorial_seed43.csv
/content/xagentic_work/xagentic-slicing/experiment/results/seeds/e4_factorial_seed44.csv
/content/xagentic_work/xagentic-slicing/experiment/results/seeds/e4_factorial_seed45.csv
/content/xagentic_work/xagentic-slicing/experiment/results/seeds/e4_factorial_seed46.csv
/content/xagentic_work/xagentic-slicing/experiment/run_seeds.py

In [52]:
!find . -maxdepth 3 -type f | sort | grep -E "seed|multi|aggregate|summary"

./results/all_summary.json
./results_before_e4/all_summary.json
./results_before_e4/e1_summary.json
./results_before_e4/e2_summary.json
./results_before_e4/e3_summary.json
./results/e1_seeds.csv
./results/e1_summary.json
./results/e2_summary.json
./results/e3_summary.json
./results/e4_seeds.csv
./results/e4_summary.json
./results/results_macros_seeds.tex
./results/seeds/all_summary_seed42.json
./results/seeds/all_summary_seed43.json
./results/seeds/all_summary_seed44.json
./results/seeds/all_summary_seed45.json
./results/seeds/all_summary_seed46.json
./results/seeds/e1_models_seed42.csv
./results/seeds/e1_models_seed43.csv
./results/seeds/e1_models_seed44.csv
./results/seeds/e1_models_seed45.csv
./results/seeds/e1_models_seed46.csv
./results/seeds/e4_factorial_seed42.csv
./results/seeds/e4_factorial_seed43.csv
./results/seeds/e4_factorial_seed44.csv
./results/seeds/e4_factorial_seed45.csv
./results/seeds/e4_factorial_seed46.csv
./run_seeds.py

In [53]:
!find . -maxdepth 2 -type d | sort

.
./__pycache__
./results
./results_before_e4
./results/seeds

In [55]:
!grep -nE "seed_runs|results_seed|seed_|aggregate|mkdir|makedirs" run_seeds.py

67:    os.makedirs(SEEDS_DIR, exist_ok=True)
139:                    help="skip running; just re-aggregate existing seed outputs")

In [62]:
import os
import shutil

EXP = "/content/xagentic_work/xagentic-slicing/experiment"
RESULTS = os.path.join(EXP, "results")
QUICK = os.path.join(EXP, "results_5seed_quick")

if os.path.exists(QUICK):
    shutil.rmtree(QUICK)

shutil.copytree(RESULTS, QUICK)

print("Quick 5-seed results preserved:")
print(QUICK)

Quick 5-seed results preserved:
/content/xagentic_work/xagentic-slicing/experiment/results_5seed_quick

In [63]:
import os
import shutil

RESULTS = "/content/xagentic_work/xagentic-slicing/experiment/results"

if os.path.exists(RESULTS):
    shutil.rmtree(RESULTS)

os.makedirs(RESULTS, exist_ok=True)

print("Clean results directory:", RESULTS)
print("Contents:", os.listdir(RESULTS))

Clean results directory: /content/xagentic_work/xagentic-slicing/experiment/results
Contents: []

In [64]:
%cd /content/xagentic_work/xagentic-slicing/experiment

!python run_seeds.py \
    --seeds 42 43 44 45 46 \
    --no-llm \
    --no-embeddings \
    2>&1 | tee /content/xagentic_e1_e4_5seed_FINAL.log

/content/xagentic_work/xagentic-slicing/experiment

========================================================================
SEED 42
========================================================================
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(

In [65]:
!grep -nE "SEED 42|SEED 43|SEED 44|SEED 45|SEED 46|generating shared corpus|MULTI-SEED SUMMARY" \
    /content/xagentic_e1_e4_5seed_FINAL.log

3:SEED 42
331:[run_all] generating shared corpus (n=3000, seed=42) ...
536:SEED 43
864:[run_all] generating shared corpus (n=3000, seed=43) ...
1068:SEED 44
1396:[run_all] generating shared corpus (n=3000, seed=44) ...
1600:SEED 45
1928:[run_all] generating shared corpus (n=3000, seed=45) ...
2132:SEED 46
2460:[run_all] generating shared corpus (n=3000, seed=46) ...
2665:MULTI-SEED SUMMARY  (n = 5 seeds)

In [66]:
!grep -Ein "traceback|exception|failed|fatal" \
    /content/xagentic_e1_e4_5seed_FINAL.log \
    || echo "PASS — no traceback/exception/failure/fatal messages."

PASS — no traceback/exception/failure/fatal messages.

In [67]:
import os

RESULTS = "/content/xagentic_work/xagentic-slicing/experiment/results"

important = [
    "e1_seeds.csv",
    "e4_seeds.csv",
    "results_macros_seeds.tex",
]

for f in important:
    p = os.path.join(RESULTS, f)

    if os.path.isfile(p):
        print(f"PASS  {f:30s} {os.path.getsize(p):>10,d} bytes")
    else:
        print(f"FAIL  {f}")

PASS  e1_seeds.csv                          669 bytes
PASS  e4_seeds.csv                        1,003 bytes
PASS  results_macros_seeds.tex            1,331 bytes

In [68]:
import pandas as pd
import os

RESULTS = "/content/xagentic_work/xagentic-slicing/experiment/results"

e1_seeds = pd.read_csv(
    os.path.join(RESULTS, "e1_seeds.csv")
)

display(e1_seeds)

,seed,acc,macro_f1,oov_gap,acc_ambiguous,model,tau,fid1,expl_ms
0,42,92.777778,0.927832,11.582665,77.689243,Gradient Boosting,0.8,8.000000,240.271914
1,43,93.000000,0.930081,10.864237,80.000000,Gradient Boosting,0.8,16.769231,235.068401
2,44,94.222222,0.942292,9.914216,82.758621,Gradient Boosting,0.9,16.500000,232.162191
3,45,93.000000,0.929772,12.164580,81.468531,Gradient Boosting,0.8,8.363636,232.616838
4,46,92.555556,0.925612,12.077468,80.155642,Decision Tree,0.9,9.625000,0.011044

In [69]:
e4_seeds = pd.read_csv(
    os.path.join(RESULTS, "e4_seeds.csv")
)

display(e4_seeds)

,seed,acc_base,acc_e2_only,acc_e3_only,acc_combined,d_expl,d_prior,d_combined,gamma,oov_base,oov_combined
0,42,92.777778,91.666667,95.222222,90.333333,-1.111111,2.444444,-2.444444,-3.777778,11.582665,14.789016
1,43,93.000000,91.888889,95.222222,90.000000,-1.111111,2.222222,-3.000000,-4.111111,10.864237,3.852631
2,44,94.222222,92.777778,95.222222,90.888889,-1.444444,1.000000,-3.333333,-2.888889,9.914216,6.341501
3,45,93.000000,89.666667,96.111111,92.333333,-3.333333,3.111111,-0.666667,-0.444444,12.164580,11.031588
4,46,93.333333,92.555556,96.000000,93.555556,-0.777778,2.666667,0.222222,-1.666667,10.785016,8.032519

In [70]:
!grep -A 30 "MULTI-SEED SUMMARY" \
    /content/xagentic_e1_e4_5seed_FINAL.log

MULTI-SEED SUMMARY  (n = 5 seeds)
========================================================================
  EOneAccS              +93.1  std    0.6  95% CI [+92.7, +93.7]  (n=5)
  EOneOOVS              +11.3  std    0.9  95% CI [+10.5, +12.0]  (n=5)
  EOneFidS              +11.9  std    4.4  95% CI [+8.5, +15.2]  (n=5)
  model selected    Gradient Boosting in 4/5 seeds
  tau selected      0.80 in 3/5 seeds
  EFourAccS             +91.4  std    1.5  95% CI [+90.3, +92.7]  (n=5)
  EFourOOVS              +8.8  std    4.2  95% CI [+5.7, +12.1]  (n=5)
  DeltaExpl              -1.6  std    1.0  95% CI [-2.4, -1.0]  (n=5)
  DeltaPrior             +2.3  std    0.8  95% CI [+1.6, +2.8]  (n=5)
  Gamma                  -2.6  std    1.5  95% CI [-3.7, -1.4]  (n=5)

  --------------------------------------------------------------------
  INTERACTION gamma = -2.6 +/- 1.5 pts, 95% CI [-3.7, -1.4]
  -> the interval EXCLUDES zero: the gains demonstrably do not compose.
  --------------------------------------------------------------------

  -> /content/xagentic_work/xagentic-slicing/experiment/results/results_macros_seeds.tex
[run_seeds] copy results_macros_seeds.tex next to paper.tex.

In [71]:
import shutil
import os

RESULTS = "/content/xagentic_work/xagentic-slicing/experiment/results"

archive = shutil.make_archive(
    "/content/xagentic_e1_e4_5seed_results",
    "zip",
    RESULTS
)

print("Created:")
print(archive)

print(
    "Size:",
    round(os.path.getsize(archive) / 1024 / 1024, 2),
    "MB"
)

Created:
/content/xagentic_e1_e4_5seed_results.zip
Size: 0.29 MB

In [72]:
!unzip -l /content/xagentic_e1_e4_5seed_results.zip

Archive:  /content/xagentic_e1_e4_5seed_results.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2026-10-05 12:13   seeds/
     3041  2026-10-05 12:13   results_macros.tex
      478  2026-10-05 12:12   e3_variants.csv
     3260  2026-10-05 12:13   e4_summary.json
    23542  2026-10-05 12:13   all_summary.json
    14440  2026-10-05 12:13   fig_e2_latency.pdf
      669  2026-10-05 12:13   e1_seeds.csv
   761399  2026-10-05 12:08   corpus.csv
     1517  2026-10-05 12:09   e1_local_explanations.json
     4843  2026-10-05 12:09   e1_summary.json
    19087  2026-10-05 12:13   fig_e4_combined.pdf
    11259  2026-10-05 12:13   fig_e3_oov.pdf
      456  2026-10-05 12:09   e1_shap_global.csv
     4619  2026-10-05 12:12   e3_summary.json
      909  2026-10-05 12:09   e1_models.csv
       27  2026-10-05 12:09   e1_confusion.csv
     3176  2026-10-05 12:12   e3_semantic_cache.json
      653  2026-10-05 12:13   comparison.csv
      205  2026-10-05 12:09   e1_per_class.csv
      545  2026-10-05 12:09   e1_escalation_signals.csv
     1331  2026-10-05 12:13   results_macros_seeds.tex
     8047  2026-10-05 12:12   e2_summary.json
    13400  2026-10-05 12:13   fig_shap_global.pdf
     1003  2026-10-05 12:13   e4_seeds.csv
     1333  2026-10-05 12:13   e4_factorial.csv
    14841  2026-10-05 12:13   fig_escalation.pdf
     1268  2026-10-05 12:12   e2_explainers.csv
      456  2026-10-05 12:09   e1_escalation.csv
      455  2026-10-05 12:09   e1_escalation_oof.csv
      865  2026-10-05 11:59   seeds/e1_models_seed45.csv
    23308  2026-10-05 11:49   seeds/all_summary_seed43.json
    23315  2026-10-05 11:40   seeds/all_summary_seed42.json
     1347  2026-10-05 12:08   seeds/e4_factorial_seed45.csv
    23339  2026-10-05 12:08   seeds/all_summary_seed45.json
    23364  2026-10-05 11:58   seeds/all_summary_seed44.json
     1307  2026-10-05 11:49   seeds/e4_factorial_seed43.csv
      909  2026-10-05 12:09   seeds/e1_models_seed46.csv
      896  2026-10-05 11:31   seeds/e1_models_seed42.csv
     1295  2026-10-05 11:58   seeds/e4_factorial_seed44.csv
     1333  2026-10-05 12:13   seeds/e4_factorial_seed46.csv
      863  2026-10-05 11:40   seeds/e1_models_seed43.csv
     1336  2026-10-05 11:40   seeds/e4_factorial_seed42.csv
      836  2026-10-05 11:50   seeds/e1_models_seed44.csv
    23542  2026-10-05 12:13   seeds/all_summary_seed46.json
---------                     -------
  1024114                     44 files

In [73]:
from google.colab import files

files.download(
    "/content/xagentic_e1_e4_5seed_results.zip"
)